// Mapa compartilhado de labels e terminologias clínicas do Zemda em português
export const clinicalLabels: Record<string, string> = {
  // Identificação e Atendimento
  patientName: 'Paciente',
  patient_name: 'Paciente',
  professionalName: 'Profissional responsável',
  professional_name: 'Profissional responsável',
  serviceName: 'Especialidade / Serviço',
  service_name: 'Especialidade / Serviço',
  sessionDate: 'Data do atendimento',
  session_date: 'Data do atendimento',
  consultationDate: 'Data da consulta',
  consultation_date: 'Data da consulta',
  consultationTime: 'Horário da consulta',
  consultation_time: 'Horário da consulta',
  moduleType: 'Módulo de atendimento',
  module_type: 'Módulo de atendimento',
  title: 'Título do registro',
  clinicalEvolution: 'Evolução clínica',
  clinical_evolution: 'Evolução clínica',
  technicalNotes: 'Observações clínicas',
  technical_notes: 'Observações clínicas',
  conducts: 'Condutas realizadas',

  // Anamnese e Histórico Clínico Geral
  anamnesisData: 'Anamnese',
  anamnesis: 'Anamnese',
  clinicalHistory: 'Histórico clínico',
  chiefComplaint: 'Queixa principal',
  complaint: 'Queixa principal',
  hpi: 'História da moléstia atual (HMA)',
  pastMedicalHistory: 'Histórico médico pregresso',
  familyHistory: 'Histórico familiar',
  medicalHistory: 'Histórico médico',
  dentalHistory: 'Histórico odontológico',
  occupationalHistory: 'Histórico ocupacional',
  dailyRoutine: 'Rotina diária',
  habitsLifestyle: 'Hábitos e estilo de vida',
  habits: 'Hábitos e estilo de vida',
  bowelHabits: 'Hábitos intestinais',
  smoking: 'Tabagismo',
  alcohol: 'Consumo de bebidas alcoólicas',
  physicalActivity: 'Atividade física',
  routineWakeUp: 'Horário de despertar',
  routineSleep: 'Horário de sono',
  interests: 'Interesses e preferências',
  environment: 'Ambiente de convivência',

  // Condições e Patologias Sistêmicas
  systemicDiseases: 'Doenças sistêmicas',
  allergies: 'Alergias conhecidas',
  currentMedications: 'Medicamentos em uso contínuo',
  medications: 'Medicamentos',
  anesthesiaHistory: 'Histórico anestésico e intercorrências',
  previousSurgeries: 'Cirurgias prévias',
  previousTreatments: 'Tratamentos anteriores',
  diabetes: 'Diabetes mellitus',
  hypertension: 'Hipertensão arterial',
  pregnant: 'Gestação',
  pregnancy: 'Gestação',
  heartDisease: 'Doença cardiovascular',
  contraindications: 'Contraindicações',
  adverseEvents: 'Eventos adversos ou intercorrências',

  // Sinais Vitais e Biometria
  vitalSigns: 'Sinais vitais',
  bloodPressure: 'Pressão arterial (PA)',
  heartRate: 'Frequência cardíaca (bpm)',
  respiratoryRate: 'Frequência respiratória (rpm)',
  temperature: 'Temperatura corporal (°C)',
  oxygenSaturation: 'Saturação de O₂ (%)',
  weight: 'Peso corporal (kg)',
  height: 'Estatura (cm)',
  bmi: 'Índice de massa corporal (IMC)',
  bmr: 'Taxa metabólica basal (TMB)',
  totalEnergy: 'Gasto energético total (GET)',
  waistCirc: 'Circunferência da cintura (cm)',
  abdominalCirc: 'Circunferência abdominal (cm)',
  hipCirc: 'Circunferência do quadril (cm)',
  whr: 'Relação cintura-quadril (RCQ)',
  whtr: 'Relação cintura-estatura (RCE)',

  // Composição Corporal / Cineantropometria (Personal Trainer / Nutrição)
  bodyComposition: 'Composição corporal',
  bodyFatPct: 'Percentual de gordura (%)',
  body_fat_percentage: 'Percentual de gordura (%)',
  fatMassKg: 'Massa gorda (kg)',
  fat_mass_kg: 'Massa gorda (kg)',
  leanMassKg: 'Massa magra (kg)',
  lean_mass_kg: 'Massa magra (kg)',
  muscleMassKg: 'Massa muscular esquelética (kg)',
  muscle_mass_kg: 'Massa muscular esquelética (kg)',
  tavVal: 'Taxa de adiposidade visceral (TAV)',
  tav_value: 'Taxa de adiposidade visceral (TAV)',
  tavClassification: 'Classificação TAV',
  tav_classification: 'Classificação TAV',
  bioimpedanceData: 'Bioimpedância',
  anthropometryForm: 'Avaliação antropométrica',

  // Nutrição e Plano Alimentar
  recallData: 'Recordatório alimentar',
  recallDate: 'Data do recordatório',
  isWeekend: 'Final de semana',
  meals: 'Refeições',
  mealName: 'Nome da refeição',
  mealTime: 'Horário da refeição',
  items: 'Alimentos prescritos',
  food: 'Alimento',
  portion: 'Porção',
  calories: 'Calorias (kcal)',
  calorieTarget: 'Meta calórica diária (kcal)',
  waterTargetMl: 'Meta hídrica diária (ml)',
  waterIntakeMl: 'Ingestão hídrica atual (ml)',
  carb: 'Carboidratos',
  carbG: 'Carboidratos (g)',
  carbPercent: 'Carboidratos (%)',
  protein: 'Proteínas',
  protG: 'Proteínas (g)',
  protGPerKg: 'Proteínas (g/kg)',
  proteinPercent: 'Proteínas (%)',
  fat: 'Gorduras',
  fatG: 'Gorduras (g)',
  fatPercent: 'Gorduras (%)',
  calculationsData: 'Cálculos nutricionais',
  calculationInputs: 'Parâmetros de cálculo',
  calcFormula: 'Fórmula preditiva utilizada',
  activityFactor: 'Fator de atividade física',
  injuryFactor: 'Fator térmico / de injúria',
  mealPlanData: 'Plano alimentar',
  mealPlan: 'Plano alimentar',
  goalsData: 'Metas nutricionais',
  goalForm: 'Meta traçada',

  // Odontologia (ZemdaOdonto)
  odontogramData: 'Odontograma',
  toothChanges: 'Alterações dentárias registradas',
  toothNumber: 'Dente',
  tooth: 'Dente',
  face: 'Face dental',
  condition: 'Condição clínica',
  previousCondition: 'Condição prévia',
  site: 'Sítio / Face de sondagem',
  probingDepth: 'Profundidade de sondagem (mm)',
  bleeding: 'Sangramento à sondagem',
  bleedingOnProbing: 'Sangramento à sondagem',
  suppuration: 'Supuração',
  mobility: 'Grau de mobilidade',
  furcation: 'Envolvimento de furca',
  recession: 'Recessão gengival (mm)',
  plaqueIndex: 'Índice de placa bacteriana',
  gingivalIndex: 'Índice gengival',
  pocketDepth: 'Profundidade de bolsa (mm)',
  insertionLoss: 'Perda de inserção (mm)',
  periodontalData: 'Exame periodontal',
  endodonticData: 'Endodontia',
  pulpDiagnosis: 'Diagnóstico pulpar',
  periapicalDiagnosis: 'Diagnóstico periapical',
  vitalityTest: 'Teste de sensibilidade pulpar',
  percussion: 'Teste de percussão',
  palpation: 'Palpação',
  coldTest: 'Teste térmico ao frio',
  heatTest: 'Teste térmico ao calor',
  workingLength: 'Comprimento de trabalho (CT)',
  canals: 'Canais radiculares instrumentados',
  obturation: 'Obturação endodôntica',
  prostheticData: 'Prótese dentária',
  orthodonticData: 'Ortodontia',
  facialData: 'Harmonização orofacial',
  labName: 'Laboratório de prótese',
  workType: 'Tipo de trabalho protético',
  shadeColor: 'Cor dental (Escala VITA)',
  material: 'Material protético',
  sentDate: 'Data de envio ao laboratório',
  expectedDate: 'Previsão de entrega',
  receivedDate: 'Data de recebimento',
  brushingFrequency: 'Frequência diária de escovação',
  flossing: 'Uso diário de fio dental',
  lastVisit: 'Data da última visita odontológica',

  // Fisioterapia e Reabilitação (ZemdaFisio)
  physioDiagnosis: 'Diagnóstico fisioterapêutico',
  painScore: 'Escala de dor (EVA 0–10)',
  painLocation: 'Localização anatômica da dor',
  painCharacteristics: 'Características da dor',
  painAtRest: 'Dor em repouso (EVA 0–10)',
  painOnMovement: 'Dor ao movimento (EVA 0–10)',
  bodyMapJson: 'Mapeamento topográfico da dor',
  bodyMapImage: 'Imagem anatômica da dor',
  goniometryData: 'Goniometria / Amplitude de movimento',
  joint: 'Articulação avaliada',
  movement: 'Movimento articular',
  degrees: 'Amplitude medida (graus °)',
  normal: 'Valor normativo de referência',
  muscleStrengthData: 'Força muscular (Escala de Oxford)',
  muscle: 'Grupo muscular testado',
  grade: 'Grau de força (0 a 5)',
  rightGrade: 'Grau de força lado direito',
  leftGrade: 'Grau de força lado esquerdo',
  right: 'Lado direito',
  left: 'Lado esquerdo',
  postureData: 'Avaliação postural',
  postureAnterior: 'Inspeção postural — vista anterior',
  postureLateral: 'Inspeção postural — vista lateral',
  posturePosterior: 'Inspeção postural — vista posterior',
  gaitAnalysis: 'Análise biomecânica da marcha',
  testsData: 'Testes funcionais específicos',
  cbdfData: 'Classificação funcional (CIF)',
  cbdfBodyFunction: 'Funções do corpo (CIF)',
  cbdfBodyStructure: 'Estruturas anatômicas (CIF)',
  cbdfActivityParticipation: 'Atividade e participação (CIF)',
  cbdfContextualFactors: 'Fatores contextuais ambientais e pessoais (CIF)',
  cbdfDiagnosticSummary: 'Síntese diagnóstica funcional (CIF)',
  treatmentResources: 'Recursos e modalidades terapêuticas utilizadas',
  conductsExercises: 'Exercícios terapêuticos e condutas',
  homeExercisesData: 'Exercícios domiciliares prescritos',
  reassessmentDate: 'Data prevista para reavaliação',

  // Fonoaudiologia (ZemdaFono)
  phonemesData: 'Avaliação fonética e fonológica',
  languageData: 'Avaliação de linguagem e comunicação',
  orofacialData: 'Motricidade orofacial e mastigação',
  voiceData: 'Avaliação da voz e qualidade vocal',
  audioData: 'Amostra de áudio vocal gravada',
  fluencyData: 'Avaliação da fluência da fala',
  dysphagiaData: 'Avaliação da deglutição (disfagia)',
  audiologyData: 'Triagem e avaliação audiológica',

  // Terapia Ocupacional (ZemdaTO)
  profileData: 'Perfil ocupacional',
  adlData: 'Atividades de vida diária (AVDs)',
  sensoryData: 'Processamento sensorial',
  motorCognitiveData: 'Funções motoras e cognitivas',
  treatmentPlanData: 'Plano de intervenção ocupacional',
  assistiveTechnologyData: 'Tecnologia assistiva e adaptações',

  // Psicologia & Psicopedagogia (ZemdaPsico / ZemdaPP)
  demandDescription: 'Demanda e queixa inicial',
  mentalStatus: 'Exame do estado mental',
  techniquesUsed: 'Técnicas e intervenções realizadas',
  therapeuticGoals: 'Objetivos terapêuticos estabelecidos',
  familyGuidance: 'Orientações aos familiares / responsáveis',
  schoolGuidance: 'Orientações pedagógicas / escolares',
  sessionsCount: 'Número de sessões realizadas',
  estimatedSessions: 'Previsão de sessões',
  sessionFrequency: 'Frequência dos atendimentos',

  // Medicina Geral & Especialidades (ZemdaMed)
  medicalDiagnosis: 'Diagnóstico médico',
  diagnosis: 'Diagnóstico',
  hypothesis: 'Hipótese diagnóstica',
  hypotheses: 'Hipóteses diagnósticas',
  diagnosticHypotheses: 'Hipóteses diagnósticas',
  cidCode: 'Código CID',
  cidDescription: 'Descrição CID',
  physicalExam: 'Exame físico detalhado',
  neurologicalExam: 'Exame neurológico',
  soapNotes: 'Evolução clínica SOAP',
  assessment: 'Avaliação clínica',
  assessmentData: 'Avaliação clínica',

  // Estética e Procedimentos Faciais/Corporais (ZemdaEstetic)
  fitzpatrick: 'Fototipo de Fitzpatrick',
  glogau: 'Grau de fotoenvelhecimento (Glogau)',
  facialRegion: 'Região de aplicação',
  region: 'Região corporal',
  productName: 'Produto / Substância aplicada',
  productBrand: 'Marca comercial',
  batchLot: 'Lote do produto',
  lotNumber: 'Número de lote',
  expiryDate: 'Data de validade do produto',
  unitsQuantity: 'Dose / Unidades aplicadas',
  techniqueNotes: 'Técnica de aplicação e conduta',
  touchup_required: 'Necessidade de retoque',
  touchup_description: 'Descrição do retoque programado',
  biological_response: 'Resposta tecidual / biológica',
  patient_feedback: 'Relato e percepção do paciente',
  evaluation_notes: 'Notas de reavaliação estética',

  // Prescrições, Orientações e Documentos
  prescription: 'Prescrição medicamentosa',
  certificate: 'Atestado emitido',
  examRequest: 'Solicitação de exames',
  examsList: 'Lista de exames solicitados',
  clinicalIndication: 'Indicação clínica do exame',
  exams: 'Exames complementares',
  generalGuidelines: 'Orientações gerais ao paciente',
  guidelines: 'Orientações ao paciente',
  referral: 'Encaminhamento interprofissional',
  referralReason: 'Motivo do encaminhamento',
  referredByProfessionalId: 'Profissional de origem',
  returnAppt: 'Retorno clínico',
  returnAppointment: 'Consulta de retorno',
  returnInDays: 'Prazo previsto de retorno (dias)',
  returnDate: 'Data prevista de retorno',
  scheduled_date: 'Data agendada',
  dosage: 'Posologia / Dosagem',
  frequency: 'Frequência de administração',
  duration: 'Duração do tratamento',
  route: 'Via de administração',
  medication: 'Medicamento prescrito',
  attachments: 'Anexos clínicos',
  documents: 'Documentos vinculados',
  proceduresPerformed: 'Procedimentos clínicos executados',
  procedure: 'Procedimento',
  procedureName: 'Procedimento',
  procedure_name: 'Procedimento realizado',
  conduct: 'Conduta clínica',
  treatment: 'Tratamento',
  plan: 'Plano de tratamento',
  treatmentPlan: 'Plano terapêutico',
  objectives: 'Objetivos terapêuticos',
  goals: 'Metas clínicas',

  // Faces Dentais em Português
  distovestibular: 'Distovestibular',
  mesiovestibular: 'Mesiovestibular',
  distolingual: 'Distolingual',
  mesiolingual: 'Mesiolingual',
  distopalatal: 'Distopalatina',
  mesiopalatal: 'Mesiopalatina',
  buccal: 'Vestibular',
  vestibular: 'Vestibular',
  lingual: 'Lingual',
  palatal: 'Palatina',
  mesial: 'Mesial',
  distal: 'Distal',
  occlusal: 'Oclusal',
  incisal: 'Incisal',
  cervical: 'Cervical',

  // Exercícios e Treinamento Físico
  division: 'Divisão de treino',
  structure_type: 'Estrutura do treinamento',
  exercises: 'Exercícios prescritos',
  sets: 'Séries',
  reps: 'Repetições',
  load_kg: 'Carga (kg)',
  rest_seconds: 'Intervalo de descanso (s)',
  custom_name: 'Nome do exercício',

  // Orçamentos
  budget: 'Orçamento clínico',
  budgetData: 'Proposta orçamentária',
  budgetNumber: 'Número da proposta',
  budgetId: 'Identificador do orçamento',
  unitPrice: 'Valor unitário (R$)',
  totalPrice: 'Valor total (R$)',
  costValue: 'Custo laboratorial (R$)',
  totalValue: 'Valor total bruto (R$)',
  discountValue: 'Desconto concedido (R$)',
  finalValue: 'Valor final líquido (R$)',
  paymentTerms: 'Condições de pagamento aceitas',
  status: 'Status do registro',
  quantity: 'Quantidade'
};

export const labels = clinicalLabels;

// Formata de forma robusta e elegante qualquer chave clínica para português, nunca deixando camelCase ou snake_case
export function formatClinicalKey(key: string): string {
  if (!key) return '';
  const trimmed = key.trim();

  // 1. Busca exata no dicionário clínico
  if (clinicalLabels[trimmed]) return clinicalLabels[trimmed];

  // 2. Busca com conversão de snake_case para camelCase
  const camel = trimmed.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
  if (clinicalLabels[camel]) return clinicalLabels[camel];

  // 3. Busca com conversão de camelCase para snake_case
  const snake = trimmed.replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase();
  if (clinicalLabels[snake]) return clinicalLabels[snake];

  // 4. Se já for uma frase com espaços ou pontuação legível
  if (/^[A-ZÁÀÂÃÉÊÍÓÔÕÚÇ0-9][^_]*[ áàâãéêíóôõúç]/i.test(trimmed)) {
    return trimmed;
  }

  // 5. Se for índice numérico
  if (/^\d+$/.test(trimmed)) {
    return `Item ${trimmed}`;
  }

  // 6. Fallback refinado: separa palavras e capitaliza a primeira letra
  const words = trimmed
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/[_-]+/g, ' ')
    .toLowerCase()
    .trim();

  if (!words) return '';
  return words.charAt(0).toUpperCase() + words.slice(1);
}
