import { type Locator } from '@playwright/test';
import { test, expect } from '../../helpers/audit-test';
import { login, apiLogin } from '../../helpers/session';

const field = (scope: Locator, name: string) => scope.locator('label').filter({ hasText: new RegExp(`^${name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s*\\*?$`) }).locator('..').locator('input, select, textarea').first();

test('@critical Paciente, serviço e estoque persistem após F5; entrada 100 e saída 20', async ({ page, request }) => {
  await login(page, 'manager');
  const headers = await apiLogin(request, 'manager');
  await page.goto('/pacientes');
  await page.getByRole('button', { name: 'Novo Paciente', exact: true }).click();
  await page.getByPlaceholder('Nome completo', { exact: true }).fill('e2e-patient-operacional');
  await field(page.locator('form'), 'WhatsApp / Telefone').fill('11999998888');
  await page.getByPlaceholder('cliente@email.com').fill('e2e-patient-operacional@test.invalid');
  const patientSaved = page.waitForResponse(r => r.url().endsWith('/v1/patients') && r.request().method() === 'POST');
  await page.getByRole('button', { name: 'Salvar Cadastro', exact: true }).click();
  const savedPatient = await patientSaved;
  expect(savedPatient.ok()).toBe(true);
  const patientId = (await savedPatient.json()).id;
  await page.reload();
  await expect(page.getByRole('table').getByText('e2e-patient-operacional', { exact: true })).toBeVisible();
  const patients = await request.get('/api/v1/patients?search=e2e-patient-operacional', { headers });
  expect((await patients.json()).find((item: any) => item.full_name === 'e2e-patient-operacional').email).toBe('e2e-patient-operacional@test.invalid');

  await page.goto('/servicos');
  await page.getByRole('button', { name: 'Novo Serviço', exact: true }).click();
  const serviceModal = page.getByRole('heading', { name: 'Novo Serviço', exact: true }).locator('xpath=../..');
  await field(serviceModal, 'Profissional Responsável').selectOption('pro-fisio');
  await page.getByPlaceholder('Ex: Consulta Odontológica Inicial').fill('e2e-service-operacional');
  await field(serviceModal, 'Preço (R$)').fill('180');
  await field(serviceModal, 'Duração (minutos)').fill('40');
  const serviceSaved = page.waitForResponse(r => r.url().endsWith('/v1/services') && r.request().method() === 'POST');
  await page.getByRole('button', { name: 'Salvar Serviço', exact: true }).click();
  expect((await serviceSaved).ok()).toBe(true);
  await page.reload();
  await expect(page.getByText('e2e-service-operacional', { exact: true })).toBeVisible();
  const services = await request.get('/api/v1/services', { headers });
  const service = (await services.json()).find((item: any) => item.name === 'e2e-service-operacional');
  expect(Number(service.price)).toBe(180);
  expect(service.duration_minutes).toBe(40);

  await page.goto('/agenda');
  await page.getByRole('button', { name: 'Agendar', exact: true }).click();
  const appointmentModal = page.getByRole('heading', { name: 'Novo Agendamento', exact: true }).locator('xpath=../..');
  await appointmentModal.getByPlaceholder(/Buscar paciente/).fill('e2e-patient-operacional');
  await appointmentModal.getByText('e2e-patient-operacional', { exact: true }).click();
  await field(appointmentModal, 'Profissional').selectOption('pro-fisio');
  await field(appointmentModal, 'Serviço').selectOption(service.id);
  const date = new Date();
  date.setDate(date.getDate() + 7);
  while (date.getDay() === 0) date.setDate(date.getDate() + 1);
  await appointmentModal.locator('input[type=date]').fill(date.toISOString().slice(0,10));
  await appointmentModal.getByRole('button', { name: /^\d{2}:\d{2}$/ }).first().click();
  const booked = page.waitForResponse(r => r.url().endsWith('/v1/appointments') && r.request().method() === 'POST');
  await appointmentModal.getByRole('button', { name: 'Confirmar Agendamento', exact: true }).click();
  const booking = await booked;
  expect(booking.ok(), await booking.text()).toBe(true);
  const appointmentId = (await booking.json()).id;
  await page.reload();
  const persisted = await request.get(`/api/v1/appointments/${appointmentId}`, { headers });
  expect(persisted.ok()).toBe(true);
  const appointment = (await persisted.json()).appointment;
  expect(appointment.patient_id).toBe(patientId);
  expect(appointment.professional_id).toBe('pro-fisio');
  expect(appointment.service_id).toBe(service.id);

  await page.goto('/estoque');
  await page.getByRole('button', { name: 'Novo Item de Estoque', exact: true }).click();
  const stockModal = page.getByRole('heading', { name: 'Cadastrar Item no Estoque' }).locator('xpath=../..');
  await page.getByPlaceholder('Ex: Luva Procedimento Nitrílica M, Agulha 30G...').fill('e2e-inventory-operacional');
  await field(stockModal, 'Qtd Atual (Inicial)').fill('100');
  await page.getByPlaceholder('Ex: LOTE2409A').fill('E2E-LOTE');
  await field(stockModal, 'Data de Validade').fill('2028-01-01');
  const stockSaved = page.waitForResponse(r => r.url().endsWith('/v1/inventory') && r.request().method() === 'POST');
  await page.getByRole('button', { name: 'Salvar Item', exact: true }).click();
  expect((await stockSaved).ok()).toBe(true);
  const row = page.getByRole('row').filter({ hasText: 'e2e-inventory-operacional' });
  await row.getByTitle('Lançar movimentação').click();
  const movementModal = page.getByRole('heading', { name: 'Movimentar Estoque' }).locator('xpath=../..');
  await movementModal.getByRole('button', { name: '- Saída', exact: true }).click();
  await field(movementModal, 'Quantidade').fill('20');
  await page.getByPlaceholder('Ex: Compra de reposição, Uso em procedimento, Perda').fill('Uso sintético E2E');
  const moved = page.waitForResponse(r => r.url().endsWith('/v1/inventory/movements') && r.request().method() === 'POST');
  await page.getByRole('button', { name: 'Confirmar Movimentação', exact: true }).click();
  expect((await moved).ok()).toBe(true);
  await page.reload();
  await expect(row).toContainText('80');
  const inventory = await request.get('/api/v1/inventory', { headers });
  const item = (await inventory.json()).items.find((item: any) => item.name === 'e2e-inventory-operacional');
  expect(item.quantity).toBe(80);
  expect(item.batch_number).toBe('E2E-LOTE');
  expect(item.expiration_date).toBe('2028-01-01');
});
