import { test, expect } from '@playwright/test';
import { login, apiLogin } from '../../helpers/session';

test('@critical login → atendimento → autosave → revisão → prontuário', async ({ page, request }) => {
  await login(page);
  await page.getByTitle('Iniciar Atendimento Rápido').click();
  await expect(page.getByText('Paciente teste fisio', { exact: true }).first()).toBeVisible();
  await page.getByRole('button', { name: 'Abrir ZemdaFisio', exact: true }).first().click();
  await page.getByRole('button', { name: '4. Dor & Zemda360', exact: true }).click();
  const scale = page.locator('[data-clinical-scale="pain"]').first();
  await expect(scale.locator('output')).toHaveText('Não avaliado');
  await scale.getByRole('slider').focus();
  await scale.getByRole('slider').press('Home');
  await expect(scale.locator('output')).toHaveText('EVA: 0/10');
  await scale.getByRole('slider').press('ArrowRight');
  await expect(scale.locator('output')).toHaveText('EVA: 1/10');
  await scale.getByRole('button', { name: 'Limpar' }).click();
  await expect(scale.locator('output')).toHaveText('Não avaliado');
  await scale.getByRole('slider').press('End');
  await expect(scale.locator('output')).toHaveText('EVA: 10/10');
  await page.getByRole('button', { name: '1. Evolução', exact: true }).click();
  const evolution = page.getByPlaceholder('Descreva detalhadamente o estado atual do paciente, intervenções aplicadas (cinesioterapia, mobilização articular, eletroterapia), resposta durante os exercícios e raciocínio clínico...');
  await expect(evolution).toHaveValue('');
  const text = 'Evolução exclusivamente sintética do teste automatizado.';
  const saved = page.waitForResponse(r => r.url().includes('/clinical/draft') && r.request().method() === 'POST' && r.ok());
  await evolution.fill(text);
  await saved;
  await page.getByRole('button', { name: '2. Anamnese', exact: true }).click();
  await expect(page.getByPlaceholder('Relato da queixa nas palavras do paciente...')).toHaveValue('');
  await page.getByRole('button', { name: '1. Evolução', exact: true }).click();
  await expect(evolution).toHaveValue(text);
  await page.getByRole('button', { name: '14. Finalização', exact: true }).click();
  await page.getByRole('button', { name: 'Finalizar Atendimento', exact: true }).last().click();
  const review = page.getByRole('dialog', { name: 'Resumo do atendimento' });
  await expect(review).toContainText(text);
  await expect(review).toContainText('Paciente teste fisio');
  await review.getByRole('button', { name: 'Voltar e editar' }).click();
  await expect(review).toHaveCount(0);
  await page.getByRole('button', { name: '1. Evolução', exact: true }).click();
  await expect(evolution).toHaveValue(text);
  await page.getByRole('button', { name: '14. Finalização', exact: true }).click();
  await page.getByRole('button', { name: 'Finalizar Atendimento', exact: true }).last().click();
  await review.getByRole('button', { name: 'Finalizar atendimento', exact: true }).click();
  await page.getByRole('button', { name: 'Confirmar e finalizar', exact: true }).click();
  await expect(page.getByText('Atendimento Finalizado com Sucesso!', { exact: true })).toBeVisible();
  const headers = await apiLogin(request, 'fisio');
  const response = await request.get('/api/v1/dashboard/metrics', { headers });
  expect(response.ok()).toBeTruthy();
  const row = (await response.json()).today.appointments.find((a: any) => a.id === 'apt-fisio');
  expect(row.status).toBe('completed');
  expect(row.record_id).toBeTruthy();
  await page.getByRole('button', { name: 'Ver prontuário do paciente' }).click();
  await expect(page.getByText(text, { exact: false }).last()).toBeVisible();
});
