import { test, expect, type Page } from '@playwright/test';
import { login, apiLogin } from '../../helpers/session';

test('Sidebar: pacientes A e B, áreas, CRUD, estoque, mapas, F5 e finalização', async ({ page, request }) => {
  test.setTimeout(240_000);
  page.setDefaultTimeout(15_000);
  page.setDefaultNavigationTimeout(60_000);
  const failures: string[] = [];
  page.on('pageerror', error => failures.push(error.message));
  page.on('response', response => { if (response.url().includes('/api/v1/estetic/') && response.status() >= 400) failures.push(`${response.status()} ${response.url()}`); });
  await login(page, 'estetic');
  const headers = await apiLogin(request, 'estetic');
  const records = async (kind: string, patient: string, area = 'FACIAL') => {
    const response = await request.get(`/api/v1/estetic/${kind}?patientId=${patient}&area=${area}`, { headers });
    expect(response.ok(), await response.text()).toBeTruthy(); return response.json();
  };
  const saved = async (kind: string, action: () => Promise<any>, method = 'POST') => {
    const pending = page.waitForResponse(response => response.url().includes(`/v1/estetic/${kind}`) && response.request().method() === method);
    await action(); const response = await pending;
    expect(response.ok(), await response.text()).toBeTruthy(); return response.json();
  };
  const area = async (name: string) => { await page.locator('[data-tour=estetic-area-selector]').click(); await page.getByRole('button', { name: `Estética ${name}`, exact: true }).click(); };
  const tab = async (name: string) => page.getByTestId('zemda-estetic-workspace').locator(`[data-tour=tab-${({ 'Planejamento': 'planning', 'Procedimentos': 'procedures', 'Fotografias': 'photos', 'Evoluções': 'evolutions', 'Retornos': 'returns', 'Avaliação Estética': 'assessment', 'Zemda360': 'zemda360', 'Antes × Depois': 'before_after', 'Histórico Completo': 'history' } as Record<string,string>)[name]}]`).click();
  const remove = async (kind: string, id: string) => {
    await page.getByTestId(`record-actions-${id}`).getByRole('button', {name:'Excluir',exact:true}).click();
    await saved(kind, () => page.getByRole('dialog', {name:'Excluir registro',exact:true}).getByRole('button', {name:'Confirmar exclusão'}).click(), 'DELETE');
    await expect(page.getByTestId(`record-actions-${id}`)).toHaveCount(0);
  };
  for (const suffix of ['A', 'B']) {
    const patient = `pat-estetic-${suffix}`;
    await page.goto('/zemda-estetic', {waitUntil:'domcontentloaded'});
    await page.getByPlaceholder('Buscar paciente para atendimento estético...').fill(`Estética paciente ${suffix}`);
    await page.getByText(`Estética paciente ${suffix}`, { exact: true }).first().click();
    await expect(page).toHaveURL(new RegExp(`/zemda-estetic/pacientes/${patient}`));
    await tab('Avaliação Estética');
    const complaint = page.getByTestId('zemda-estetic-workspace').locator('form textarea').first();
    await expect(complaint).toHaveValue('');
    await complaint.fill(`Avaliação facial ${suffix}`);
    await area('Corporal'); await expect(complaint).toHaveValue(''); await complaint.fill(`Avaliação corporal ${suffix}`);
    await area('Capilar'); await expect(complaint).toHaveValue(''); await complaint.fill(`Avaliação capilar ${suffix}`);
    await saved('assessments', () => page.getByRole('button', { name: 'Salvar Avaliação', exact: true }).click());
    await area('Facial'); await expect(complaint).toHaveValue(`Avaliação facial ${suffix}`);
    await saved('assessments', () => page.getByRole('button', { name: 'Salvar Avaliação', exact: true }).click());
    await complaint.fill(`Avaliação facial revisada ${suffix}`);
    await saved('assessments', () => page.getByRole('button', { name: 'Salvar Avaliação', exact: true }).click(), 'PUT');
    expect(await records('assessments', patient)).toHaveLength(1);
    const firstAssessment = (await records('assessments',patient))[0];
    await page.getByTestId('zemda-estetic-workspace').getByRole('button',{name:'Nova avaliação',exact:true}).last().click();
    await complaint.fill('Avaliação temporária para comparar');
    const extraAssessment = await saved('assessments', () => page.getByRole('button',{name:'Salvar Avaliação',exact:true}).click());
    await expect(page.getByRole('checkbox',{name:`Comparar avaliação ${firstAssessment.assessment_date}`,exact:true})).toHaveCount(2);
    await page.getByRole('checkbox',{name:`Comparar avaliação ${firstAssessment.assessment_date}`,exact:true}).first().check();
    await page.getByRole('checkbox',{name:`Comparar avaliação ${firstAssessment.assessment_date}`,exact:true}).last().check();
    await page.getByRole('button',{name:'Comparar avaliações selecionadas',exact:true}).click();
    await expect(page.getByRole('dialog',{name:'Comparação de avaliações',exact:true})).toContainText('Avaliação temporária para comparar');
    await page.getByRole('button',{name:'Fechar comparação',exact:true}).click();
    await remove('assessments',extraAssessment.id);

    await tab('Planejamento');
    await page.getByRole('button', {name:'Criar Novo Plano',exact:true}).click();
    let planDialog = page.getByRole('dialog', {name:'Planejamento estético',exact:true});
    await planDialog.getByLabel('Título', {exact:true}).fill(`Planejamento ${suffix}`);
    await planDialog.getByLabel('Objetivos', {exact:true}).fill('Objetivo persistido');
    await planDialog.getByPlaceholder('Ex: Toxina Botulínica', {exact:true}).fill('Procedimento planejado');
    const plan = await saved('plans', () => planDialog.locator('button[type=submit]').click());
    expect((await records('plans',patient))[0].objectives).toBe('Objetivo persistido');
    await page.getByTestId(`record-actions-${plan.id}`).getByRole('button',{name:'Editar',exact:true}).click();
    await planDialog.getByLabel('Título',{exact:true}).fill(`Planejamento revisado ${suffix}`);
    await saved('plans', () => planDialog.locator('button[type=submit]').click(), 'PUT');
    await saved('plans', () => page.getByTestId('zemda-estetic-workspace').locator('select').first().selectOption('REALIZADO'), 'PATCH');
    expect((await records('plans',patient))[0].status).toBe('CONCLUIDO');
    await remove('plans',plan.id);

    await tab('Procedimentos');
    await page.getByRole('button', { name: 'Registrar Novo Procedimento', exact: true }).click();
    let dialog = page.getByRole('dialog', { name: 'Procedimento estético', exact: true });
    await dialog.getByLabel('Procedimento', { exact: true }).fill(`Procedimento ${suffix}`);
    await dialog.getByLabel('Região anatômica').fill('Fronte');
    await dialog.getByRole('checkbox').check();
    await dialog.getByLabel('Insumo do estoque').selectOption('estetic-stock');
    await dialog.getByLabel('Quantidade aplicada').fill('2');
    await dialog.getByLabel('Data de realização').fill('2026-10-01');
    await dialog.getByLabel('Orientações pós-procedimento').fill(`Orientações ${suffix}`);
    const procedure = await saved('procedures', () => dialog.getByRole('button', { name: 'Registrar Procedimento', exact: true }).click());
    let row = (await records('procedures', patient))[0];
    expect(row).toMatchObject({ patient_id: patient, region: 'Fronte', batch_lot: 'LOTE-E2E', expiry_date: '2028-01-01', quantity: 2, date_performed: '2026-10-01', post_instructions: `Orientações ${suffix}` });
    await page.getByTestId(`record-actions-${procedure.id}`).getByRole('button', { name: 'Editar', exact: true }).click();
    await dialog.getByLabel('Quantidade aplicada').fill('3');
    await saved('procedures', () => dialog.getByRole('button', { name: 'Registrar Procedimento', exact: true }).click(), 'PUT');
    row = (await records('procedures', patient))[0]; expect(row.quantity).toBe(3);
    await page.getByRole('button',{name:'Registrar Novo Procedimento',exact:true}).click();
    await dialog.getByLabel('Procedimento',{exact:true}).fill('Procedimento temporário');
    await dialog.getByLabel('Região anatômica').fill('Fronte');
    const extraProcedure = await saved('procedures', () => dialog.getByRole('button',{name:'Registrar Procedimento',exact:true}).click());
    await remove('procedures',extraProcedure.id);
    expect(await records('procedures',patient)).toHaveLength(1);


    await tab('Fotografias');
    for (const type of ['ANTES', 'DEPOIS']) {
      await page.getByRole('button', { name: 'Anexar Nova Foto', exact: true }).click();
      dialog = page.getByRole('dialog', { name: 'Fotografia clínica', exact: true });
      await dialog.locator('input[type=file]').setInputFiles({ name: 'teste.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a5mcAAAAASUVORK5CYII=', 'base64') });
      await dialog.getByLabel('Tipo de fotografia').selectOption(type);
      await saved('photos', () => dialog.locator('button[type=submit]').click());
    }
    expect(await records('photos', patient)).toHaveLength(2);
    await tab('Antes × Depois'); await expect(page.getByText('Ângulo: FRONTAL')).toBeVisible();
    await tab('Fotografias');
    const photo = (await records('photos',patient)).find((row:any) => row.photo_type === 'DEPOIS');
    await page.getByTestId(`record-actions-${photo.id}`).getByRole('button',{name:'Editar',exact:true}).click();
    dialog = page.getByRole('dialog',{name:'Fotografia clínica',exact:true});
    await dialog.getByLabel('Observações',{exact:true}).fill('Foto revisada');
    await saved('photos', () => dialog.locator('button[type=submit]').click(), 'PUT');
    await remove('photos',photo.id);
    expect(await records('photos',patient)).toHaveLength(1);

    await tab('Zemda360');
    const map = page.getByTestId('zemda360-workspace');
    await map.getByPlaceholder('Observações sobre queixas, dor, intensidade, amplitude ou evolução clínica...').fill(`Mapa facial ${suffix}`);
    await map.locator('[data-region-id=face_malar_right]').first().click();
    await map.getByLabel('Observação da região',{exact:true}).fill(`Marcação ${suffix}`);
    await map.getByRole('button',{name:'Adicionar marcação',exact:true}).click();
    await map.getByRole('button', { name: 'Caneta', exact: true }).click();
    const surface = map.locator('.mapa-corporal-wrapper');
    await surface.scrollIntoViewIfNeeded(); const bounds = (await surface.boundingBox())!;
    await page.mouse.move(bounds.x+bounds.width*.45,bounds.y+bounds.height*.25);
    await page.mouse.down(); await page.mouse.move(bounds.x+bounds.width*.55,bounds.y+bounds.height*.30,{steps:8}); await page.mouse.up();
    await map.getByRole('button', { name: 'Borracha', exact: true }).click();
    await page.mouse.click(bounds.x+bounds.width*.50,bounds.y+bounds.height*.275);
    await tab('Evoluções'); // Switching tabs flushes pending anatomical persistence.
    await page.getByRole('button', { name: 'Nova Evolução', exact: true }).first().click();
    dialog = page.getByRole('dialog', { name: 'Evolução estética', exact: true });
    await dialog.getByLabel('Resposta biológica').fill(`Evolução ${suffix}`);
    await dialog.getByLabel('Relato do paciente').fill('Resposta informada');
    await dialog.getByLabel('Conduta', { exact: true }).fill('Acompanhar');
    const evolution = await saved('evolutions', () => dialog.locator('button[type=submit]').click());
    await page.getByTestId(`record-actions-${evolution.id}`).getByRole('button',{name:'Editar',exact:true}).click();
    await dialog.getByLabel('Conduta',{exact:true}).fill('Conduta revisada');
    await saved('evolutions', () => dialog.locator('button[type=submit]').click(), 'PUT');
    expect((await records('evolutions',patient))[0].conduct).toBe('Conduta revisada');
    await page.getByRole('button',{name:'Nova Evolução',exact:true}).click();
    await dialog.getByLabel('Resposta biológica').fill('Evolução temporária');
    const extraEvolution = await saved('evolutions', () => dialog.locator('button[type=submit]').click());
    await remove('evolutions',extraEvolution.id);
    expect(await records('evolutions',patient)).toHaveLength(1);

    await tab('Retornos');
    await page.getByRole('button', { name: 'Agendar Retorno', exact: true }).first().click();
    dialog = page.getByRole('dialog', { name: 'Retorno estético', exact: true });
    await dialog.getByLabel('Data prevista').fill('2026-11-01');
    const scheduled = await saved('returns', () => dialog.locator('button[type=submit]').click());
    expect((await records('returns', patient))[0].status).toBe('AGENDADO');
    await page.getByTestId(`record-actions-${scheduled.id}`).getByRole('button',{name:'Editar',exact:true}).click();
    await dialog.getByLabel('Avaliação do retorno',{exact:true}).fill('Retorno revisado');
    await saved('returns', () => dialog.locator('button[type=submit]').click(), 'PUT');
    await page.getByRole('button', { name: 'Confirmar Comparecimento', exact: true }).click();
    await expect.poll(async () => (await records('returns', patient))[0].status).toBe('COMPARECEU');
    await page.getByRole('button', {name:'Agendar Retorno',exact:true}).first().click();
    const cancelled = await saved('returns', () => dialog.locator('button[type=submit]').click());
    await page.getByTestId(`record-actions-${cancelled.id}`).getByRole('button',{name:'Cancelar retorno',exact:true}).click();
    await expect.poll(async () => (await records('returns',patient)).find((row:any)=>row.id === cancelled.id).status).toBe('CANCELADO');
    await remove('returns',cancelled.id);
    await page.reload();
    await expect(page.getByText(`Estética paciente ${suffix}`, { exact: true }).first()).toBeVisible();
    await tab('Procedimentos'); await expect(page.getByText(`Procedimento ${suffix}`, { exact: true })).toBeVisible();
    if (suffix === 'B') await expect(page.getByText('Procedimento A', { exact: true })).toHaveCount(0);
    await tab('Zemda360'); await expect(map.getByPlaceholder('Observações sobre queixas, dor, intensidade, amplitude ou evolução clínica...')).toHaveValue(`Mapa facial ${suffix}`);
    await expect(map.locator('[data-region-id=face_malar_right]').first()).toHaveAttribute('aria-pressed','true');
    await map.getByRole('button',{name:'Histórico',exact:true}).click();
    await page.getByRole('dialog',{name:'Histórico Zemda360',exact:true}).getByRole('button',{name:/Abrir registro/}).first().click();
    await expect(page.getByLabel('Mapa no histórico')).toBeVisible();
    await page.getByRole('button',{name:'Fechar histórico',exact:true}).click();
    await area('Capilar'); await expect(map.getByPlaceholder('Observações sobre queixas, dor, intensidade, amplitude ou evolução clínica...')).toHaveValue('');
    await area('Facial'); await expect(map.getByPlaceholder('Observações sobre queixas, dor, intensidade, amplitude ou evolução clínica...')).toHaveValue(`Mapa facial ${suffix}`);
    await page.getByRole('button', { name: 'Finalizar atendimento', exact: true }).click();
    await page.getByRole('button', { name: 'Concluir Atendimento', exact: true }).click();
    await page.getByRole('dialog', { name: 'Resumo do atendimento' }).getByRole('button', { name: 'Finalizar atendimento', exact: true }).click();
    const payment = page.getByRole('dialog', { name: 'Recebimento do atendimento' });
    await expect(payment).toBeVisible();
    await payment.getByLabel('Valor do atendimento').fill('180');
    await payment.getByLabel('Forma de pagamento').selectOption('pix');
    await payment.getByLabel('Status do recebimento').selectOption(suffix === 'A' ? 'pending' : 'paid');
    await payment.getByRole('button', { name: 'Confirmar e finalizar', exact: true }).click();
    await expect(payment).toHaveCount(0);
    await expect.poll(async () => (await records('assessments', patient, 'CORPORAL')).length).toBe(1);
    expect(await records('assessments', patient)).toHaveLength(1);
    expect(await records('procedures', patient)).toHaveLength(1);
    await page.goto(`/zemda-estetic/pacientes/${patient}`); await tab('Histórico Completo');
    await expect(page.getByText(`Procedimento ${suffix}`, { exact: true })).toBeVisible();
  }
  expect(failures).toEqual([]);
});
