import { test, expect } from '../../helpers/audit-test';
import { login, apiLogin } from '../../helpers/session';

test('Nutri: alimento manual, edição, exclusão e totais persistem junto da TACO', async ({ page, request }) => {
  await login(page, 'nutri');
  const headers = await apiLogin(request, 'nutri');
  await page.goto('/zemda-nutri');
  await page.locator('main input[placeholder*="Buscar paciente"]').fill('Paciente teste nutri');
  await page.getByText('Paciente teste nutri', { exact: true }).last().click();
  await page.locator('[data-tour=tab-meal_plans]').click();
  await expect(page.getByPlaceholder(/Buscar alimento/).first()).toBeVisible();
  await page.getByRole('button', { name: 'Adicionar alimento manual em Café da Manhã', exact: true }).click();
  const modal = page.getByRole('dialog', { name: 'Adicionar alimento manual', exact: true });
  await modal.getByLabel('Nome do alimento', { exact: true }).fill('Preparação sintética manual');
  await modal.getByLabel('Quantidade', { exact: true }).fill('100');
  await modal.getByLabel('kcal', { exact: true }).fill('200');
  await modal.getByLabel('Carboidratos (CHO) — g', { exact: true }).fill('30');
  await modal.getByLabel('Proteínas (PTN) — g', { exact: true }).fill('10');
  await modal.getByLabel('Gorduras (LIP) — g', { exact: true }).fill('4');
  await modal.getByRole('button', { name: 'Salvar alimento', exact: true }).click();
  await page.getByRole('button', { name: 'Editar Preparação sintética manual', exact: true }).click();
  const editing = page.getByRole('dialog', { name: 'Editar alimento manual', exact: true });
  await editing.getByLabel('kcal', { exact: true }).fill('220');
  await editing.getByRole('button', { name: 'Salvar alimento', exact: true }).click();
  const saved = page.waitForResponse(r => r.url().endsWith('/v1/nutrition/meal-plans') && r.request().method() === 'POST');
  await page.getByRole('button', { name: 'Salvar Plano Alimentar no Prontuário', exact: true }).click();
  expect((await saved).ok()).toBe(true);
  await page.reload();
  await page.locator('main input[placeholder*="Buscar paciente"]').fill('Paciente teste nutri');
  await page.getByText('Paciente teste nutri', { exact: true }).last().click();
  await page.locator('[data-tour=tab-meal_plans]').click();
  const plans = await request.get('/api/v1/nutrition/meal-plans/pat-nutri', { headers });
  expect(plans.ok()).toBe(true);
  const persisted = await plans.json();
  expect(JSON.stringify(persisted)).toContain('Preparação sintética manual');
  expect(persisted[0]).toMatchObject({ total_calories: 220, total_carbs: 30, total_protein: 10, total_fat: 4 });
  await expect(page.getByRole('button', { name: 'Editar Preparação sintética manual', exact: true })).toBeVisible();
  const food = page.getByText('Preparação sintética manual', { exact: true }).locator('xpath=../..');
  await food.getByTitle('Remover alimento', { exact: true }).click();
  await expect(page.getByRole('button', { name: 'Editar Preparação sintética manual', exact: true })).toHaveCount(0);
  const removed = page.waitForResponse(r => r.url().endsWith('/v1/nutrition/meal-plans') && r.request().method() === 'POST');
  await page.getByRole('button', { name: 'Salvar Plano Alimentar no Prontuário', exact: true }).click();
  expect((await removed).ok()).toBe(true);
  const afterRemoval = await request.get('/api/v1/nutrition/meal-plans/pat-nutri', { headers });
  expect(afterRemoval.ok()).toBe(true);
  expect((await afterRemoval.json())[0]).toMatchObject({ total_calories: 0, total_carbs: 0, total_protein: 0, total_fat: 0 });
});
