// Exclusive medical findings. Generic measurements remain in their shared tools.
export interface SpecialtySection { title: string; fields: [string, string][] }
const section = (title: string, fields: string): SpecialtySection => ({ title, fields: fields.split('|').map(field => {
  const [key, label] = field.split('=');
  return [key, label || key];
}) });
export const specialtyNoteKeys: Record<string, string> = {
  'clinica-medica': 'internalMedicineNotes', neurologia: 'neurologicalExam', psiquiatria: 'psychiatricNotes',
  pediatria: 'pediatricNotes', geriatria: 'geriatricNotes', endocrinologia: 'endocrinoNotes', ortopedia: 'orthoNotes',
  cardiologia: 'cardioNotes', dermatologia: 'dermatoNotes', reumatologia: 'rheumaNotes',
  'ginecologia-obstetricia': 'gynecoNotes', ginecologia: 'gynecoNotes', gastroenterologia: 'gastroNotes',
  oftalmologia: 'ophtalmoNotes', otorrinolaringologia: 'otorrinoNotes', urologia: 'uroNotes'
};
export const specialtySections: Record<string, SpecialtySection[]> = {
  'clinica-medica': [section('Revisão por sistemas', 'constitutional=Geral / constitucional|cardiovascular=Cardiovascular|respiratory=Respiratório|gastrointestinal=Gastrointestinal|genitourinary=Geniturinário|neurological=Neurológico|musculoskeletal=Musculoesquelético|dermatological=Dermatológico|endocrine=Endocrinológico'), section('Condições crônicas', 'hypertension=Hipertensão|diabetes=Diabetes|dyslipidemia=Dislipidemia|obesity=Obesidade|kidneyDisease=Doença renal|smoking=Tabagismo|otherConditions=Outras condições'), section('Acompanhamento', 'prevention=Medicina preventiva|surgicalRisk=Risco cirúrgico|investigation=Investigação diagnóstica|palliativeCare=Cuidados paliativos')],
  neurologia: [section('Estado mental', 'consciousness=Consciência|orientation=Orientação|language=Linguagem|attention=Atenção|memory=Memória'), section('Pares cranianos', 'cranialI=I — Olfatório|cranialII=II — Óptico|cranialIII=III — Oculomotor|cranialIV=IV — Troclear|cranialV=V — Trigêmeo|cranialVI=VI — Abducente|cranialVII=VII — Facial|cranialVIII=VIII — Vestibulococlear|cranialIX=IX — Glossofaríngeo|cranialX=X — Vago|cranialXI=XI — Acessório|cranialXII=XII — Hipoglosso'), section('Sistema motor', 'tone=Tônus|trophism=Trofismo|involuntaryMovements=Movimentos involuntários'), section('Reflexos', 'bicipital=Bicipital|tricipital=Tricipital|patellar=Patelar|achilles=Aquileu|plantar=Plantar'), section('Sensibilidade', 'tactile=Tátil|painSensitivity=Dolorosa|thermal=Térmica|proprioception=Proprioceptiva'), section('Coordenação e equilíbrio', 'fingerNose=Índex-nariz|heelKnee=Calcanhar-joelho|diadochokinesia=Diadococinesia|base=Base|romberg=Romberg|balanceChanges=Alterações|meningealSigns=Sinais meníngeos')],
  psiquiatria: [section('Exame do estado mental', 'appearance=Aparência|attitude=Atitude|behavior=Comportamento|consciousness=Consciência|orientation=Orientação|attention=Atenção|memory=Memória|psychomotor=Psicomotricidade|mood=Humor|affect=Afeto|thought=Pensamento|thoughtProcess=Curso do pensamento|thoughtContent=Conteúdo do pensamento|perception=Percepção|language=Linguagem|judgment=Crítica|insight=Insight'), section('Funcionamento e tratamento', 'sleep=Sono|appetite=Apetite|substances=Uso de substâncias|socialFunction=Funcionamento social|occupationalFunction=Funcionamento ocupacional|adherence=Adesão medicamentosa')],
  pediatria: [section('Nascimento', 'gestationalAge=Idade gestacional|delivery=Tipo de parto|birthWeight=Peso ao nascer (g)|birthLength=Comprimento ao nascer (cm)|birthHeadCircumference=Perímetro cefálico ao nascer (cm)|apgar=Apgar'), section('Desenvolvimento', 'motorDevelopment=Motor|languageDevelopment=Linguagem|socialDevelopment=Social|cognitiveDevelopment=Cognitivo'), section('Alimentação', 'breastfeeding=Aleitamento|foodIntroduction=Introdução alimentar|currentDiet=Dieta atual'), section('Vacinação', 'vaccinationStatus=Situação vacinal|vaccinationNotes=Observações')],
  geriatria: [section('Avaliação geriátrica ampla', 'functionality=Funcionalidade|cognition=Cognição|mood=Humor|nutrition=Nutrição|fallRisk=Risco de quedas|continence=Continência|vision=Visão|hearing=Audição|socialSupport=Suporte social'), section('Polifarmácia', 'medicationCount=Número de medicamentos|polypharmacy=Medicamentos em uso|duplicates=Duplicidades|medicationNotes=Observações')],
  endocrinologia: [section('Diabetes', 'glucose=Glicemia (mg/dL)|fastingGlucose=Glicemia de jejum (mg/dL)|hba1c=HbA1c (%)|diabetesTreatment=Tratamento|insulin=Uso de insulina|hypoglycemia=Hipoglicemias'), section('Tireoide', 'tsh=TSH|t4=T4|thyroidPalpation=Palpação|nodules=Nódulos|thyroidUltrasound=Ultrassom registrado'), section('Osteometabolismo', 'calcium=Cálcio|vitaminD=Vitamina D|densitometry=Densitometria|fractures=Fraturas')],
  ortopedia: [],
  cardiologia: [section('Sintomas', 'chestPain=Dor torácica|dyspnea=Dispneia|palpitations=Palpitações|syncope=Síncope|edema=Edema|exerciseIntolerance=Intolerância ao esforço'), section('Exame cardiovascular', 'rhythm=Ritmo|heartSounds=Bulhas|murmurs=Sopros|pulses=Pulsos|perfusion=Perfusão|examEdema=Edema ao exame'), section('Risco cardiovascular', 'smoking=Tabagismo|diabetes=Diabetes|hypertension=Hipertensão|dyslipidemia=Dislipidemia|familyRisk=Histórico familiar|cvRisk=Estratificação registrada'), section('Exames', 'ecg=ECG|echo=Ecocardiograma|mapa=MAPA|holter=Holter|stressTest=Teste ergométrico|otherTests=Outros')],
  dermatologia: [section('Pele e anexos', 'phototype=Fototipo de Fitzpatrick')],
  reumatologia: [section('Articulações', 'tenderJointCount=Articulações dolorosas|swollenJointCount=Articulações edemaciadas|jointStiffness=Rigidez|functionalLimitation=Limitação funcional'), section('Sintomas sistêmicos', 'morningStiffnessMinutes=Rigidez matinal (min)|fatigue=Fadiga|diffusePain=Dor difusa|systemicManifestations=Manifestações sistêmicas')],
  'ginecologia-obstetricia': [section('Ginecologia', 'menarche=Menarca|lmpDate=DUM|cycle=Ciclo menstrual|regularity=Regularidade|duration=Duração|flow=Fluxo|symptoms=Sintomas|contraception=Contracepção|gynecoHistory=Histórico ginecológico|sti=IST|surgeries=Cirurgias|preventiveStatus=Rastreamento preventivo'), section('Exame ginecológico', 'breastExam=Mamas|vulva=Vulva|vagina=Vagina|cervixExam=Colo|uterus=Útero|adnexa=Anexos'), section('Obstetrícia', 'gravidity=G|parity=P|abortions=A|cesareans=Cesáreas|dueDate=DPP|gestationalAge=Idade gestacional|fundalHeight=Altura uterina|fetalHeartRate=BCF|fetalMovement=Movimentos fetais|edema=Edema|complications=Intercorrências')],
  gastroenterologia: [section('Sintomas', 'abdominalPain=Dor abdominal|heartburn=Pirose|reflux=Refluxo|regurgitation=Regurgitação|nausea=Náuseas|vomiting=Vômitos|dysphagia=Disfagia|odynophagia=Odinofagia|distension=Distensão|constipation=Constipação|diarrhea=Diarreia|bleeding=Sangramento|weightLoss=Perda ponderal'), section('Hábito intestinal', 'bowelFrequency=Frequência|bristolScale=Escala de Bristol'), section('Exame abdominal', 'inspection=Inspeção|auscultation=Ausculta|percussion=Percussão|superficialPalpation=Palpação superficial|deepPalpation=Palpação profunda|organomegaly=Visceromegalias|localizedPain=Dor localizada')],
  oftalmologia: ['OD', 'OE'].flatMap(side => [section(`${side} — ${side === 'OD' ? 'olho direito' : 'olho esquerdo'}`, `visualAcuity${side}=Acuidade sem correção|correctedAcuity${side}=Acuidade com correção|nearAcuity${side}=Acuidade perto|farAcuity${side}=Acuidade longe|sphere${side}=Esfera|cylinder${side}=Cilindro|axis${side}=Eixo|addition${side}=Adição|iop${side}=Pressão intraocular (mmHg)|eyelids${side}=Pálpebras|conjunctiva${side}=Conjuntiva|cornea${side}=Córnea|anteriorChamber${side}=Câmara anterior|iris${side}=Íris|lens${side}=Cristalino|disc${side}=Papila|vessels${side}=Vasos|macula${side}=Mácula|retina${side}=Retina|motility${side}=Movimentos oculares|changes${side}=Alterações`)]).concat([section('Tonometria e exames', 'iopMethod=Método da PIO|iopTime=Horário da PIO|oct=OCT|retinography=Retinografia|visualField=Campimetria|topography=Topografia|pachymetry=Paquimetria')]),
  otorrinolaringologia: ['OD', 'OE'].map(side => section(`${side} — ouvido ${side === 'OD' ? 'direito' : 'esquerdo'}`, `otoscopy${side}=Otoscopia|tympanum${side}=Membrana timpânica|discharge${side}=Secreção|wax${side}=Cerume|pain${side}=Dor`)).concat([section('Nariz', 'septum=Septo|mucosa=Mucosa|turbinates=Cornetos|secretion=Secreção|obstruction=Obstrução'), section('Orofaringe', 'oralMucosa=Mucosa|tonsils=Amígdalas|palate=Palato|oropharynx=Alterações'), section('Laringe e voz', 'voiceComplaint=Queixa vocal|voiceNotes=Observações|voiceExams=Exames'), section('Vertigem', 'vertigoSymptoms=Sintomas|vertigoDuration=Duração|triggers=Gatilhos|associatedSymptoms=Sintomas associados')]),
  urologia: [section('Sintomas urinários', 'frequency=Frequência|urgency=Urgência|nocturia=Noctúria|dysuria=Disúria|hesitation=Hesitação|urinaryFlow=Jato|straining=Esforço|incompleteEmptying=Esvaziamento incompleto|hematuria=Hematúria|incontinence=Incontinência'), section('Próstata', 'psa=PSA|prostateExam=Exame|prostateVolume=Volume|prostateNotes=Observações'), section('Litíase', 'stoneLocation=Localização|stoneSide=Lateralidade|stoneHistory=Histórico|recurrence=Recorrência'), section('Saúde do homem', 'sexualFunction=Função sexual|andrologicalHistory=Histórico andrológico|andrologicalNotes=Observações')]
};
specialtySections.ginecologia = specialtySections['ginecologia-obstetricia'];
