// Real consent API + SQLite and production public SPA; only delivery providers and UI identity context are test doubles.
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {chromium}=require('playwright'),esbuild=require('esbuild');
const backend=path.resolve(__dirname,'../../backend');
const express=require(path.join(backend,'node_modules/express'));
const out=fs.mkdtempSync(path.join(os.tmpdir(),'zemda-consent-browser-'));
process.env.DATABASE_PATH=path.join(out,'test.sqlite');process.env.JWT_SECRET='browser-consent-test';process.env.NODE_ENV='test';
const {db,initializeDatabase}=require(path.join(backend,'dist/config/database'));initializeDatabase();
const {mountPublicConsentRoutes,mountConsentRoutes}=require(path.join(backend,'dist/routes/consents.routes'));
const {authMiddleware}=require(path.join(backend,'dist/middlewares/auth.middleware'));
const {tenantMiddleware}=require(path.join(backend,'dist/middlewares/tenant.middleware'));
const {generateToken}=require(path.join(backend,'dist/utils/jwt'));
const {EmailService}=require(path.join(backend,'dist/services/email.service'));let lastOtp='',lastRecipient='';
EmailService.sendCustomEmail=async(_to,_subject,body)=>{lastRecipient=_to;lastOtp=body.replace(/<[^>]*>/g,' ').match(/\b\d{6}\b/)?.[0]||'';return true;};
const {InfobipService}=require(path.join(backend,'dist/services/infobip.service'));InfobipService.isConfigured=()=>false;
db.prepare("INSERT INTO tenants(id,slug,name,email,status,manager_profession) VALUES('browser-clinic','browser-clinic','Clínica Browser','browser@test.invalid','active','Fisioterapia')").run();
db.prepare("INSERT INTO users(id,tenant_id,name,email,password_hash,role,status) VALUES('browser-manager','browser-clinic','Gestor','manager@test.invalid','test','clinic_admin','active')").run();
db.prepare("INSERT INTO patients(id,tenant_id,full_name,email,phone,birth_date) VALUES('browser-patient','browser-clinic','Paciente Browser','patient@test.invalid','11999999999','1990-01-01')").run();
const auth=generateToken({userId:'browser-manager',tenantId:'browser-clinic',name:'Gestor',email:'manager@test.invalid',role:'clinic_admin'});
const src=path.resolve(__dirname,'../src');
fs.writeFileSync(path.join(out,'entry.tsx'),`import React from 'react';import {createRoot} from 'react-dom/client';import {DashboardView} from ${JSON.stringify(path.join(src,'components/dashboard/DashboardView.tsx'))};import {PatientConsentsPanel} from ${JSON.stringify(path.join(src,'components/consents/PatientConsentsPanel.tsx'))};import {ConsentPendingAlert} from ${JSON.stringify(path.join(src,'components/consents/ConsentPendingAlert.tsx'))};createRoot(document.getElementById('root')!).render(location.pathname==='/test-dashboard'?<DashboardView onNavigate={()=>{}} onOpenNewAppointment={()=>{}} onOpenNewPatient={()=>{}}/>:<div className="p-4 max-w-5xl mx-auto"><ConsentPendingAlert patientId="browser-patient" onOpen={()=>{}}/><PatientConsentsPanel patientId="browser-patient" patient={{full_name:'Paciente Browser',birth_date:'1990-01-01',email:'patient@test.invalid'}}/></div>);`);
const fixtureBuild=esbuild.build({entryPoints:[path.join(out,'entry.tsx')],bundle:true,platform:'browser',format:'iife',outfile:path.join(out,'fixture.js'),jsx:'automatic',define:{'import.meta.env':'{}'},nodePaths:[path.resolve(__dirname,'../node_modules')],plugins:[{name:'identity-fixtures',setup(build){build.onResolve({filter:/context\/(AuthContext|ToastContext)$/},args=>({path:args.path,namespace:'identity'}));build.onLoad({filter:/.*/,namespace:'identity'},args=>({contents:args.path.endsWith('AuthContext')?"export const useAuth=()=>({currentUser:{role:new URLSearchParams(location.search).get('role')||'clinic_admin'}});":"export const useToast=()=>({showToast:()=>{}});",loader:'js'}));}}]});
const dist=path.resolve(__dirname,'../dist'),css=fs.readdirSync(path.join(dist,'assets')).find(n=>/^index-.*\.css$/.test(n));
const app=express();app.use(express.json({limit:'8mb'}));
const api=express.Router();mountPublicConsentRoutes(api);api.use(authMiddleware,tenantMiddleware);mountConsentRoutes(api);
api.get('/v1/dashboard/metrics',(_req,res)=>res.json({today:{total:1,appointments:[{id:'today-test',patient_id:'browser-patient',patient_name:'Paciente Browser',patient_phone:'11999999999',status:'confirmed',start_time:'2026-10-04T10:00:00',end_time:'2026-10-04T11:00:00'}]}}));
api.get('/v1/patients/:id', (req,res)=>res.json({patient:db.prepare('SELECT * FROM patients WHERE id=?').get(req.params.id),guardians:[]}));
api.get('/v1/services',(req,res)=>res.json(require(path.join(backend,'dist/services/consent.service')).ConsentService.compatibleServices(req,String(req.query.consentModule||'general'))));app.use('/api',api);
app.get(['/test-panel','/test-dashboard'],(_req,res)=>res.send(`<html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/assets/${css}"><link rel="stylesheet" href="/fixture/fixture.css"><div id="root"></div><script src="/fixture/fixture.js"></script></html>`));
app.use('/fixture',express.static(out));app.use(express.static(dist));app.get(['/assinar-termo/:token','/verificar/:code'],(_req,res)=>res.sendFile(path.join(dist,'index.html')));
const server=app.listen(0,'127.0.0.1');
let checks=0;
(async()=>{
 await fixtureBuild;
 if(!server.listening) await new Promise(r=>server.once('listening',r));const base=`http://127.0.0.1:${server.address().port}`;process.env.APP_URL=base;
 const browser=await chromium.launch({headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});
 try {
  const context=await browser.newContext({viewport:{width:1280,height:900}}),page=await context.newPage(),errors=[],outbound=[];
  page.on('pageerror',e=>errors.push(e.message));
  await context.route('**/*',route=>{const url=route.request().url();if(url.startsWith(base)||url.startsWith('data:'))route.continue();else{outbound.push(url);route.abort();}});
  await context.addInitScript(({auth})=>{localStorage.setItem('auth_token',auth);localStorage.setItem('active_tenant_id','browser-clinic');},{auth});
  await page.goto(base+'/test-panel');await page.getByRole('heading',{name:'Termos & Consentimentos'}).waitFor();
  if(process.env.CONSENT_SERVICES_ONLY==='1') {
    db.prepare("UPDATE users SET profession_id='prof-fisioterapeuta' WHERE id='browser-manager'").run();
    for(const [id,module] of [['fisio-shared','ZemdaFisio'],['med-shared','ZemdaMed'],['psico-shared','ZemdaPsico']]) db.prepare('INSERT INTO services(id,tenant_id,name,clinical_module) VALUES(?,?,?,?)').run(id,'browser-clinic',id,module);
    await page.reload();await page.getByRole('button',{name:'Biblioteca de termos',exact:true}).click();
    await page.getByRole('button',{name:'Criar termo próprio',exact:true}).click();
    const services=page.getByLabel('Serviço relacionado',{exact:true}),area=page.getByLabel('Área / módulo',{exact:true});
    await services.locator('option[value="fisio-shared"]').waitFor({state:'attached'});
    assert.equal(await services.locator('option').count(),2);
    await services.selectOption('fisio-shared');await area.fill('ZemdaMed');assert.equal(await services.inputValue(),'');assert.equal(await services.locator('option').count(),1);
    await area.fill('ZemdaFisio');assert.equal(await services.locator('option').count(),2);
    await services.selectOption('fisio-shared');await page.getByLabel('Título',{exact:true}).fill('Termo com serviço compatível');await page.getByLabel('Conteúdo completo').fill('Consentimento informado para o serviço compatível selecionado.');
    await page.getByRole('button',{name:'Salvar modelo',exact:true}).click();await page.getByRole('heading',{name:'Termo com serviço compatível',exact:true}).waitFor();
    assert.equal(db.prepare("SELECT t.service_id FROM consent_templates t JOIN consent_template_versions v ON v.template_id=t.id WHERE v.title='Termo com serviço compatível'").get().service_id,'fisio-shared');
    assert.deepEqual(errors,[]);console.log('PASS consent service catalog scoped by server, immediate area filtering/reset, compatible save');return;
  }
  if(process.env.CONSENT_LIBRARY_ONLY==='1') {
    await page.getByRole('button',{name:'Biblioteca de termos',exact:true}).click();
    const cardFor=title=>page.locator('article').filter({has:page.getByRole('heading',{name:title,exact:true})});
    const save=async()=>{await page.getByRole('button',{name:'Salvar modelo',exact:true}).click();await page.getByRole('form',{name:'Editor de termo'}).waitFor({state:'detached'});};
    const standard=db.prepare("SELECT * FROM consent_templates WHERE id='consent-standard-general'").get();
    const original=db.prepare('SELECT * FROM consent_template_versions WHERE template_id=?').all(standard.id);
    const globalCard=cardFor(original[0].title);
    assert.equal(await globalCard.getByRole('button',{name:'Editar',exact:true}).count(),0);
    await globalCard.getByRole('button',{name:'Personalizar',exact:true}).click();
    assert.equal(await page.getByLabel('Conteúdo completo').inputValue(),original[0].content);
    await page.getByLabel('Título',{exact:true}).fill('Modelo personalizado da biblioteca');
    await save();
    const customCard=cardFor('Modelo personalizado da biblioteca');await customCard.waitFor();
    const custom=db.prepare("SELECT template_id FROM consent_template_versions WHERE title='Modelo personalizado da biblioteca'").get().template_id;
    assert.notEqual(custom,standard.id);
    assert.deepEqual(db.prepare('SELECT * FROM consent_templates WHERE id=?').get(standard.id),standard);
    assert.deepEqual(db.prepare('SELECT * FROM consent_template_versions WHERE template_id=?').all(standard.id),original);
    const firstVersion=db.prepare('SELECT * FROM consent_template_versions WHERE template_id=?').get(custom);
    await customCard.getByRole('button',{name:'Editar',exact:true}).click();
    await page.getByLabel('Conteúdo completo').fill('Conteúdo atualizado da biblioteca em uma nova versão imutável.');
    await save();
    await customCard.getByText(/v2/).waitFor();
    assert.equal(db.prepare('SELECT current_version FROM consent_templates WHERE id=?').get(custom).current_version,2);
    assert.deepEqual(db.prepare('SELECT * FROM consent_template_versions WHERE id=?').get(firstVersion.id),firstVersion);
    for(const title of [original[0].title,'Modelo personalizado da biblioteca']) {
      await cardFor(title).getByRole('button',{name:'Duplicar',exact:true}).click();
      assert.equal(await page.getByLabel('Título',{exact:true}).inputValue(),'Cópia de '+title);
      await save();await cardFor('Cópia de '+title).getByRole('button',{name:'Editar',exact:true}).waitFor();
    }
    await page.getByLabel('Filtrar módulo').selectOption('ZemdaFisio');
    await page.getByRole('button',{name:'Criar termo próprio',exact:true}).click();
    await page.getByLabel('Título',{exact:true}).fill('Termo próprio na biblioteca');
    await page.getByLabel('Conteúdo completo').fill('Informações completas do termo criado diretamente na biblioteca.');
    await page.getByLabel('Procedimento relacionado').fill('Procedimento opcional');
    await page.getByLabel('Termo obrigatório nesta área/serviço').check();
    await save();await cardFor('Termo próprio na biblioteca').waitFor();
    assert.equal(await page.getByLabel('Filtrar módulo').inputValue(),'general');
    await page.setViewportSize({width:390,height:844});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await page.screenshot({path:path.join(out,'library-mobile.png'),fullPage:true});
    await page.goto(base+'/test-panel?role=receptionist');
    await page.getByRole('button',{name:'Biblioteca de termos',exact:true}).click();
    assert.equal(await page.getByRole('button',{name:/^(Criar termo próprio|Editar|Personalizar|Duplicar)$/}).count(),0);
    await cardFor('Termo próprio na biblioteca').getByRole('button',{name:'Usar modelo',exact:true}).click();
    assert.ok(await page.getByLabel('Modelo',{exact:true}).inputValue());
    assert.deepEqual(errors,[]);
    console.log('PASS library personalize global, edit/version clinic, duplicate both, create/filter refresh, mobile and reception read/request permissions. Screenshots: '+out);
    return;
  }
  if(process.env.CONSENT_EDITOR_ONLY==='1') {
    const sentBefore=db.prepare('SELECT * FROM patient_consents').all();
    await page.getByRole('button',{name:'Solicitar assinatura',exact:true}).click();
    await page.getByLabel('Solicitar foto no momento da assinatura',{exact:true}).check();
    await page.getByRole('button',{name:'+ Criar termo próprio',exact:true}).click();
    assert.ok(await page.getByRole('button',{name:'Assinar agora',exact:true}).isDisabled());
    await page.getByLabel('Título',{exact:true}).fill('Termo criado na solicitação');
    await page.getByLabel('Conteúdo completo').fill('Conteúdo personalizado para revisão e assinatura do paciente.');
    await page.getByLabel('Procedimento relacionado').fill('Atendimento remoto');
    await page.getByRole('button',{name:'Salvar e utilizar',exact:true}).click();
    await page.getByRole('form',{name:'Editor de termo'}).waitFor({state:'detached'});
    const created=await page.getByLabel('Modelo',{exact:true}).inputValue();
    assert.ok(created);
    assert.match(await page.getByLabel('Modelo',{exact:true}).locator('option:checked').innerText(),/Termo criado na solicitação.*v1/);
    assert.ok(await page.getByLabel('Solicitar foto no momento da assinatura',{exact:true}).isChecked());
    assert.deepEqual(db.prepare('SELECT * FROM patient_consents').all(),sentBefore,'saving a template does not issue a document');
    await page.getByText('Ler conteúdo antes de enviar',{exact:true}).click();
    await page.getByText('Conteúdo personalizado para revisão e assinatura do paciente.',{exact:true}).waitFor();
    const standard=db.prepare("SELECT * FROM consent_templates WHERE id='consent-standard-general'").get();
    const standardVersions=db.prepare('SELECT * FROM consent_template_versions WHERE template_id=?').all(standard.id);
    await page.getByLabel('Modelo',{exact:true}).selectOption(standard.id);
    await page.getByRole('button',{name:'✏️ Editar / Adaptar termo',exact:true}).click();
    await page.getByLabel('Título',{exact:true}).fill('Cópia personalizada na solicitação');
    await page.getByLabel('Conteúdo completo').fill('Texto adaptado da clínica para consentimento do atendimento.');
    await page.getByRole('button',{name:'Salvar e utilizar',exact:true}).click();
    await page.getByRole('form',{name:'Editor de termo'}).waitFor({state:'detached'});
    const custom=await page.getByLabel('Modelo',{exact:true}).inputValue();
    assert.notEqual(custom,standard.id);
    assert.deepEqual(db.prepare('SELECT * FROM consent_templates WHERE id=?').get(standard.id),standard);
    assert.deepEqual(db.prepare('SELECT * FROM consent_template_versions WHERE template_id=?').all(standard.id),standardVersions);
    await page.getByText('Texto adaptado da clínica para consentimento do atendimento.',{exact:true}).waitFor();
    const originalVersion=db.prepare('SELECT * FROM consent_template_versions WHERE template_id=?').get(custom);
    const headers={Authorization:`Bearer ${auth}`,'Content-Type':'application/json'};
    const pending=await(await fetch(base+'/api/v1/consents/patients/browser-patient/request',{method:'POST',headers,body:JSON.stringify({templateId:custom})})).json();
    const snapshot=db.prepare('SELECT * FROM patient_consents WHERE id=?').get(pending.id);
    assert.ok(snapshot);
    await page.getByRole('button',{name:'✏️ Editar / Adaptar termo',exact:true}).click();
    await page.getByLabel('Conteúdo completo').fill('Nova versão da clínica com informações adaptadas antes do envio.');
    await page.getByRole('button',{name:'Salvar e utilizar',exact:true}).click();
    await page.getByRole('form',{name:'Editor de termo'}).waitFor({state:'detached'});
    assert.equal(await page.getByLabel('Modelo',{exact:true}).inputValue(),custom);
    assert.match(await page.getByLabel('Modelo',{exact:true}).locator('option:checked').innerText(),/v2/);
    await page.getByText('Nova versão da clínica com informações adaptadas antes do envio.',{exact:true}).waitFor();
    assert.deepEqual(db.prepare('SELECT * FROM patient_consents WHERE id=?').get(pending.id),snapshot,'pending document snapshot and hash unchanged');
    assert.deepEqual(db.prepare('SELECT * FROM consent_template_versions WHERE id=?').get(originalVersion.id),originalVersion,'old version immutable');
    await page.screenshot({path:path.join(out,'inline-template-desktop.png'),fullPage:true});
    await page.setViewportSize({width:390,height:844});
    await page.getByRole('button',{name:'✏️ Editar / Adaptar termo',exact:true}).click();
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await page.screenshot({path:path.join(out,'inline-template-mobile.png'),fullPage:true});
    await page.getByRole('form',{name:'Editor de termo'}).getByRole('button',{name:'Voltar',exact:true}).click();
    assert.equal(await page.getByLabel('Modelo',{exact:true}).inputValue(),custom);
    await page.goto(base+'/test-panel?role=receptionist');
    await page.getByRole('button',{name:'Solicitar assinatura',exact:true}).click();
    assert.equal(await page.getByRole('button',{name:'+ Criar termo próprio',exact:true}).count(),0);
    await page.getByLabel('Modelo',{exact:true}).selectOption(custom);
    await page.getByText('Ler conteúdo antes de enviar',{exact:true}).click();
    assert.equal(await page.getByRole('button',{name:'✏️ Editar / Adaptar termo',exact:true}).count(),0);
    assert.deepEqual(errors,[]);
    console.log('PASS inline create/select, global copy, clinic versioning, preserved request state, pending snapshots/hashes, cancellation, reception UI and mobile. Screenshots: '+out);
    return;
  }
  await page.getByRole('button',{name:'Biblioteca de termos',exact:true}).click();
  await page.getByText('Configuração da clínica',{exact:true}).click();
  await page.getByLabel('Nível de confirmação').selectOption('basic');await page.getByRole('button',{name:'Salvar configuração'}).click();
  await page.getByRole('button',{name:'Criar termo próprio'}).click();
  await page.getByLabel('Título',{exact:true}).fill('Termo Browser universal');
  await page.getByLabel('Conteúdo completo').fill('Recebi informações claras sobre o atendimento. Tive oportunidade de tirar dúvidas. Concordo com o atendimento proposto para este teste.');
  await page.getByLabel('Termo obrigatório nesta área/serviço').check();await page.getByRole('button',{name:'Salvar modelo',exact:true}).click();
  await page.getByRole('heading',{name:'Termo Browser universal',exact:true}).waitFor();checks++;
  await page.getByText('⚠ Paciente possui termo obrigatório pendente.',{exact:false}).waitFor();checks++;
  const card=page.getByRole('heading',{name:'Termo Browser universal',exact:true}).locator('..');await card.getByRole('button',{name:'Usar modelo'}).click();
  await page.getByRole('button',{name:'QR Code',exact:true}).click();
  const open=page.getByRole('link',{name:'Assinar neste dispositivo'});await open.waitFor();const link=await open.getAttribute('href');
  await page.getByText('Mostrar QR Code',{exact:true}).waitFor();
  assert.equal(await page.getByRole('img',{name:'QR Code para assinar este termo'}).count(),1);checks++;
  const signaturePage=await context.newPage();signaturePage.on('pageerror',e=>errors.push(e.message));await signaturePage.goto(link);
  await signaturePage.getByRole('heading',{name:'Termo Browser universal'}).waitFor();assert.equal(await signaturePage.getByRole('button',{name:'Tirar foto'}).count(),0);checks++;
  for(const checkbox of await signaturePage.getByRole('checkbox').all())await checkbox.check();
  const canvas=signaturePage.locator('canvas'),box=await canvas.boundingBox();
  await signaturePage.mouse.move(box.x+30,box.y+90);await signaturePage.mouse.down();for(let i=0;i<25;i++)await signaturePage.mouse.move(box.x+30+i*12,box.y+90+Math.sin(i)*25);await signaturePage.mouse.up();
  await signaturePage.screenshot({path:path.join(out,'public-desktop.png'),fullPage:true});
  await signaturePage.getByRole('button',{name:'Confirmar assinatura'}).click();await signaturePage.getByRole('heading',{name:'Termo assinado com sucesso'}).waitFor();checks++;
  const verification=await signaturePage.getByRole('link',{name:'Verificar autenticidade'}).getAttribute('href');await signaturePage.goto(verification);await signaturePage.getByRole('heading',{name:'Documento autêntico'}).waitFor();
  assert.ok(!(await signaturePage.locator('body').innerText()).includes('Paciente Browser'));checks++;
  await page.getByRole('button',{name:'Atualizar',exact:true}).click();await page.getByRole('button',{name:'Termos do paciente',exact:true}).click();await page.getByText('✓ Assinado',{exact:true}).waitFor();checks++;
  const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'PDF / imprimir'}).click();const download=await downloadPromise;await download.saveAs(path.join(out,'browser-signed.pdf'));assert.ok(fs.statSync(path.join(out,'browser-signed.pdf')).size>3000);checks++;
  await page.getByRole('button',{name:'Biblioteca de termos',exact:true}).click();await card.getByRole('button',{name:'Editar',exact:true}).click();await page.getByLabel('Conteúdo completo').fill('Versão dois do termo, com novas informações que devem solicitar nova assinatura sem alterar a versão assinada.');await page.getByRole('button',{name:'Salvar modelo',exact:true}).click();await page.getByRole('button',{name:'Termos do paciente',exact:true}).click();await page.getByText('⚠ Nova assinatura necessária',{exact:true}).waitFor();checks++;
  // Recommended OTP on a new request and mobile layout.
  await page.getByRole('button',{name:'Biblioteca de termos',exact:true}).click();await page.getByText('Configuração da clínica',{exact:true}).click();await page.getByLabel('Nível de confirmação').selectOption('recommended');await page.getByRole('button',{name:'Salvar configuração'}).click();
  await card.getByRole('button',{name:'Usar modelo'}).click();await page.getByRole('button',{name:'QR Code',exact:true}).click();await open.waitFor();const mobileLink=await open.getAttribute('href');
  const mobile=await context.newPage();await mobile.setViewportSize({width:375,height:812});await mobile.goto(mobileLink);await mobile.getByRole('heading',{name:'Termo Browser universal'}).waitFor();
  assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));checks++;
  const otpResponse=mobile.waitForResponse(r=>r.url().includes('/otp/request'));await mobile.getByRole('button',{name:'Enviar código',exact:true}).click();await otpResponse;await mobile.getByLabel('Código de 6 dígitos').fill(lastOtp);await mobile.getByRole('button',{name:'Validar código'}).click();await mobile.getByText('✓ Código confirmado.',{exact:false}).waitFor();checks++;
  for(const checkbox of await mobile.getByRole('checkbox').all())await checkbox.check();
  const mb=await mobile.locator('canvas').boundingBox();await mobile.locator('canvas').scrollIntoViewIfNeeded();const b=await mobile.locator('canvas').boundingBox();const touch=await context.newCDPSession(mobile);await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:b.x+20,y:b.y+80}]});for(let i=0;i<22;i++)await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:b.x+20+i*10,y:b.y+80+Math.sin(i)*20}]});await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await touch.detach();
  await mobile.screenshot({path:path.join(out,'public-mobile.png'),fullPage:true});await mobile.getByRole('button',{name:'Confirmar assinatura'}).click();await mobile.getByRole('heading',{name:'Termo assinado com sucesso'}).waitFor();checks++;
  await mobile.goto(mobileLink);await mobile.getByText('Link expirado, cancelado ou já utilizado.').waitFor();checks++;
  await page.getByRole('button',{name:'Atualizar',exact:true}).click();
  await page.waitForFunction(()=>!document.body.textContent.includes('⚠ Nova assinatura necessária'));
  assert.equal(await page.getByText('⚠ Nova assinatura necessária',{exact:true}).count(),0);checks++;
  await page.getByRole('button',{name:'Solicitar assinatura',exact:true}).click();
  const selected=db.prepare("SELECT template_id FROM consent_template_versions WHERE title='Termo Browser universal' ORDER BY version DESC LIMIT 1").get().template_id;
  await page.getByLabel('Modelo',{exact:true}).selectOption(selected);
  await page.getByLabel('Solicitar foto no momento da assinatura',{exact:true}).check();
  await page.getByRole('button',{name:'Assinar agora',exact:true}).click();
  await page.getByRole('dialog',{name:'Assinar termo'}).getByRole('heading',{name:'Termo Browser universal'}).waitFor();
  const inline=page.getByRole('dialog',{name:'Assinar termo',exact:true});await inline.getByRole('button',{name:'Tirar foto'}).click();await page.waitForFunction(()=>document.querySelector('video')?.videoWidth>0);await inline.getByRole('button',{name:'Capturar foto'}).click();await inline.getByRole('button',{name:'Confirmar foto'}).click();await inline.getByText('Foto confirmada.',{exact:true}).waitFor();checks++;
  await page.getByRole('button',{name:'Voltar aos termos'}).click();checks++;
  const headers={Authorization:`Bearer ${auth}`,'Content-Type':'application/json'};
  await fetch(base+'/api/v1/consents/settings',{method:'PUT',headers,body:JSON.stringify({authLevel:'basic',linkHours:1,photoRequested:true})});
  const photoRequest=await (await fetch(base+'/api/v1/consents/patients/browser-patient/request',{method:'POST',headers,body:JSON.stringify({templateId:selected})})).json();
  const photoPage=await context.newPage();await photoPage.goto(photoRequest.url);

  await photoPage.getByRole('button',{name:'Tirar foto'}).click();
  await photoPage.waitForFunction(()=>document.querySelector('video')?.videoWidth>0);
  await photoPage.getByRole('button',{name:'Capturar foto'}).click();
  await photoPage.getByRole('button',{name:'Refazer foto'}).click();
  await photoPage.waitForFunction(()=>document.querySelector('video')?.videoWidth>0);
  await photoPage.getByRole('button',{name:'Capturar foto'}).click();
  await photoPage.getByRole('button',{name:'Confirmar foto'}).click();
  await photoPage.getByText('Foto confirmada.',{exact:true}).waitFor();checks++;
  assert.equal(await photoPage.getByRole('heading',{name:'Confirme sua identidade'}).count(),0);checks++;
  for(const checkbox of await photoPage.getByRole('checkbox').all())await checkbox.check();
  await photoPage.locator('canvas').scrollIntoViewIfNeeded();const penBox=await photoPage.locator('canvas').boundingBox(),pen=await context.newCDPSession(photoPage);
  await pen.send('Input.dispatchMouseEvent',{type:'mousePressed',x:penBox.x+20,y:penBox.y+80,button:'left',buttons:1,clickCount:1,pointerType:'pen'});
  for(let i=0;i<22;i++)await pen.send('Input.dispatchMouseEvent',{type:'mouseMoved',x:penBox.x+20+i*10,y:penBox.y+80+Math.sin(i)*20,buttons:1,pointerType:'pen'});
  await pen.send('Input.dispatchMouseEvent',{type:'mouseReleased',x:penBox.x+230,y:penBox.y+80,button:'left',buttons:0,clickCount:1,pointerType:'pen'});await pen.detach();
  await photoPage.getByRole('button',{name:'Remover foto'}).click();assert.equal(await photoPage.getByRole('button',{name:'Confirmar assinatura'}).isDisabled(),true);checks++;
  await photoPage.getByRole('button',{name:'Tirar foto'}).click();await photoPage.waitForFunction(()=>document.querySelector('video')?.videoWidth>0);await photoPage.getByRole('button',{name:'Capturar foto'}).click();assert.equal(await photoPage.getByRole('button',{name:'Confirmar assinatura'}).isDisabled(),true);checks++;await photoPage.getByRole('button',{name:'Confirmar foto'}).click();
  await photoPage.getByRole('button',{name:'Confirmar assinatura'}).click();await photoPage.getByRole('heading',{name:'Termo assinado com sucesso'}).waitFor();checks++;
  assert.ok(db.prepare('SELECT photo_data_url FROM consent_signatures WHERE consent_id=?').get(photoRequest.id).photo_data_url);checks++;
  const cameraPdf=await fetch(base+'/api/v1/consents/'+photoRequest.id+'/pdf',{headers});assert.equal(cameraPdf.status,200);fs.writeFileSync(path.join(out,'camera-signed.pdf'),Buffer.from(await cameraPdf.arrayBuffer()));checks++;
  const panelMobile=await context.newPage();await panelMobile.setViewportSize({width:375,height:812});await panelMobile.goto(base+'/test-panel');await panelMobile.getByRole('heading',{name:'Termos & Consentimentos'}).waitFor();assert.ok(await panelMobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await panelMobile.screenshot({path:path.join(out,'panel-mobile.png'),fullPage:true});checks++;
  db.prepare("UPDATE users SET profession_id='prof-esteticista' WHERE id='browser-manager'").run();
  const dash=await context.newPage();await dash.goto(base+'/test-dashboard');await dash.getByRole('button',{name:'Termos',exact:true}).click();
  const dialog=dash.getByRole('dialog',{name:'Termos & Consentimentos',exact:true});await dialog.getByRole('heading',{name:'Termos & Consentimentos'}).first().waitFor();
  await dialog.getByRole('button',{name:'Solicitar assinatura',exact:true}).click();
  const choices=await dialog.getByLabel('Modelo',{exact:true}).innerText();assert.ok(choices.includes('ZemdaEstetic')&&!choices.includes('ZemdaFisio'));checks++;
  await dialog.getByLabel('Modelo',{exact:true}).selectOption('consent-standard-ZemdaEstetic');
  await dialog.getByLabel('Solicitar foto no momento da assinatura',{exact:true}).check();
  await dialog.locator('form').getByRole('button',{name:'QR Code',exact:true}).click();
  const cancelLink=await dialog.getByRole('link',{name:'Assinar neste dispositivo'}).getAttribute('href');
  const cameraMobile=await context.newPage();await cameraMobile.setViewportSize({width:375,height:812});await cameraMobile.goto(cancelLink);await cameraMobile.getByRole('button',{name:'Tirar foto'}).click();await cameraMobile.waitForFunction(()=>document.querySelector('video')?.videoWidth>0);await cameraMobile.getByRole('button',{name:'Capturar foto'}).click();await cameraMobile.getByRole('button',{name:'Confirmar foto'}).click();await cameraMobile.getByText('Foto confirmada.',{exact:true}).waitFor();checks++;
  const pendingCard=dialog.locator('article').filter({has:dash.getByRole('heading',{name:'Consentimento para atendimento — ZemdaEstetic',exact:true})});
  await pendingCard.getByRole('button',{name:'Cancelar / invalidar'}).click();assert.equal(await pendingCard.getByRole('button',{name:'Confirmar cancelamento'}).isDisabled(),true);await pendingCard.getByLabel('Motivo *',{exact:false}).fill('Cancelado para teste da agenda');await pendingCard.getByRole('button',{name:'Confirmar cancelamento'}).click();await pendingCard.getByText('✕ Cancelado',{exact:true}).waitFor();checks++;
  await cameraMobile.goto(cancelLink);await cameraMobile.getByText('Link expirado, cancelado ou já utilizado.').waitFor();checks++;
  assert.equal(await dialog.getByRole('option',{name:/WhatsApp/}).count(),0);checks++;
  await dialog.getByRole('button',{name:'Solicitar assinatura',exact:true}).click();await dialog.getByLabel('Modelo',{exact:true}).selectOption('consent-standard-ZemdaEstetic');
  const sentResponse=dash.waitForResponse(r=>r.url().endsWith('/send'));await dialog.locator('form').getByRole('button',{name:'Enviar por e-mail',exact:true}).click();await sentResponse;assert.equal(lastRecipient,'patient@test.invalid');checks++;
  await context.grantPermissions(['clipboard-read','clipboard-write'],{origin:base});await dialog.locator('aside').getByRole('button',{name:'Copiar link',exact:true}).click();assert.equal(await dash.evaluate(()=>navigator.clipboard.readText()),await dialog.getByRole('link',{name:'Assinar neste dispositivo'}).getAttribute('href'));checks++;
  const signedPhotoCard=dialog.locator('article').filter({has:dash.getByRole('heading',{name:'Termo Browser universal',exact:true})}).filter({has:dash.getByRole('button',{name:'Ver evidências',exact:true})}).first();await signedPhotoCard.getByRole('button',{name:'Ver evidências',exact:true}).click();await dialog.getByRole('img',{name:'Foto da assinatura',exact:true}).waitFor();checks++;
  assert.deepEqual(errors,[]);assert.ok(!outbound.some(url=>/google.*(analytics|tagmanager)|facebook|fbevents/i.test(url)));checks++;
  console.log(JSON.stringify({checks,screenshots:out,pdf:path.join(out,'browser-signed.pdf'),analytics:'No trackers requested on public signing pages',externalMessages:'none'}));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>server.close());
