// Real consent API + SQLite and production public SPA; only delivery providers and UI identity context are test doubles.
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {chromium}=require('playwright'),esbuild=require('esbuild');
const backend=path.resolve(__dirname,'../../backend');
const express=require(path.join(backend,'node_modules/express'));
const out=fs.mkdtempSync(path.join(os.tmpdir(),'zemda-consent-browser-'));
process.env.DATABASE_PATH=path.join(out,'test.sqlite');process.env.JWT_SECRET='browser-consent-test';process.env.NODE_ENV='test';
const {db,initializeDatabase}=require(path.join(backend,'dist/config/database'));initializeDatabase();
const {mountPublicConsentRoutes,mountConsentRoutes}=require(path.join(backend,'dist/routes/consents.routes'));
const {authMiddleware}=require(path.join(backend,'dist/middlewares/auth.middleware'));
const {tenantMiddleware}=require(path.join(backend,'dist/middlewares/tenant.middleware'));
const {generateToken}=require(path.join(backend,'dist/utils/jwt'));
const {EmailService}=require(path.join(backend,'dist/services/email.service'));let lastOtp='';
EmailService.sendCustomEmail=async(_to,_subject,body)=>{lastOtp=body.match(/\b\d{6}\b/)?.[0]||'';return true;};
const {InfobipService}=require(path.join(backend,'dist/services/infobip.service'));InfobipService.isConfigured=()=>false;
db.prepare("INSERT INTO tenants(id,slug,name,email,status,manager_profession) VALUES('browser-clinic','browser-clinic','Clínica Browser','browser@test.invalid','active','Fisioterapia')").run();
db.prepare("INSERT INTO users(id,tenant_id,name,email,password_hash,role,status) VALUES('browser-manager','browser-clinic','Gestor','manager@test.invalid','test','clinic_admin','active')").run();
db.prepare("INSERT INTO patients(id,tenant_id,full_name,email,phone,birth_date) VALUES('browser-patient','browser-clinic','Paciente Browser','patient@test.invalid','11999999999','1990-01-01')").run();
const auth=generateToken({userId:'browser-manager',tenantId:'browser-clinic',name:'Gestor',email:'manager@test.invalid',role:'clinic_admin'});
const src=path.resolve(__dirname,'../src');
fs.writeFileSync(path.join(out,'entry.tsx'),`import React from 'react';import {createRoot} from 'react-dom/client';import {PatientConsentsPanel} from ${JSON.stringify(path.join(src,'components/consents/PatientConsentsPanel.tsx'))};import {ConsentPendingAlert} from ${JSON.stringify(path.join(src,'components/consents/ConsentPendingAlert.tsx'))};createRoot(document.getElementById('root')!).render(<div className="p-4 max-w-5xl mx-auto"><ConsentPendingAlert patientId="browser-patient" onOpen={()=>{}}/><PatientConsentsPanel patientId="browser-patient" patient={{full_name:'Paciente Browser',birth_date:'1990-01-01'}}/></div>);`);
const fixtureBuild=esbuild.build({entryPoints:[path.join(out,'entry.tsx')],bundle:true,platform:'browser',format:'iife',outfile:path.join(out,'fixture.js'),jsx:'automatic',define:{'import.meta.env':'{}'},nodePaths:[path.resolve(__dirname,'../node_modules')],plugins:[{name:'identity-fixtures',setup(build){build.onResolve({filter:/context\/(AuthContext|ToastContext)$/},args=>({path:args.path,namespace:'identity'}));build.onLoad({filter:/.*/,namespace:'identity'},args=>({contents:args.path.endsWith('AuthContext')?"export const useAuth=()=>({currentUser:{role:'clinic_admin'}});":"export const useToast=()=>({showToast:()=>{}});",loader:'js'}));}}]});
const dist=path.resolve(__dirname,'../dist'),css=fs.readdirSync(path.join(dist,'assets')).find(n=>/^index-.*\.css$/.test(n));
const app=express();app.use(express.json({limit:'8mb'}));
const api=express.Router();mountPublicConsentRoutes(api);api.use(authMiddleware,tenantMiddleware);mountConsentRoutes(api);
api.get('/v1/services',(_req,res)=>res.json([]));app.use('/api',api);
app.get('/test-panel',(_req,res)=>res.send(`<html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/assets/${css}"><link rel="stylesheet" href="/fixture/fixture.css"><div id="root"></div><script src="/fixture/fixture.js"></script></html>`));
app.use('/fixture',express.static(out));app.use(express.static(dist));app.get(['/assinar-termo/:token','/verificar/:code'],(_req,res)=>res.sendFile(path.join(dist,'index.html')));
const server=app.listen(0,'127.0.0.1');
let checks=0;
(async()=>{
 await fixtureBuild;
 if(!server.listening) await new Promise(r=>server.once('listening',r));const base=`http://127.0.0.1:${server.address().port}`;process.env.APP_URL=base;
 const browser=await chromium.launch({headless:true});
 try {
  const context=await browser.newContext({viewport:{width:1280,height:900}}),page=await context.newPage(),errors=[],outbound=[];
  page.on('pageerror',e=>errors.push(e.message));
  await context.route('**/*',route=>{const url=route.request().url();if(url.startsWith(base)||url.startsWith('data:'))route.continue();else{outbound.push(url);route.abort();}});
  await context.addInitScript(({auth})=>{localStorage.setItem('auth_token',auth);localStorage.setItem('active_tenant_id','browser-clinic');},{auth});
  await page.goto(base+'/test-panel');await page.getByRole('heading',{name:'Termos & Consentimentos'}).waitFor();
  await page.getByRole('button',{name:'Biblioteca de termos',exact:true}).click();
  await page.getByText('Configuração da clínica',{exact:true}).click();
  await page.getByLabel('Nível de confirmação').selectOption('basic');await page.getByRole('button',{name:'Salvar configuração'}).click();
  await page.getByRole('button',{name:'Criar termo próprio'}).click();
  await page.getByLabel('Título',{exact:true}).fill('Termo Browser universal');
  await page.getByLabel('Conteúdo completo').fill('Recebi informações claras sobre o atendimento. Tive oportunidade de tirar dúvidas. Concordo com o atendimento proposto para este teste.');
  await page.getByLabel('Termo obrigatório nesta área/serviço').check();await page.getByRole('button',{name:'Salvar modelo',exact:true}).click();
  await page.getByRole('heading',{name:'Termo Browser universal',exact:true}).waitFor();checks++;
  await page.getByText('⚠ Paciente possui termo obrigatório pendente.',{exact:false}).waitFor();checks++;
  const card=page.getByRole('heading',{name:'Termo Browser universal',exact:true}).locator('..');await card.getByRole('button',{name:'Usar modelo'}).click();
  await page.getByRole('button',{name:'Gerar solicitação'}).click();
  const open=page.getByRole('link',{name:'Assinar neste dispositivo'});await open.waitFor();const link=await open.getAttribute('href');
  await page.getByText('Mostrar QR Code',{exact:true}).click();
  assert.equal(await page.getByRole('img',{name:'QR Code para assinar este termo'}).count(),1);checks++;
  const signaturePage=await context.newPage();signaturePage.on('pageerror',e=>errors.push(e.message));await signaturePage.goto(link);
  await signaturePage.getByRole('heading',{name:'Termo Browser universal'}).waitFor();
  for(const checkbox of await signaturePage.getByRole('checkbox').all())await checkbox.check();
  const canvas=signaturePage.locator('canvas'),box=await canvas.boundingBox();
  await signaturePage.mouse.move(box.x+30,box.y+90);await signaturePage.mouse.down();for(let i=0;i<25;i++)await signaturePage.mouse.move(box.x+30+i*12,box.y+90+Math.sin(i)*25);await signaturePage.mouse.up();
  await signaturePage.screenshot({path:path.join(out,'public-desktop.png'),fullPage:true});
  await signaturePage.getByRole('button',{name:'Confirmar assinatura'}).click();await signaturePage.getByRole('heading',{name:'Termo assinado com sucesso'}).waitFor();checks++;
  const verification=await signaturePage.getByRole('link',{name:'Verificar autenticidade'}).getAttribute('href');await signaturePage.goto(verification);await signaturePage.getByRole('heading',{name:'Documento autêntico'}).waitFor();
  assert.ok(!(await signaturePage.locator('body').innerText()).includes('Paciente Browser'));checks++;
  await page.getByRole('button',{name:'Atualizar',exact:true}).click();await page.getByRole('button',{name:'Termos do paciente',exact:true}).click();await page.getByText('✓ Assinado',{exact:true}).waitFor();checks++;
  const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'PDF / imprimir'}).click();const download=await downloadPromise;await download.saveAs(path.join(out,'browser-signed.pdf'));assert.ok(fs.statSync(path.join(out,'browser-signed.pdf')).size>3000);checks++;
  await page.getByRole('button',{name:'Biblioteca de termos',exact:true}).click();await card.getByRole('button',{name:'Editar',exact:true}).click();await page.getByLabel('Conteúdo completo').fill('Versão dois do termo, com novas informações que devem solicitar nova assinatura sem alterar a versão assinada.');await page.getByRole('button',{name:'Salvar modelo',exact:true}).click();await page.getByRole('button',{name:'Termos do paciente',exact:true}).click();await page.getByText('⚠ Nova assinatura necessária',{exact:true}).waitFor();checks++;
  // Recommended OTP on a new request and mobile layout.
  await page.getByRole('button',{name:'Biblioteca de termos',exact:true}).click();await page.getByText('Configuração da clínica',{exact:true}).click();await page.getByLabel('Nível de confirmação').selectOption('recommended');await page.getByRole('button',{name:'Salvar configuração'}).click();
  await card.getByRole('button',{name:'Usar modelo'}).click();await page.getByRole('button',{name:'Gerar solicitação'}).click();await open.waitFor();const mobileLink=await open.getAttribute('href');
  const mobile=await context.newPage();await mobile.setViewportSize({width:375,height:812});await mobile.goto(mobileLink);await mobile.getByRole('heading',{name:'Termo Browser universal'}).waitFor();
  assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));checks++;
  const otpResponse=mobile.waitForResponse(r=>r.url().includes('/otp/request'));await mobile.getByRole('button',{name:'Enviar código',exact:true}).click();await otpResponse;await mobile.getByLabel('Código de 6 dígitos').fill(lastOtp);await mobile.getByRole('button',{name:'Validar código'}).click();await mobile.getByText('✓ Código confirmado.',{exact:false}).waitFor();checks++;
  for(const checkbox of await mobile.getByRole('checkbox').all())await checkbox.check();
  const mb=await mobile.locator('canvas').boundingBox();await mobile.locator('canvas').scrollIntoViewIfNeeded();const b=await mobile.locator('canvas').boundingBox();await mobile.mouse.move(b.x+20,b.y+80);await mobile.mouse.down();for(let i=0;i<22;i++)await mobile.mouse.move(b.x+20+i*10,b.y+80+Math.sin(i)*20);await mobile.mouse.up();
  await mobile.screenshot({path:path.join(out,'public-mobile.png'),fullPage:true});await mobile.getByRole('button',{name:'Confirmar assinatura'}).click();await mobile.getByRole('heading',{name:'Termo assinado com sucesso'}).waitFor();checks++;
  await mobile.goto(mobileLink);await mobile.getByText('Link expirado, cancelado ou já utilizado.').waitFor();checks++;
  await page.getByRole('button',{name:'Atualizar',exact:true}).click();
  await page.waitForFunction(()=>!document.body.textContent.includes('⚠ Nova assinatura necessária'));
  assert.equal(await page.getByText('⚠ Nova assinatura necessária',{exact:true}).count(),0);checks++;
  const panelMobile=await context.newPage();await panelMobile.setViewportSize({width:375,height:812});await panelMobile.goto(base+'/test-panel');await panelMobile.getByRole('heading',{name:'Termos & Consentimentos'}).waitFor();assert.ok(await panelMobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await panelMobile.screenshot({path:path.join(out,'panel-mobile.png'),fullPage:true});checks++;
  assert.deepEqual(errors,[]);assert.ok(!outbound.some(url=>/google.*(analytics|tagmanager)|facebook|fbevents/i.test(url)));checks++;
  console.log(JSON.stringify({checks,screenshots:out,pdf:path.join(out,'browser-signed.pdf'),analytics:'No trackers requested on public signing pages',externalMessages:'none'}));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>server.close());
