import React from 'react';
import { createRoot } from 'react-dom/client';
import { AuthProvider } from '../src/context/AuthContext';
import { ToastProvider } from '../src/context/ToastContext';
import { ApiClient } from '../src/api/client';
import { AppointmentConsultation } from '../src/components/clinical/AppointmentConsultation';
import { DashboardView } from '../src/components/dashboard/DashboardView';
import { CalendarView } from '../src/components/calendar/CalendarView';
import { ZemdaMedWorkspace } from '../src/components/medical/ZemdaMedWorkspace';
import { DentistryWorkspace } from '../src/components/dentistry/DentistryWorkspace';
import { NutritionWorkspace } from '../src/components/nutrition/NutritionWorkspace';
import { OccupationalTherapyWorkspace } from '../src/components/occupational-therapy/OccupationalTherapyWorkspace';
import { SpeechTherapyWorkspace } from '../src/components/speech-therapy/SpeechTherapyWorkspace';
import { PsychologyWorkspace } from '../src/components/psychology/PsychologyWorkspace';
import { PsychopedagogyWorkspace } from '../src/components/psychopedagogy/PsychopedagogyWorkspace';
import { PhysiotherapyWorkspace } from '../src/components/physiotherapy/PhysiotherapyWorkspace';
import { ZemdaEsteticWorkspace } from '../src/components/estetic/ZemdaEsteticWorkspace';
import { ZemdaPersonalView } from '../src/components/personal/ZemdaPersonalView';
import { GeneralClinicalWorkspace } from '../src/components/clinical/GeneralClinicalWorkspace';
const params = new URLSearchParams(location.search), moduleType=params.get('module')||'ZemdaPersonal', source=params.get('source')||'direct';
const state:any = {calls:[],events:0,finished:0,fail:false}; (window as any).__completion=state;
const patient:any={id:'patient',full_name:'Paciente teste',name:'Paciente teste',status:'active',created_at:'2026-01-01',birth_date:'1990-01-01'};
const professional:any={id:'professional',name:'Profissional teste',active:true};
const date=new Date(); date.setHours(10,0,0,0);
const localDate=[date.getFullYear(),String(date.getMonth()+1).padStart(2,'0'),String(date.getDate()).padStart(2,'0')].join('-');
const appointment:any={id:'appointment',patient_id:patient.id,patient_name:patient.full_name,professional_id:professional.id,professional_name:professional.name,service_id:'service',service_name:'Consulta',status:params.has('completed')?'completed':'scheduled',clinical_module:moduleType,start_time:localDate+'T10:00:00',end_time:localDate+'T10:50:00',modality:'presential'};
state.appointment=appointment;
const user:any={id:'user',name:professional.name,role:'clinic_admin',professionalId:professional.id,commercialModule:moduleType,clinicalWorkspace:moduleType,capabilities:[],permissions:['attend_appointment']};
localStorage.setItem('auth_token','fixture-token');
window.addEventListener('zemda-appointment-updated',()=>state.events++);
ApiClient.get=async (url:string):Promise<any>=>{
  state.calls.push({method:'GET',url});
  if(url==='/v1/auth/me')return {user,tenant:{id:'clinic',name:'Clínica teste'}};
  if(url.includes('/completion'))return {moduleType,alreadyCompleted:appointment.status==='completed'};
  if(url==='/v1/appointments/appointment')return {appointment:{...appointment}};
  if(url==='/v1/appointments')return [{...appointment}];
  if(url.startsWith('/v1/dashboard/metrics'))return {today:{appointments:[{...appointment}],total:1},monthly:{completed:appointment.status==='completed'?1:0},totals:{}};
  if(url==='/v1/professionals')return [professional];
  if(url==='/v1/professionals/professional')return professional;
  if(url==='/v1/patients/patient')return patient;
  if(url.startsWith('/v1/patients?')||url==='/v1/patients')return [patient];
  if(url.startsWith('/v1/nutrition/foods'))return [{id:'rice',name:'Arroz TACO',source:'TACO',energy_kcal:100,protein_g:3,carbohydrate_g:20,lipid_g:1}];
  if(url.includes('/draft/'))return {};
  if(url.includes('/psychology/profile/'))return {patient,sessions:[],documents:[]};
  if(url==='/v1/personal/students/patient')return {student:patient,workouts:[]};
  if(url.startsWith('/v1/personal/'))return {students:[patient],assessments:[],history:[],photos:[],logs:[],records:[],metrics:{},total:0};
  if(url.startsWith('/v1/estetic/'))return {};
  if(url.includes('medical-tree'))return {specialties:[]};
  if(url.includes('my-resources'))return {};
  return [];
};
ApiClient.post=async(url:string,body:any):Promise<any>=>{
  state.calls.push({method:'POST',url,body});
  if(url==='/v1/clinical/consultations/start') {
    appointment.status='in_progress';
    return {appointmentId:appointment.id,appointment:{...appointment},created:true};
  }
  if(url.endsWith('/finish')||url.endsWith('/finish-consultation')){
    if(state.fail)throw new Error('Falha simulada; dados preservados.');
    if(appointment.status==='completed')return {alreadyCompleted:true};
    appointment.status='completed';return {generatedDocs:{recordId:'record'},success:true};
  }
  return {id:'record',success:true};
};
ApiClient.put=async(url:string,body:any):Promise<any>=>{state.calls.push({method:'PUT',url,body});if(url.endsWith('/status'))appointment.status=body.status;return {success:true};};
ApiClient.delete=async(url:string):Promise<any>=>{state.calls.push({method:'DELETE',url});return {};};
const modules:any={ZemdaMed:ZemdaMedWorkspace,ZemdaOdonto:DentistryWorkspace,ZemdaNutri:NutritionWorkspace,ZemdaTO:OccupationalTherapyWorkspace,ZemdaFono:SpeechTherapyWorkspace,ZemdaPsico:PsychologyWorkspace,ZemdaPP:PsychopedagogyWorkspace,ZemdaFisio:PhysiotherapyWorkspace,ZemdaEstetic:ZemdaEsteticWorkspace,ZemdaPersonal:ZemdaPersonalView,general:GeneralClinicalWorkspace};
const Workspace=modules[moduleType];
const finished=()=>{state.finished++};
const props:any={initialPatientId:'patient',initialStudentId:'patient',initialAppointmentId:params.has('sidebar')?undefined:appointment.id,...(params.has('callback')?{onFinishConsultation:finished}:{})};
createRoot(document.getElementById('root')!).render(<AuthProvider><ToastProvider>{source==='dashboard'?<DashboardView onNavigate={()=>{}} onOpenNewAppointment={()=>{}} onOpenNewPatient={()=>{}}/>:source==='agenda'?<CalendarView onOpenNewAppointment={()=>{}}/>:source==='orchestrator'?<AppointmentConsultation appointment={appointment} initialModuleType={moduleType} onClose={()=>{}} onFinished={finished}/>:<Workspace {...props}/>}</ToastProvider></AuthProvider>);
