const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const base=process.env.TEST_BASE_URL||'http://127.0.0.1:5173';const out=process.env.TEST_OUTPUT_DIR||path.join(__dirname,'posture-results');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});try{
 const page=await browser.newPage({viewport:{width:1440,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));let saved,aiCalls=0,comparisons=[];
 await page.route('**/*',async route=>{const url=new URL(route.request().url());if(url.origin!==base)return route.abort();if(!url.pathname.startsWith('/api/'))return route.continue();let data={};
 if(url.pathname.endsWith('/url'))data={url:`${base}/exercise-photos/ex-prancha-isometrica-123b6d7c2f36.webp`};
 else if(url.pathname.endsWith('/posture-ai/status'))data={available:true};
 else if(url.pathname.endsWith('/posture-ai/analyze')){aiCalls++;data={suggestions:[{id:'ai-note',view:'front',region:'shoulders',text:'Possível diferença visual entre ombros. Confirmar enquadramento.',source:'ai',reviewed:false,evolution:'unrated'}]};}
 else if(url.pathname.includes('/compare/')){comparisons.push(url.search);const posture=saved.posture;data={current_assessment:{id:'assessment-2',assessment_date:'2026-09-25',posture_json:JSON.stringify(posture)},previous_assessment:{id:'baseline',assessment_date:'2026-01-01',posture_json:JSON.stringify(posture)},current_photos:[{photo_type:'front',file_id:'photo-front'}],previous_photos:[{photo_type:'front',file_id:'photo-front'}],metrics:[],posture_history:[{id:'baseline',assessment_date:'2026-01-01',count:1,pending:0,evolution:{improved:0,stable:0,worse:0}},{id:'assessment-2',assessment_date:'2026-09-25',count:2,pending:0,evolution:{improved:1,stable:1,worse:0}}],tav_comparison:{current:{value:null},previous:{value:null}}};}
 else if(url.pathname.endsWith('/assessments/assessment-2')&&route.request().method()==='PUT'){saved=route.request().postDataJSON();data={id:'assessment-2'};}
 else if(url.pathname.endsWith('/tav/protocols'))data={protocols:[]};return route.fulfill({json:data});});
 await page.goto(`${base}/tests/posture.html`);await page.getByRole('button',{name:/Fotos.*Parecer/}).click();await page.getByLabel('Modo Avaliação Postural').check();
 await page.getByRole('button',{name:'Caneta',exact:true}).click();const canvas=page.getByLabel('Área de marcação postural');await canvas.waitFor();const box=await canvas.boundingBox();await page.mouse.move(box.x+70,box.y+60);await page.mouse.down();await page.mouse.move(box.x+180,box.y+120,{steps:8});await page.mouse.up();
 await page.getByRole('button',{name:'Desfazer',exact:true}).click();await page.getByRole('button',{name:'Linha',exact:true}).click();await page.mouse.move(box.x+100,box.y+80);await page.mouse.down();await page.mouse.move(box.x+170,box.y+160);await page.mouse.up();
 await page.getByRole('button',{name:'Borracha',exact:true}).click();const strokesBefore=await canvas.locator('path[data-stroke]').count();assert.equal(strokesBefore,1);await canvas.locator('path[data-stroke]').dispatchEvent('pointerdown',{bubbles:true,pointerId:1});assert.equal(await canvas.locator('path[data-stroke]').count(),0);await page.getByRole('button',{name:'Desfazer',exact:true}).click();assert.equal(await canvas.locator('path[data-stroke]').count(),1);
 await page.getByLabel('Guias',{exact:true}).check();await page.getByRole('button',{name:'Adicionar observação: Ombros',exact:true}).click();await page.getByLabel('Observação postural',{exact:true}).fill('Ombro direito visualmente elevado; confirmar na avaliação.');await page.getByLabel('Evolução em relação à inicial').selectOption('stable');assert.equal(aiCalls,0);
 await page.getByRole('button',{name:'Analisar postura com IA',exact:true}).click();await page.getByText('aguarda revisão',{exact:false}).waitFor();assert.equal(aiCalls,1);await page.getByRole('button',{name:'Confirmar revisão',exact:true}).click();await page.getByLabel('Evolução em relação à inicial').nth(1).selectOption('improved');
 await page.screenshot({path:path.join(out,'editor.png'),fullPage:true});await page.getByRole('button',{name:/Salvar Avaliação/}).click();await page.getByRole('status').filter({hasText:'Avaliação salva'}).waitFor();assert.equal(saved.posture.views.front.strokes.length,1);assert.equal(saved.posture.views.front.strokes[0].tool,'line');assert.equal(saved.posture.observations.length,2);assert(saved.posture.observations.every(o=>o.reviewed));
 await page.evaluate(saved=>localStorage.setItem('posture-assessment',JSON.stringify({...saved,id:'assessment-2',posture_json:JSON.stringify(saved.posture)})),saved);await page.reload();await page.getByRole('button',{name:/Fotos.*Parecer/}).click();await page.getByLabel('Região postural').selectOption('shoulders');assert.equal(await page.getByLabel('Observação postural',{exact:true}).count(),2);assert.equal(aiCalls,1);

 await page.goto(`${base}/tests/posture.html?mode=edit-posture`);await page.getByRole('button',{name:'Salvar Avaliação Postural',exact:true}).click();await page.getByRole('status').filter({hasText:'Avaliação salva'}).waitFor();assert(!('weight' in saved));assert(!('body_fat_percentage' in saved));assert(saved.posture.observations.length===2);
 await page.goto(`${base}/tests/posture.html?mode=compare`);await page.getByRole('button',{name:/Avaliação Postural.*referência inicial/}).click();await page.getByRole('heading',{name:'Evolução postural',exact:true}).waitFor();assert(comparisons.includes('?posture_baseline=1'));await page.getByText(/Referência: primeira avaliação postural/).waitFor();await page.screenshot({path:path.join(out,'comparacao.png'),fullPage:true});await page.getByLabel('Sobreposição',{exact:true}).check();await page.getByLabel('Transparência da avaliação atual').fill('35');await page.screenshot({path:path.join(out,'sobreposicao.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);console.log('PASS drawing/undo/guides/region notes/AI only on click/review/save/reload/baseline/overlay/mobile; HTTP and AI mocked.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
