import type { SeedExercise } from './exercise-library.seed';

export const PRIORITY_EXPANSION_EXERCISES: SeedExercise[] = [
  {
    id: 'ex-supino-declinado-halteres',
    name: 'Supino Declinado com Halteres',
    muscle_group: 'Peitoral',
    secondary_muscles: ['Tríceps', 'Ombros (Deltoide Anterior)'],
    body_region: 'Membros Superiores',
    equipment: 'Halteres',
    category: 'Musculação',
    execution_type: 'bilateral',
    mechanics: 'peso livre',
    level: 'intermediario',
    instructions: 'Deitado em banco declinado fixando as pernas no apoio, segure os halteres sobre a linha inferior do peito. Desça os pesos de forma controlada até o alinhamento do peitoral e empurre estendendo os cotovelos sem bater os halteres no topo.',
    technical_notes: 'Foco na porção esternocostal inferior do peitoral maior, mantendo escápulas aduzidas e punhos firmes.'
  },
  {
    id: 'ex-supino-inclinado-maquina',
    name: 'Supino Inclinado na Máquina',
    muscle_group: 'Peitoral',
    secondary_muscles: ['Tríceps', 'Ombros (Deltoide Anterior)'],
    body_region: 'Membros Superiores',
    equipment: 'Máquina',
    category: 'Musculação',
    execution_type: 'bilateral',
    mechanics: 'máquina',
    level: 'iniciante',
    instructions: 'Ajuste o assento de modo que as manoplas fiquem na linha da clavícula. Mantenha as costas e a cabeça apoiadas no encosto, empurre as manoplas até quase a extensão total dos braços e retorne controlando o movimento.',
    technical_notes: 'Permite sobrecarga estável e direcionamento para a porção clavicular superior do peitoral sem demandar estabilização livre.'
  },
  {
    id: 'ex-supino-inclinado-smith',
    name: 'Supino Inclinado no Smith',
    muscle_group: 'Peitoral',
    secondary_muscles: ['Ombros (Deltoide Anterior)', 'Tríceps'],
    body_region: 'Membros Superiores',
    equipment: 'Smith',
    category: 'Musculação',
    execution_type: 'bilateral',
    mechanics: 'máquina',
    level: 'intermediario',
    instructions: 'Posicione o banco inclinado a 30-45 graus sob a barra guiada do Smith. Desça a barra de forma lenta até o terço superior do peito e empurre verticalmente mantendo a trajetória guiada.',
    technical_notes: 'Ajuste as travas de segurança na altura do peito para máxima segurança sob cargas elevadas.'
  },
  {
    id: 'ex-flexao-joelhos-apoiados',
    name: 'Flexão de Braços com Joelhos Apoiados',
    muscle_group: 'Peitoral',
    secondary_muscles: ['Tríceps', 'Ombros', 'Abdômen/Core'],
    body_region: 'Membros Superiores',
    equipment: 'Peso Corporal',
    category: 'Musculação',
    execution_type: 'bilateral',
    mechanics: 'peso corporal',
    level: 'iniciante',
    instructions: 'Apoie os joelhos e as mãos no solo, com as mãos ligeiramente mais largas que a largura dos ombros. Mantenha o quadril e a coluna alinhados, desça o peito em direção ao solo e empurre até a extensão quase completa dos braços.',
    technical_notes: 'Excelente regressão para iniciantes desenvolverem força e padrão motor antes da flexão padrão.'
  },
  {
    id: 'ex-pullover-polia',
    name: 'Pullover na Polia Alta',
    muscle_group: 'Costas',
    secondary_muscles: ['Peitoral', 'Tríceps (Cabeça Longa)', 'Serrátil anterior'],
    body_region: 'Membros Superiores',
    equipment: 'Cabo / Polia',
    category: 'Musculação',
    execution_type: 'bilateral',
    mechanics: 'cabo/polia',
    level: 'intermediario',
    instructions: 'Deitado em banco posicionado em frente à polia ou em pé com leve inclinação de tronco, segure a corda ou barra com cotovelos semiflexionados. Conduza as mãos em arco sobre a cabeça até o alinhamento das costelas mantendo o tórax expandido.',
    technical_notes: 'Mantém tensão constante do cabo ao longo de toda a curva de resistência articular.'
  },
  {
    id: 'ex-barra-fixa-neutra',
    name: 'Barra Fixa com Pegada Neutra',
    muscle_group: 'Costas',
    secondary_muscles: ['Bíceps', 'Braquial', 'Antebraços'],
    body_region: 'Membros Superiores',
    equipment: 'Peso Corporal',
    category: 'Musculação',
    execution_type: 'bilateral',
    mechanics: 'peso corporal',
    level: 'intermediario',
    instructions: 'Segure nas manoplas paralelas com as palmas voltadas uma para a outra. Inicie o movimento deprimindo as escápulas e puxe o corpo para cima até o queixo ultrapassar a linha das mãos. Desça controlando até estender os braços.',
    technical_notes: 'Pegada mais anatômica e confortável para ombros e punhos do que a barra fixa pronada clássica.'
  },
  {
    id: 'ex-remada-pendlay',
    name: 'Remada Pendlay com Barra',
    muscle_group: 'Costas',
    secondary_muscles: ['Trapézio', 'Romboides', 'Bíceps', 'Lombar'],
    body_region: 'Membros Superiores',
    equipment: 'Barra',
    category: 'Musculação',
    execution_type: 'bilateral',
    mechanics: 'peso livre',
    level: 'avancado',
    instructions: 'Com a barra no solo e o tronco estritamente paralelo ao chão (90 graus), puxe a barra explosivamente até encostar na linha média do abdômen/peito inferior e retorne ao solo a cada repetição partindo da inércia (dead stop).',
    technical_notes: 'Não utilize impulso das pernas ou elevação do tronco; o tronco deve permanecer horizontal estático durante todo o movimento.'
  },
  {
    id: 'ex-remada-baixa-pegada-aberta',
    name: 'Remada Baixa com Pegada Aberta',
    muscle_group: 'Costas',
    secondary_muscles: ['Trapézio Médio', 'Romboides', 'Deltoide Posterior', 'Bíceps'],
    body_region: 'Membros Superiores',
    equipment: 'Cabo / Polia',
    category: 'Musculação',
    execution_type: 'bilateral',
    mechanics: 'cabo/polia',
    level: 'iniciante',
    instructions: 'Sentado no banco da polia baixa com os pés apoiados, segure a barra reta com pegada pronada aberta. Puxe a barra em direção ao abdômen superior trazendo os cotovelos apontados para fora e aduzindo fortemente as escápulas.',
    technical_notes: 'Foco prioritário nos retratores da escápula (romboides e trapézio) e deltoide posterior.'
  },
  {
    id: 'ex-remada-articulada-unilateral',
    name: 'Remada Articulada Unilateral na Máquina',
    muscle_group: 'Costas',
    secondary_muscles: ['Grande Dorsal', 'Bíceps', 'Romboides'],
    body_region: 'Membros Superiores',
    equipment: 'Máquina',
    category: 'Musculação',
    execution_type: 'unilateral',
    mechanics: 'máquina',
    level: 'iniciante',
    instructions: 'Com o peito apoiado na almofada, segure a manopla com uma das mãos. Puxe para trás rente ao tronco direcionando o cotovelo para o quadril, contraindo o dorsal unilateralmente. Retorne controlando o peso.',
    technical_notes: 'Permite isolamento do dorsal e amplitude livre de tração sem rotação excessiva da coluna.'
  },
  {
    id: 'ex-pullover-maquina',
    name: 'Pullover na Máquina Articulada',
    muscle_group: 'Costas',
    secondary_muscles: ['Grande Dorsal', 'Peitoral', 'Tríceps (Cabeça Longa)'],
    body_region: 'Membros Superiores',
    equipment: 'Máquina',
    category: 'Musculação',
    execution_type: 'bilateral',
    mechanics: 'máquina',
    level: 'intermediario',
    instructions: 'Sente-se na máquina com o encosto ajustado para que o eixo de rotação alinhe-se à articulação dos ombros. Apoie os cotovelos nas almofadas, puxe para baixo e para trás em arco até as mãos ficarem próximas à cintura.',
    technical_notes: 'Excelente para recrutar o grande dorsal em toda a curva de extensão de ombro sem fadigar os antebraços e bíceps.'
  },
  {
    id: 'ex-rosca-martelo-cruzada',
    name: 'Rosca Martelo Cruzada no Peito',
    muscle_group: 'Bíceps',
    secondary_muscles: ['Braquial', 'Braquiorradial', 'Antebraços'],
    body_region: 'Membros Superiores',
    equipment: 'Halteres',
    category: 'Musculação',
    execution_type: 'unilateral',
    mechanics: 'peso livre',
    level: 'iniciante',
    instructions: 'Em pé com halteres nas mãos e palmas neutras, flexione o cotovelo trazendo o halter em diagonal cruzando a frente do tronco em direção ao ombro oposto. Retorne de forma lenta e repita com o outro braço.',
    technical_notes: 'Enfatiza o músculo braquial e braquiorradial conferindo maior espessura e densidade ao braço.'
  },
  {
    id: 'ex-spanish-squat',
    name: 'Agachamento Espanhol (Spanish Squat)',
    muscle_group: 'Quadríceps',
    secondary_muscles: ['Glúteos', 'Tendão Patelar'],
    body_region: 'Membros Inferiores',
    equipment: 'Elástico',
    category: 'Musculação',
    execution_type: 'bilateral',
    mechanics: 'peso corporal',
    level: 'intermediario',
    instructions: 'Prenda uma faixa elástica pesada em suporte firme e posicione-a atrás dos joelhos. Afaste-se mantendo a fita tensionada, mantenha o tronco ereto e agache empurrando os joelhos firmemente contra o elástico, sustentando a postura vertical.',
    technical_notes: 'Permite agachamento com tíbias quase verticais, altamente recomendado em protocolos de reabilitação e hipertrofia com sobrecarga articular reduzida.'
  },
  {
    id: 'ex-glute-ham-raise',
    name: 'Flexão Nórdica Inversa no Banco GHR (Glute Ham Raise)',
    muscle_group: 'Posteriores de coxa',
    secondary_muscles: ['Glúteos', 'Gastrocnêmio', 'Lombar'],
    body_region: 'Membros Inferiores',
    equipment: 'Peso Corporal',
    category: 'Musculação',
    execution_type: 'bilateral',
    mechanics: 'peso corporal',
    level: 'avancado',
    instructions: 'Prenda os pés entre os rolos do banco GHR com as coxas na almofada frontal. Desça o tronco estendendo os joelhos de forma controlada e puxe de volta flexionando vigorosamente os joelhos e acionando glúteos e isquiotibiais.',
    technical_notes: 'Um dos exercícios mais completos e intensos da cadeia posterior para prevenção de lesões e potência.'
  },
  {
    id: 'ex-panturrilha-donkey',
    name: 'Elevação de Panturrilha Donkey (Burrinho)',
    muscle_group: 'Panturrilhas',
    secondary_muscles: ['Gastrocnêmio', 'Sóleo'],
    body_region: 'Membros Inferiores',
    equipment: 'Peso Corporal',
    category: 'Musculação',
    execution_type: 'bilateral',
    mechanics: 'peso corporal',
    level: 'iniciante',
    instructions: 'Incline o tronco para frente apoiando as mãos em banco ou suporte, mantendo o quadril flexionado a cerca de 90 graus e a ponta dos pés na borda de um degrau. Faça a flexão plantar máxima e desça até sentir o alongamento total da panturrilha.',
    technical_notes: 'A flexão de quadril pré-estira a cadeia posterior aumentando o braço de momento do gastrocnêmio.'
  },
  {
    id: 'ex-elevacao-joelhos-suspenso',
    name: 'Elevação de Joelhos na Barra Fixa (Hanging Knee Raise)',
    muscle_group: 'Abdômen/Core',
    secondary_muscles: ['Flexores de quadril', 'Antebraços'],
    body_region: 'Tronco / Core',
    equipment: 'Peso Corporal',
    category: 'Funcional',
    execution_type: 'bilateral',
    mechanics: 'peso corporal',
    level: 'intermediario',
    instructions: 'Suspenso na barra fixa com pegada pronada, ative as escápulas e flexione os joelhos elevando-os em direção ao peito através da flexão da pelve. Desça sem embalar o corpo.',
    technical_notes: 'Excelente alternativa com menor braço de alavanca em relação à elevação de pernas estendidas.'
  },
  {
    id: 'ex-kettlebell-clean-press',
    name: 'Clean and Press com Kettlebell',
    muscle_group: 'Corpo inteiro',
    secondary_muscles: ['Ombros', 'Glúteos', 'Tríceps', 'Core'],
    body_region: 'Corpo Inteiro',
    equipment: 'Kettlebell',
    category: 'Funcional',
    execution_type: 'unilateral',
    mechanics: 'peso livre',
    level: 'avancado',
    instructions: 'Puxe o kettlebell do solo ou entre as pernas em um movimento explosivo de quadril recebendo-o na posição de rack no ombro (Clean). A partir daí, empurre-o verticalmente acima da cabeça até estender o braço (Press).',
    technical_notes: 'Exercício dinâmico e multiarticular que exige coordenação, potência de quadril e força escapular.'
  },
  {
    id: 'ex-kettlebell-row',
    name: 'Remada Curvada com Kettlebell',
    muscle_group: 'Costas',
    secondary_muscles: ['Bíceps', 'Romboides', 'Antebraços'],
    body_region: 'Membros Superiores',
    equipment: 'Kettlebell',
    category: 'Funcional',
    execution_type: 'unilateral',
    mechanics: 'peso livre',
    level: 'intermediario',
    instructions: 'Em postura inclinada com tronco firme, segure a alça do kettlebell com o braço estendido. Puxe o peso em direção à cintura mantendo o cotovelo rente ao tronco e retorne controladamente.',
    technical_notes: 'A empunhadura espessa do kettlebell estimula fortemente a força isométrica da mão e antebraço.'
  },
  {
    id: 'ex-kettlebell-overhead-press',
    name: 'Desenvolvimento Overhead com Kettlebell',
    muscle_group: 'Ombros',
    secondary_muscles: ['Tríceps', 'Core'],
    body_region: 'Membros Superiores',
    equipment: 'Kettlebell',
    category: 'Funcional',
    execution_type: 'unilateral',
    mechanics: 'peso livre',
    level: 'intermediario',
    instructions: 'A partir da posição de rack junto ao ombro, empurre o kettlebell em linha reta vertical acima da cabeça sem inclinar a coluna para trás. Finalize com braço alinhado à orelha.',
    technical_notes: 'O centro de gravidade deslocado do kettlebell exige estabilização escapuloumeral ativa.'
  },
  {
    id: 'ex-mb-chest-pass',
    name: 'Passe de Peito Explosivo com Medicine Ball',
    muscle_group: 'Peitoral',
    secondary_muscles: ['Tríceps', 'Ombros', 'Abdômen/Core'],
    body_region: 'Membros Superiores',
    equipment: 'Medicine Ball',
    category: 'Funcional',
    execution_type: 'bilateral',
    mechanics: 'peso livre',
    level: 'intermediario',
    instructions: 'Em base atlética firme diante de uma parede sólida, segure a medicine ball junto ao peito e arremesse-a com máxima potência explosiva para a frente estendendo os braços. Recolha o rebote e repita.',
    technical_notes: 'Treina a taxa de desenvolvimento de força (RFD) dos membros superiores sem fase desacelerativa.'
  },
  {
    id: 'ex-agachamento-salto',
    name: 'Agachamento com Salto (Jump Squat)',
    muscle_group: 'Quadríceps',
    secondary_muscles: ['Glúteos', 'Panturrilhas'],
    body_region: 'Membros Inferiores',
    equipment: 'Peso Corporal',
    category: 'Cardiorrespiratório',
    execution_type: 'bilateral',
    mechanics: 'peso corporal',
    level: 'intermediario',
    instructions: 'Realize um agachamento até cerca de 90 graus e imediatamente impulsione o solo com potência máxima estendendo tornozelos, joelhos e quadril em um salto vertical. Aterrisse suavemente amortecendo a queda.',
    technical_notes: 'Aterrisse do antepé para o calcanhar com joelhos destravados para absorção de impacto.'
  },
  {
    id: 'ex-afundo-salto',
    name: 'Afundo com Salto (Jumping Lunge)',
    muscle_group: 'Quadríceps',
    secondary_muscles: ['Glúteos', 'Panturrilhas'],
    body_region: 'Membros Inferiores',
    equipment: 'Peso Corporal',
    category: 'Cardiorrespiratório',
    execution_type: 'unilateral',
    mechanics: 'peso corporal',
    level: 'avancado',
    instructions: 'Em posição de afundo, salte explosivamente trocando a posição das pernas no ar e aterrissando na postura de afundo oposta com absorção suave de impacto.',
    technical_notes: 'Alta intensidade neuromuscular e cardiovascular; manter tronco ereto e joelho dianteiro alinhado.'
  },
  {
    id: 'ex-flexao-arqueiro',
    name: 'Flexão Arqueiro (Archer Push-up)',
    muscle_group: 'Peitoral',
    secondary_muscles: ['Tríceps', 'Ombros', 'Abdômen/Core'],
    body_region: 'Membros Superiores',
    equipment: 'Peso Corporal',
    category: 'Musculação',
    execution_type: 'unilateral',
    mechanics: 'peso corporal',
    level: 'avancado',
    instructions: 'Com as mãos bem afastadas além da largura dos ombros, desça o corpo em direção a uma das mãos mantendo o outro braço completamente estendido ao lado. Empurre e alterne o lado.',
    technical_notes: 'Excelente ponte da calistenia para desenvolver força unilateral rumo à flexão com um braço.'
  },
  {
    id: 'ex-handstand-push-up',
    name: 'Flexão na Parada de Mãos (Handstand Push-up)',
    muscle_group: 'Ombros',
    secondary_muscles: ['Tríceps', 'Trapézio', 'Core'],
    body_region: 'Membros Superiores',
    equipment: 'Peso Corporal',
    category: 'Musculação',
    execution_type: 'bilateral',
    mechanics: 'peso corporal',
    level: 'avancado',
    instructions: 'Em parada de mãos apoiado em parede firme com corpo travado em linha reta, flexione os cotovelos até a cabeça tocar suavemente o solo/almofada e empurre o solo estendendo os braços.',
    technical_notes: 'Exercício calistênico avançado de força vertical pura para ombros e tríceps.'
  },
  {
    id: 'ex-corrida-estacionaria',
    name: 'Corrida Estacionária',
    muscle_group: 'Cardiorrespiratórios',
    secondary_muscles: ['Panturrilhas', 'Quadríceps', 'Core'],
    body_region: 'Corpo Inteiro',
    equipment: 'Peso Corporal',
    category: 'Cardiorrespiratório',
    execution_type: 'dinâmico',
    mechanics: 'peso corporal',
    level: 'iniciante',
    instructions: 'Corra no mesmo lugar sem sair do ponto com cadência contínua, amortecendo a aterrissagem sobre o antepé e coordenando o movimento alternado dos braços.',
    technical_notes: 'Excelente opção de aquecimento dinâmico e cardio indoor sem necessidade de esteira ou estepe.'
  },
  {
    id: 'ex-skater-jump',
    name: 'Salto do Patinador (Skater Jump)',
    muscle_group: 'Cardiorrespiratórios',
    secondary_muscles: ['Glúteo Médio', 'Quadríceps', 'Panturrilhas'],
    body_region: 'Membros Inferiores',
    equipment: 'Peso Corporal',
    category: 'Cardiorrespiratório',
    execution_type: 'unilateral',
    mechanics: 'peso corporal',
    level: 'intermediario',
    instructions: 'Salte lateralmente de uma perna para a outra, aterrissando suavemente em apoio unipodal com a perna livre cruzando por trás, simulando a passada de patinação.',
    technical_notes: 'Desenvolve potência no plano frontal e estabilidade do complexo quadril-joelho-tornozelo.'
  },
  {
    id: 'ex-scapular-pull-up',
    name: 'Puxada Escapular na Barra Fixa',
    muscle_group: 'Mobilidade',
    secondary_muscles: ['Trapézio Inferior', 'Romboides', 'Dorsal'],
    body_region: 'Membros Superiores',
    equipment: 'Peso Corporal',
    category: 'Mobilidade',
    execution_type: 'bilateral',
    mechanics: 'mobilidade',
    level: 'iniciante',
    instructions: 'Pendure-se na barra com os braços totalmente estendidos. Sem dobrar os cotovelos, eleve o corpo puxando e deprimindo as escápulas para baixo e para trás. Segure por 1 segundo e relaxe suavemente.',
    technical_notes: 'Ativa o trapézio inferior e educa o início correto da puxada em barras fixas e puxadas.'
  },
];
