import type { SeedExercise } from './exercise-library.seed';

// Each row describes a distinct movement or equipment variation, not a renamed duplicate.
type Row = [string, string, string, string, string, string];
const strength: Row[] = [
  ['supino-maquina', 'Supino na Máquina Convergente', 'Peitoral', 'Máquina', 'Sentado com costas apoiadas e manoplas na altura do peito, empurre e retorne controladamente.', 'Tríceps|Ombros'],
  ['supino-neutro-halteres', 'Supino com Halteres em Pegada Neutra', 'Peitoral', 'Halteres', 'Deitado no banco, mantenha palmas voltadas uma para a outra; desça junto ao tronco e estenda os braços.', 'Tríceps|Ombros'],
  ['supino-solo-halteres', 'Supino no Solo com Halteres (Floor Press)', 'Peitoral', 'Halteres', 'Deitado no solo com joelhos dobrados, desça até os braços tocarem suavemente o chão e empurre.', 'Tríceps'],
  ['supino-smith', 'Supino Reto no Smith', 'Peitoral', 'Smith', 'Ajuste o banco sob a barra e as travas; desça a barra à linha do peito e empurre mantendo os pés apoiados.', 'Tríceps|Ombros'],
  ['flexao-inclinada', 'Flexão com Mãos Elevadas', 'Peitoral', 'Peso Corporal', 'Apoie as mãos em banco firme e mantenha corpo alinhado; flexione cotovelos aproximando peito do apoio e retorne.', 'Tríceps|Abdômen/Core'],
  ['flexao-declinada', 'Flexão com Pés Elevados', 'Peitoral', 'Peso Corporal', 'Com pés em apoio firme e mãos no solo, desça o peito entre as mãos e empurre sem deixar a pelve cair.', 'Ombros|Tríceps'],
  ['supino-elastico', 'Press de Peito com Elástico', 'Peitoral', 'Elástico', 'Com elástico fixado atrás na altura do peito, dê um passo à frente e empurre as mãos mantendo tronco estável.', 'Tríceps|Ombros'],
  ['crucifixo-unilateral-cabo', 'Crucifixo Unilateral no Cabo', 'Peitoral', 'Cabo / Polia', 'Em base afastada lateralmente à polia, conduza um braço à frente do peito e retorne sem girar o tronco.', 'Abdômen/Core|Ombros'],
  ['remada-peito-apoiado', 'Remada com Halteres e Peito Apoiado', 'Costas', 'Halteres', 'De bruços em banco inclinado, puxe halteres em direção às costelas e estenda os braços controladamente.', 'Bíceps|Deltoide posterior'],
  ['remada-unilateral-cabo', 'Remada Unilateral na Polia', 'Costas', 'Cabo / Polia', 'Sentado diante da polia, puxe uma manopla até a lateral do tronco mantendo ombros e pelve alinhados.', 'Bíceps|Abdômen/Core'],
  ['remada-elastico', 'Remada Sentada com Elástico', 'Costas', 'Elástico', 'Sentado com elástico em ponto de fixação firme, puxe cotovelos para trás e retorne sem inclinar a lombar.', 'Bíceps|Romboides'],
  ['remada-invertida', 'Remada Invertida na Barra', 'Costas', 'Peso Corporal', 'Sob barra fixada, apoie calcanhares e puxe o peito em direção à barra mantendo corpo alinhado.', 'Bíceps|Abdômen/Core'],
  ['puxada-unilateral', 'Puxada Unilateral na Polia Alta', 'Costas', 'Cabo / Polia', 'Sentado ou ajoelhado, puxe a manopla acima da cabeça até a lateral do peito sem inclinar o tronco.', 'Bíceps'],
  ['barra-fixa-assistida', 'Barra Fixa na Máquina Assistida', 'Costas', 'Máquina', 'Ajuste a assistência, apoie os joelhos e puxe o corpo até aproximar o peito das manoplas.', 'Bíceps|Antebraços'],
  ['pullover-halter', 'Pullover com Halter', 'Costas', 'Halteres', 'Deitado no banco, segure um halter acima do peito e leve-o atrás da cabeça em arco confortável, retornando.', 'Peitoral|Tríceps'],
  ['remada-alta-maquina', 'Remada Alta Articulada (High Row)', 'Costas', 'Máquina', 'Com peito apoiado, puxe as manoplas altas em direção às costelas e controle o retorno.', 'Bíceps|Deltoide posterior'],
  ['desenvolvimento-arnold', 'Desenvolvimento Arnold', 'Ombros', 'Halteres', 'Sentado com halteres à frente do rosto, gire palmas para frente enquanto eleva os braços; retorne controladamente.', 'Tríceps'],
  ['landmine-press', 'Press Unilateral no Landmine', 'Ombros', 'Barra', 'Em meio-ajoelhado, segure a ponta da barra ancorada junto ao ombro e empurre diagonalmente para cima.', 'Peitoral|Tríceps|Abdômen/Core'],
  ['elevacao-lateral-maquina', 'Elevação Lateral na Máquina', 'Ombros', 'Máquina', 'Ajuste o assento e apoie braços nas almofadas; eleve lateralmente até amplitude confortável e retorne.', 'Trapézio'],
  ['crucifixo-inverso-cabo', 'Crucifixo Inverso no Cabo', 'Ombros', 'Cabo / Polia', 'Com cabos cruzados à frente, afaste os braços mantendo cotovelos levemente flexionados.', 'Romboides|Trapézio'],
  ['rotacao-externa-elastico', 'Rotação Externa de Ombro com Elástico', 'Ombros', 'Elástico', 'Com cotovelo junto ao tronco a 90 graus, gire o antebraço para fora sem deslocar o braço.', 'Infraespinal|Redondo menor'],
  ['rotacao-interna-cabo', 'Rotação Interna de Ombro na Polia', 'Ombros', 'Cabo / Polia', 'Com cotovelo junto ao tronco a 90 graus, conduza a mão em direção ao abdômen sem girar o tronco.', 'Subescapular'],
  ['elevacao-y-banco', 'Elevação em Y no Banco Inclinado', 'Ombros', 'Halteres', 'Com peito apoiado e polegares voltados para cima, eleve os braços em Y sem arquear a lombar.', 'Trapézio inferior'],
  ['serratus-punch', 'Protração Escapular com Halteres', 'Ombros', 'Halteres', 'Deitado com braços verticais, leve as mãos em direção ao teto movendo as escápulas e retorne.', 'Serrátil anterior'],
  ['rosca-cabo-baixo', 'Rosca Direta na Polia Baixa', 'Bíceps', 'Cabo / Polia', 'Em pé diante da polia, flexione cotovelos com braços junto ao tronco e retorne sem balançar.', 'Braquial|Antebraços'],
  ['rosca-scott-maquina', 'Rosca Scott na Máquina', 'Bíceps', 'Máquina', 'Apoie a parte posterior dos braços no suporte e flexione cotovelos, controlando o retorno.', 'Braquial'],
  ['rosca-bayesian', 'Rosca Unilateral no Cabo Atrás do Corpo', 'Bíceps', 'Cabo / Polia', 'De costas à polia baixa, mantenha braço ligeiramente atrás do tronco e flexione o cotovelo.', 'Braquial'],
  ['rosca-elastico', 'Rosca com Elástico', 'Bíceps', 'Elástico', 'Pise no centro do elástico e flexione cotovelos, mantendo braços junto ao corpo e punhos alinhados.', 'Braquial|Antebraços'],
  ['rosca-inversa-barra', 'Rosca Inversa com Barra', 'Antebraços', 'Barra', 'Segure a barra com palmas para baixo e flexione os cotovelos sem dobrar os punhos.', 'Braquiorradial|Bíceps'],
  ['pronacao-supinacao', 'Pronação e Supinação com Halter', 'Antebraços', 'Halteres', 'Sentado com antebraço apoiado, gire lentamente a palma para cima e para baixo segurando carga leve.', 'Pronadores|Supinador'],
  ['desvio-radial', 'Desvio Radial do Punho com Halter', 'Antebraços', 'Halteres', 'Com antebraço apoiado e polegar para cima, mova o punho para cima e retorne sem mover cotovelo.', 'Extensores do punho'],
  ['triceps-unilateral-cabo', 'Extensão Unilateral de Tríceps na Polia', 'Tríceps', 'Cabo / Polia', 'Mantenha um cotovelo junto ao tronco e estenda-o puxando a manopla para baixo.', 'Ancôneo'],
  ['triceps-acima-cabo', 'Extensão de Tríceps Acima da Cabeça no Cabo', 'Tríceps', 'Cabo / Polia', 'De costas à polia, braços elevados, estenda os cotovelos sem mover o tronco.', 'Abdômen/Core'],
  ['triceps-maquina', 'Extensão de Tríceps na Máquina', 'Tríceps', 'Máquina', 'Ajuste apoios e manoplas, estenda os cotovelos e retorne controladamente.', 'Ancôneo'],
  ['supino-fechado', 'Supino com Pegada Fechada', 'Tríceps', 'Barra', 'Deitado no banco, segure a barra aproximadamente na largura dos ombros e empurre com cotovelos próximos ao tronco.', 'Peitoral|Ombros'],
  ['triceps-elastico', 'Extensão de Tríceps com Elástico Alto', 'Tríceps', 'Elástico', 'Fixe o elástico acima da cabeça e estenda os cotovelos mantendo braços junto ao tronco.', 'Ancôneo'],
  ['pallof-press', 'Pallof Press na Polia', 'Abdômen/Core', 'Cabo / Polia', 'De lado para a polia, segure a manopla junto ao peito e estenda braços resistindo à rotação.', 'Oblíquos|Glúteos'],
  ['woodchop-cabo', 'Rotação Diagonal no Cabo (Woodchop)', 'Abdômen/Core', 'Cabo / Polia', 'Em pé lateralmente à polia alta, conduza a manopla em diagonal até o quadril oposto com rotação controlada.', 'Oblíquos|Ombros'],
  ['bird-dog', 'Bird Dog em Quatro Apoios', 'Abdômen/Core', 'Peso Corporal', 'Em quatro apoios, estenda braço e perna opostos sem girar a pelve; retorne e alterne.', 'Lombar|Glúteos'],
  ['prancha-toque-ombro', 'Prancha com Toque nos Ombros', 'Abdômen/Core', 'Peso Corporal', 'Em prancha alta com pés afastados, toque uma mão no ombro oposto sem girar o quadril.', 'Ombros|Glúteos'],
  ['hollow-hold', 'Hollow Hold', 'Abdômen/Core', 'Peso Corporal', 'Deitado, eleve ombros e pernas mantendo lombar apoiada; ajuste a extensão das pernas para sustentar a posição.', 'Flexores do quadril'],
  ['reverse-crunch', 'Crunch Reverso com Elevação da Pelve', 'Abdômen/Core', 'Peso Corporal', 'Deitado com joelhos dobrados, enrole a pelve elevando-a levemente e retorne sem impulso.', 'Oblíquos'],
  ['suitcase-carry', 'Caminhada com Carga Unilateral', 'Abdômen/Core', 'Kettlebell', 'Caminhe com kettlebell em uma mão, mantendo tronco vertical e passos controlados; troque o lado.', 'Antebraços|Glúteos'],
  ['stir-pot', 'Prancha Circular na Bola', 'Abdômen/Core', 'Bola Suíça', 'Apoie antebraços na bola e descreva pequenos círculos sem perder o alinhamento da pelve.', 'Ombros'],
  ['extensao-quadril-banco', 'Extensão de Quadril no Banco Romano', 'Lombar', 'Banco Romano', 'Apoie a pelve no banco e faça flexão e extensão do quadril mantendo a coluna alinhada.', 'Glúteos|Posteriores de coxa'],
  ['hip-hinge-bastao', 'Dobradiça de Quadril com Bastão', 'Lombar', 'Bastão', 'Mantenha bastão em contato com cabeça, tórax e sacro; leve quadril para trás e retorne preservando os contatos.', 'Glúteos|Posteriores de coxa'],
  ['agachamento-goblet', 'Agachamento Goblet', 'Quadríceps', 'Kettlebell', 'Segure kettlebell junto ao peito, flexione joelhos e quadril e retorne mantendo pés apoiados.', 'Glúteos|Abdômen/Core'],
  ['agachamento-caixa', 'Agachamento na Caixa', 'Quadríceps', 'Barra', 'Com barra apoiada nas costas, desça até tocar suavemente uma caixa firme e levante sem balanço.', 'Glúteos|Posteriores de coxa'],
  ['step-up', 'Subida no Banco com Halteres', 'Quadríceps', 'Halteres', 'Coloque um pé inteiro no banco firme e suba estendendo a perna apoiada; desça controladamente.', 'Glúteos|Panturrilhas'],
  ['avanco-reverso', 'Avanço Reverso com Halteres', 'Quadríceps', 'Halteres', 'Em pé, dê um passo para trás e flexione ambos os joelhos; retorne apoiando o pé da frente.', 'Glúteos'],
  ['extensora-unilateral', 'Cadeira Extensora Unilateral', 'Quadríceps', 'Máquina', 'Ajuste o eixo ao joelho e estenda uma perna por vez sem levantar a pelve do assento.', 'Reto femoral'],
  ['legpress-unilateral', 'Leg Press Unilateral', 'Quadríceps', 'Máquina', 'Com um pé na plataforma, flexione o joelho até amplitude que preserve a pelve apoiada e empurre.', 'Glúteos'],
  ['agachamento-peso-corporal', 'Agachamento com Peso Corporal', 'Quadríceps', 'Peso Corporal', 'Com pés apoiados, flexione quadril e joelhos, desça na amplitude controlável e retorne.', 'Glúteos|Abdômen/Core'],
  ['wall-sit', 'Agachamento Isométrico na Parede', 'Quadríceps', 'Peso Corporal', 'Apoie costas na parede, avance os pés e deslize até a posição escolhida pelo profissional; sustente.', 'Glúteos'],
  ['rdl-unilateral', 'Terra Romeno Unilateral com Halter', 'Posteriores de coxa', 'Halteres', 'Apoiado em uma perna, incline o tronco pelo quadril e estenda a outra perna para trás; retorne.', 'Glúteos|Abdômen/Core'],
  ['flexora-bola', 'Flexão de Joelhos na Bola Suíça', 'Posteriores de coxa', 'Bola Suíça', 'Deitado com calcanhares na bola e quadril elevado, flexione joelhos trazendo a bola e retorne.', 'Glúteos|Abdômen/Core'],
  ['flexora-deslizante', 'Flexão de Joelhos com Discos Deslizantes', 'Posteriores de coxa', 'Discos Deslizantes', 'Deitado com calcanhares nos discos, eleve a pelve e deslize os pés para longe e para perto.', 'Glúteos'],
  ['flexora-elastico', 'Flexão de Joelhos com Elástico', 'Posteriores de coxa', 'Elástico', 'De bruços com elástico fixado aos tornozelos, dobre joelhos sem levantar a pelve.', 'Gastrocnêmio'],
  ['ponte-gluteos-solo', 'Ponte de Glúteos no Solo', 'Glúteos', 'Peso Corporal', 'Deitado com joelhos dobrados e pés apoiados, eleve a pelve e retorne sem arquear a lombar.', 'Posteriores de coxa|Abdômen/Core'],
  ['hip-thrust-maquina', 'Elevação Pélvica na Máquina', 'Glúteos', 'Máquina', 'Ajuste o apoio sobre a pelve e os pés na plataforma; estenda o quadril mantendo costelas controladas.', 'Posteriores de coxa'],
  ['pull-through', 'Pull Through na Polia', 'Glúteos', 'Cabo / Polia', 'De costas à polia baixa, segure a corda entre as pernas; leve quadril para trás e estenda-o.', 'Posteriores de coxa|Lombar'],
  ['abducao-decubito', 'Abdução de Quadril em Decúbito Lateral', 'Abdutores', 'Peso Corporal', 'De lado com pelve alinhada, eleve a perna de cima sem rodar o tronco e retorne.', 'Glúteo médio'],
  ['caminhada-lateral-elastico', 'Caminhada Lateral com Miniband', 'Abdutores', 'Elástico', 'Com miniband acima dos joelhos e leve flexão, dê passos laterais mantendo tensão constante.', 'Glúteos|Quadríceps'],
  ['clam-shell', 'Concha Lateral com Miniband', 'Abdutores', 'Elástico', 'De lado com joelhos dobrados e pés juntos, abra o joelho de cima sem girar a pelve.', 'Rotadores externos do quadril'],
  ['aducao-decubito', 'Adução de Quadril em Decúbito Lateral', 'Adutores', 'Peso Corporal', 'De lado, cruze a perna superior à frente e eleve a perna de baixo estendida.', 'Grácil'],
  ['copenhagen-curto', 'Prancha Copenhagen com Joelho Apoiado', 'Adutores', 'Banco', 'Em prancha lateral, apoie o joelho de cima no banco e eleve a pelve mantendo tronco alinhado.', 'Oblíquos|Glúteos'],
  ['panturrilha-em-pe-maquina', 'Panturrilha em Pé na Máquina', 'Panturrilhas', 'Máquina', 'Apoie antepés na plataforma e ombros sob almofadas; eleve calcanhares e desça controladamente.', 'Sóleo'],
  ['panturrilha-sentado-halter', 'Panturrilha Sentado com Halter', 'Panturrilhas', 'Halteres', 'Sentado com joelhos dobrados e carga sobre coxas, eleve e abaixe calcanhares sem impulso.', 'Sóleo'],
  ['tibial-anterior-parede', 'Elevação dos Antepés na Parede', 'Panturrilhas', 'Peso Corporal', 'Com costas na parede e calcanhares no chão, eleve as pontas dos pés e retorne.', 'Tibial anterior'],
  ['terra-trap-bar', 'Levantamento Terra com Trap Bar', 'Corpo inteiro', 'Trap Bar', 'No centro da barra hexagonal, segure as alças e estenda joelhos e quadril mantendo coluna alinhada.', 'Quadríceps|Glúteos|Posteriores de coxa'],
  ['terra-sumo', 'Levantamento Terra Sumô com Barra', 'Corpo inteiro', 'Barra', 'Com base ampla e mãos entre as pernas, empurre o chão e estenda quadril e joelhos.', 'Adutores|Glúteos|Quadríceps'],
  ['clean-kettlebell', 'Clean Unilateral com Kettlebell', 'Corpo inteiro', 'Kettlebell', 'Partindo entre as pernas, estenda quadril e conduza o kettlebell próximo ao corpo até apoiar no antebraço.', 'Glúteos|Ombros|Abdômen/Core'],
  ['turkish-getup', 'Levantamento Turco com Kettlebell', 'Corpo inteiro', 'Kettlebell', 'Deitado com carga acima do ombro, passe pelo apoio no cotovelo, mão, meio-ajoelhado e posição em pé; reverta.', 'Ombros|Abdômen/Core|Glúteos'],
];

// id, name, anatomical target, start and execution. Static stretches have optional guidance only.
const stretches: [string, string, string, string][] = [
  ['cervical-lateral', 'Alongamento Cervical Lateral', 'Pescoço', 'Sentado ereto, incline suavemente a cabeça aproximando uma orelha do ombro, sem elevar o ombro.'],
  ['trapezio-superior', 'Alongamento de Trapézio Superior com Apoio', 'Trapézio superior', 'Sentado, segure o assento com uma mão e incline a cabeça para o lado oposto sem puxá-la.'],
  ['elevador-escapula', 'Alongamento do Elevador da Escápula', 'Elevador da escápula', 'Sentado, gire levemente a cabeça e olhe para a axila oposta, mantendo o ombro relaxado.'],
  ['cervical-rotacao', 'Rotação Cervical Leve Sustentada', 'Pescoço', 'Sentado com tronco imóvel, gire a cabeça lentamente para um lado e mantenha dentro da amplitude confortável.'],
  ['ombro-cruzado', 'Alongamento de Ombro Cruzado / Deltoide Posterior', 'Deltoide posterior', 'Em pé, leve um braço à frente do peito e aproxime-o com a outra mão acima do cotovelo.'],
  ['triceps-acima', 'Alongamento de Tríceps Acima da Cabeça', 'Tríceps', 'Sentado ou em pé, dobre um cotovelo acima da cabeça e apoie a mão oposta sem pressionar a articulação.'],
  ['biceps-parede', 'Alongamento de Bíceps na Parede', 'Bíceps', 'Ao lado da parede, apoie a palma com braço estendido atrás do tronco e gire suavemente para o lado oposto.'],
  ['flexores-punho', 'Alongamento de Flexores de Punho', 'Flexores de punho', 'Com braço à frente e palma para cima, use a outra mão para estender suavemente punho e dedos.'],
  ['extensores-punho', 'Alongamento de Extensores de Punho', 'Extensores de punho', 'Com braço à frente e palma para baixo, flexione suavemente o punho auxiliando com a outra mão.'],
  ['peitoral-batente-bilateral', 'Alongamento Bilateral de Peitoral no Batente', 'Peitoral', 'Apoie ambos os antebraços no batente e avance o tronco lentamente sem arquear a lombar.'],
  ['abertura-toracica-rolo', 'Abertura Torácica Deitado sobre Rolo Longitudinal', 'Peitoral', 'Deite com rolo firme apoiando cabeça e coluna, pés no solo; abra os braços lateralmente e relaxe.'],
  ['dorsal-banco', 'Alongamento de Grande Dorsal no Banco', 'Grande dorsal', 'Ajoelhado diante de banco firme, apoie mãos e leve quadril para trás aproximando o peito do chão.'],
  ['crianca', 'Posição da Criança', 'Costas', 'Ajoelhado, leve quadril aos calcanhares e braços à frente; ajuste afastamento dos joelhos ao conforto.'],
  ['tronco-lateral', 'Alongamento Lateral de Tronco em Pé', 'Oblíquos', 'Em pé com base estável, eleve um braço e incline suavemente o tronco para o lado oposto.'],
  ['thread-needle', 'Alongamento Thread the Needle', 'Costas', 'Em quatro apoios, passe um braço por baixo do outro e apoie suavemente o ombro no solo.'],
  ['flexor-quadril-avanco', 'Alongamento de Iliopsoas em Avanço Ajoelhado', 'Flexores do quadril', 'Em meio-ajoelhado, mantenha pelve neutra e desloque o corpo ligeiramente à frente sem arquear a lombar.'],
  ['flexor-quadril-banco', 'Alongamento de Flexores do Quadril na Borda do Banco', 'Flexores do quadril', 'Deitado na borda de banco firme, segure um joelho ao peito e deixe a outra coxa descer de modo controlado.'],
  ['gluteo-sentado', 'Alongamento de Glúteo Sentado', 'Glúteos', 'Sentado, cruze um tornozelo sobre a coxa oposta e incline o tronco pelo quadril sem pressionar o joelho.'],
  ['joelho-peito', 'Alongamento com Joelho ao Peito', 'Glúteos', 'Deitado de costas, aproxime uma coxa do tronco segurando atrás do joelho e mantenha a outra perna confortável.'],
  ['quadril-9090-estatico', 'Alongamento de Quadril 90/90 Estático', 'Rotadores do quadril', 'Sentado com ambas as pernas dobradas a 90 graus, incline o tronco sobre a perna da frente sem forçar os joelhos.'],
  ['posterior-em-pe', 'Alongamento de Posteriores em Pé com Apoio', 'Posteriores de coxa', 'Apoie um calcanhar em superfície baixa, mantenha joelho levemente destravado e incline o tronco pelo quadril.'],
  ['posterior-unilateral-sentado', 'Alongamento Unilateral de Posteriores Sentado', 'Posteriores de coxa', 'Sentado com uma perna estendida e outra dobrada, incline o tronco sobre a perna estendida.'],
  ['posterior-faixa', 'Alongamento de Posteriores Deitado com Faixa', 'Posteriores de coxa', 'Deitado, passe faixa sob um pé e eleve a perna segurando as pontas, com joelho ligeiramente destravado.'],
  ['quadriceps-lateral', 'Alongamento de Quadríceps em Decúbito Lateral', 'Quadríceps', 'Deitado de lado, segure o tornozelo de cima e aproxime o calcanhar do glúteo mantendo pelve alinhada.'],
  ['quadriceps-ajoelhado', 'Alongamento de Quadríceps Ajoelhado com Apoio', 'Quadríceps', 'Em meio-ajoelhado com apoio acolchoado, eleve o pé de trás sobre banco baixo e mantenha tronco ereto.'],
  ['adutores-borboleta', 'Alongamento de Adutores Borboleta', 'Adutores', 'Sentado, una as plantas dos pés e deixe os joelhos se afastarem sem pressioná-los com as mãos.'],
  ['adutores-abertura', 'Alongamento de Adutores Sentado em Abertura', 'Adutores', 'Sentado com pernas afastadas, incline o tronco ligeiramente à frente a partir do quadril.'],
  ['adutores-frog', 'Alongamento de Adutores Frog Stretch', 'Adutores', 'Em quatro apoios acolchoados, afaste os joelhos e desloque quadril para trás até tensão confortável.'],
  ['gastrocnemio-parede', 'Alongamento de Gastrocnêmio na Parede', 'Gastrocnêmio', 'Com mãos na parede, leve uma perna para trás e mantenha joelho estendido e calcanhar apoiado.'],
  ['soleo-parede', 'Alongamento de Sóleo na Parede', 'Sóleo', 'Com mãos na parede e um pé atrás, dobre levemente o joelho posterior sem elevar o calcanhar.'],
  ['panturrilha-degrau', 'Alongamento de Panturrilha no Degrau', 'Panturrilhas', 'Segure um apoio firme, coloque antepé no degrau e abaixe o calcanhar lentamente sem rebotes.'],
  ['tornozelo-dorsiflexao', 'Alongamento de Tornozelo em Dorsiflexão Sustentada', 'Sóleo', 'Em meio-ajoelhado, avance o joelho sobre o pé dianteiro mantendo o calcanhar no solo e sustente.'],
  ['tronco-extensao', 'Alongamento de Tronco em Apoio nos Antebraços', 'Abdômen/Core', 'De bruços, apoie os antebraços e eleve suavemente o peito mantendo a pelve no chão.'],
  ['tronco-flexao', 'Alongamento de Tronco com Joelhos ao Peito', 'Lombar', 'Deitado, aproxime ambas as coxas do tronco segurando atrás dos joelhos, sem puxões.'],
  ['rotacao-deitado', 'Alongamento em Rotação de Tronco Deitado', 'Oblíquos', 'Deitado de costas com joelhos dobrados, leve-os suavemente para um lado mantendo os ombros apoiados.'],
  ['global-parede', 'Alongamento Global com Mãos na Parede', 'Cadeia posterior', 'Apoie mãos na parede, dê passos para trás e incline o tronco pelo quadril mantendo joelhos destravados.'],
  ['sequencia-pos-treino', 'Sequência Global de Alongamentos Pós-Treino', 'Corpo inteiro', 'Em espaço livre, passe de peitoral na parede para flexores do quadril em avanço e panturrilha na parede, ajustando cada posição.'],
];
const mobility: [string, string, string, string][] = [
  ['cervical-rotacoes', 'Mobilidade Cervical em Rotações', 'Pescoço', 'Sentado ereto, gire a cabeça lentamente de um lado ao outro sem mover o tronco.'],
  ['cervical-flexao', 'Mobilidade Cervical em Flexão e Extensão', 'Pescoço', 'Sentado, olhe suavemente para baixo e retorne, depois eleve o olhar em pequena amplitude.'],
  ['open-book', 'Open Book (Abertura Torácica)', 'Coluna torácica', 'Deitado de lado com joelhos dobrados, abra o braço de cima girando o tórax, mantendo joelhos juntos.'],
  ['extensao-toracica-rolo', 'Extensão Torácica sobre Rolo', 'Coluna torácica', 'Deitado com rolo transversal sob o tórax e mãos apoiando a cabeça, estenda suavemente a região torácica.'],
  ['wall-slides', 'Wall Slides (Deslizamento na Parede)', 'Ombros', 'Diante da parede com antebraços apoiados, deslize braços para cima sem elevar as costelas.'],
  ['shoulder-cars', 'Shoulder CARs (Círculos Controlados de Ombro)', 'Ombros', 'Em pé, descreva círculo lento com um braço mantendo tronco imóvel e amplitude controlável.'],
  ['scapular-cars', 'Círculos Controlados de Escápula', 'Escápulas', 'Em pé com braços relaxados, eleve, retraia, abaixe e projete as escápulas em sequência lenta.'],
  ['scapular-pushup', 'Flexão Escapular em Quatro Apoios', 'Serrátil anterior', 'Em quatro apoios e cotovelos estendidos, aproxime e afaste as escápulas sem dobrar os braços.'],
  ['hip-cars', 'Hip CARs (Círculos Controlados de Quadril)', 'Quadril', 'Em quatro apoios, eleve um joelho dobrado, abra lateralmente e leve para trás sem girar a pelve.'],
  ['quadril-rotacao-prono', 'Rotações de Quadril em Decúbito Ventral', 'Rotadores do quadril', 'De bruços com joelhos a 90 graus, afaste e aproxime os pés lentamente mantendo pelve apoiada.'],
  ['adutor-rockback', 'Mobilidade de Adutores em Rock Back', 'Adutores', 'Em quatro apoios, estenda uma perna lateralmente e leve quadril para trás, retornando em movimento lento.'],
  ['cossack-mobilidade', 'Cossack Squat de Mobilidade com Apoio', 'Quadril', 'Com base ampla e apoio firme, transfira peso lateralmente flexionando um joelho e mantendo o outro alongado.'],
  ['deep-squat-hold', 'Deep Squat Hold com Apoio', 'Quadril', 'Segure apoio firme e desça em agachamento confortável, sustentando com pés apoiados e respiração contínua.'],
  ['worlds-greatest', "World's Greatest Stretch", 'Corpo inteiro', 'Em avanço com mãos no chão, gire um braço para o teto, retorne e estenda suavemente a perna da frente.'],
  ['hip-flexor-mobilization', 'Mobilização de Flexores do Quadril', 'Flexores do quadril', 'Em meio-ajoelhado com pelve neutra, avance e recue lentamente o corpo mantendo calcanhar dianteiro apoiado.'],
  ['tornozelo-circulos', 'Círculos de Tornozelo', 'Tornozelo', 'Sentado com um pé suspenso, descreva círculos lentos com o tornozelo nos dois sentidos.'],
  ['joelho-flexao-deslizante', 'Flexão e Extensão de Joelho com Deslizamento', 'Joelho', 'Sentado ou deitado, deslize o calcanhar aproximando-o do corpo e estenda a perna sem forçar.'],
  ['cadeia-posterior-dinamica', 'Dobradiça de Quadril Dinâmica sem Carga', 'Cadeia posterior', 'Em pé com joelhos destravados, incline pelo quadril e retorne sem arredondar deliberadamente a lombar.'],
  ['punho-quatro-apoios', 'Mobilidade de Punhos em Quatro Apoios', 'Punhos', 'Apoie mãos no solo com dedos à frente e transfira suavemente peso para frente e para trás.'],
  ['transicao-ajoelhado-agachamento', 'Transição de Meio-Ajoelhado para Agachamento', 'Corpo inteiro', 'Com apoio firme à frente, passe do meio-ajoelhado para agachamento e retorne alternando lados.'],
];
const dynamic: [string, string, string, string][] = [
  ['balanco-perna-frontal', 'Alongamento Dinâmico com Balanço Frontal de Perna', 'Posteriores de coxa', 'Em pé segurando apoio, balance uma perna à frente e atrás em amplitude progressiva sem jogar o tronco.'],
  ['balanco-perna-lateral', 'Alongamento Dinâmico com Balanço Lateral de Perna', 'Adutores', 'Segurando apoio firme, balance uma perna lateralmente e cruze-a levemente à frente sem girar a pelve.'],
  ['avanco-braco-alto', 'Alongamento Dinâmico em Avanço com Braço Elevado', 'Flexores do quadril', 'Dê um passo em avanço, eleve o braço do lado de trás e retorne à posição inicial alternando lados.'],
  ['inchworm', 'Alongamento Dinâmico Inchworm', 'Cadeia posterior', 'Em pé, alcance o chão com joelhos destravados e caminhe com mãos até prancha; retorne com controle.'],
  ['abraco-abertura', 'Alongamento Dinâmico de Peitoral com Abertura de Braços', 'Peitoral', 'Em pé, alterne abrir os braços e cruzá-los à frente do peito sem impulsos bruscos.'],
  ['calcanhar-gluteo', 'Alongamento Dinâmico de Quadríceps em Marcha', 'Quadríceps', 'Caminhe lentamente, dobrando alternadamente os joelhos para aproximar calcanhares dos glúteos.'],
];
const conditioning: Row[] = [
  ['caminhada-livre', 'Caminhada em Solo', 'Cardiorrespiratórios', 'Peso Corporal', 'Caminhe em superfície regular com passos confortáveis e ritmo definido pelo profissional.', 'Glúteos|Panturrilhas'],
  ['air-bike', 'Bicicleta de Ar (Air Bike)', 'Cardiorrespiratórios', 'Máquina', 'Ajuste o selim e movimente pedais e alças em ritmo coordenado.', 'Quadríceps|Ombros'],
  ['ski-erg', 'Ski Ergômetro', 'Cardiorrespiratórios', 'Máquina', 'Com pés apoiados, puxe alças para baixo usando braços e leve flexão do quadril, retornando controladamente.', 'Costas|Tríceps|Abdômen/Core'],
  ['marcha-estacionaria', 'Marcha Estacionária', 'Cardiorrespiratórios', 'Peso Corporal', 'Em pé, alterne elevação dos joelhos e movimento dos braços mantendo base estável.', 'Quadríceps|Flexores do quadril'],
  ['polichinelo', 'Polichinelo', 'Cardiorrespiratórios', 'Peso Corporal', 'Alterne abertura de pernas e elevação dos braços com pequenos saltos e aterrissagem controlada.', 'Panturrilhas|Ombros'],
  ['step-jack', 'Polichinelo sem Salto (Step Jack)', 'Cardiorrespiratórios', 'Peso Corporal', 'Dê um passo lateral enquanto eleva os braços; retorne e alterne o lado.', 'Glúteos|Ombros'],
  ['mountain-climber', 'Mountain Climber', 'Corpo inteiro', 'Peso Corporal', 'Em prancha alta, aproxime alternadamente os joelhos do peito mantendo ombros sobre as mãos.', 'Abdômen/Core|Ombros'],
  ['bear-crawl', 'Deslocamento em Urso (Bear Crawl)', 'Corpo inteiro', 'Peso Corporal', 'Em quatro apoios com joelhos elevados, avance mão e pé opostos em passos curtos.', 'Abdômen/Core|Ombros'],
  ['slam-ball', 'Arremesso de Medicine Ball ao Solo', 'Corpo inteiro', 'Medicine Ball', 'Eleve uma bola apropriada para arremesso e lance ao solo à frente, recolhendo com flexão de quadril e joelhos.', 'Abdômen/Core|Ombros'],
  ['sled-push', 'Empurrada de Trenó', 'Corpo inteiro', 'Trenó', 'Apoie mãos nas barras do trenó e avance com passos curtos mantendo tronco alinhado.', 'Quadríceps|Glúteos|Panturrilhas'],
  ['aquecimento-marcha-bracos', 'Aquecimento com Marcha e Círculos de Braços', 'Corpo inteiro', 'Peso Corporal', 'Marche no lugar e faça círculos pequenos e progressivos com os braços.', 'Ombros|Quadríceps'],
  ['aquecimento-agachamento-alcance', 'Aquecimento com Agachamento e Alcance', 'Corpo inteiro', 'Peso Corporal', 'Faça agachamento sem carga e, ao levantar, alcance as mãos acima da cabeça sem arquear a lombar.', 'Quadríceps|Ombros'],
  ['aquecimento-step-toque', 'Aquecimento com Passo Lateral e Toque', 'Corpo inteiro', 'Peso Corporal', 'Dê passos laterais alternados aproximando o pé de trás e movendo os braços em ritmo leve.', 'Glúteos|Panturrilhas'],
];

function region(target: string): string {
  if (/Quadr|Posterior|Glúte|Adutor|Abdutor|Panturr|Sóleo|Gastro|quadril|tornozelo|Joelho|Tornozelo/.test(target)) return 'Membros Inferiores';
  if (/Core|Lombar|Costas|torácica|posterior|Oblíquos/.test(target)) return 'Tronco / Core';
  return target === 'Corpo inteiro' || target === 'Cardiorrespiratórios' ? 'Corpo Inteiro' : 'Membros Superiores';
}
function movement(row: Row, category: string): SeedExercise {
  const [id, name, muscle_group, equipment, instructions, muscles] = row;
  return { id: `ex-${id}`, name, muscle_group, secondary_muscles: muscles.split('|'), body_region: region(muscle_group), equipment, category,
    execution_type: /Unilateral|Unipodal/.test(name) ? 'unilateral' : 'bilateral',
    mechanics: equipment === 'Máquina' ? 'máquina' : equipment === 'Cabo / Polia' ? 'cabo/polia' : equipment === 'Peso Corporal' ? 'peso corporal' : 'resistido',
    level: /Turco|Clean|Copenhagen|Trap Bar/.test(name) ? 'avancado' : 'intermediario', instructions,
    technical_notes: 'Controle a amplitude e o retorno. Ajuste apoio e resistência com o profissional; não use impulso para completar repetições.' };
}
function flexibility(rows: typeof stretches, category: string, dynamic = false): SeedExercise[] {
  return rows.map(([id, name, target, instructions]) => ({
    id: `ex-${category === 'Mobilidade' ? 'mob' : 'along'}-${id}`, name,
    muscle_group: category === 'Mobilidade' ? 'Mobilidade' : 'Alongamentos', secondary_muscles: [target],
    body_region: region(target), equipment: /Faixa/.test(name) ? 'Elástico' : /Rolo/.test(name) ? 'Rolo' : /Banco/.test(name) ? 'Banco' : 'Peso Corporal',
    category, execution_type: dynamic || category === 'Mobilidade' ? 'dinâmico' : 'estático', mechanics: category === 'Mobilidade' ? 'mobilidade' : 'flexibilidade',
    level: 'iniciante', instructions: `${instructions} Região trabalhada: ${target}.`,
    technical_notes: 'Use amplitude confortável, respire continuamente e evite rebotes ou pressão forçada. Ajuste com o profissional se houver desconforto.',
    suggested_duration: dynamic || category === 'Mobilidade' ? 'Movimentos lentos; repetições e tempo definidos pelo profissional.' : 'Referência opcional: 15–30 segundos por posição; o profissional define duração, lados e séries.'
  }));
}
export const EXPANDED_EXERCISES: SeedExercise[] = [
  ...strength.map(row => movement(row, 'Musculação')),
  ...flexibility(stretches, 'Alongamento'), ...flexibility(dynamic, 'Alongamento', true), ...flexibility(mobility, 'Mobilidade'),
  ...conditioning.map(row => movement(row, row[0].startsWith('aquecimento-') ? 'Aquecimento' : row[2] === 'Cardiorrespiratórios' ? 'Cardiorrespiratório' : 'Funcional')),
];
