export interface SeedFoodItem {
  id: string;
  name: string;
  category: string;
  portion_size: number;
  portion_unit: string;
  energy_kcal: number;
  protein_g: number;
  carbs_g: number;
  fat_g: number;
  fiber_g: number;
  sodium_mg: number;
  source: 'TACO' | 'TBCA' | 'CUSTOM';
  source_code?: string;
  source_version?: string;
  source_reference?: string;
}

export const TACO_TBCA_FOOD_CATALOG: SeedFoodItem[] = [
  // ==========================================
  // CEREAIS E DERIVADOS
  // ==========================================
  {
    id: 'food-taco-001',
    name: 'Arroz Branco Cozido',
    category: 'Cereais e Leguminosas',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 128,
    protein_g: 2.5,
    carbs_g: 28.1,
    fat_g: 0.2,
    fiber_g: 1.6,
    sodium_mg: 1,
    source: 'TACO',
    source_code: 'TAC-001',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-002',
    name: 'Arroz Integral Cozido',
    category: 'Cereais e Leguminosas',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 124,
    protein_g: 2.6,
    carbs_g: 25.8,
    fat_g: 1.0,
    fiber_g: 2.7,
    sodium_mg: 1,
    source: 'TACO',
    source_code: 'TAC-002',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-003',
    name: 'Aveia em Flocos',
    category: 'Cereais e Leguminosas',
    portion_size: 30,
    portion_unit: 'g',
    energy_kcal: 118,
    protein_g: 4.3,
    carbs_g: 20.0,
    fat_g: 2.2,
    fiber_g: 3.1,
    sodium_mg: 2,
    source: 'TACO',
    source_code: 'TAC-003',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-004',
    name: 'Pão Francês',
    category: 'Panificados',
    portion_size: 50,
    portion_unit: 'unid',
    energy_kcal: 150,
    protein_g: 4.0,
    carbs_g: 29.3,
    fat_g: 1.6,
    fiber_g: 1.2,
    sodium_mg: 324,
    source: 'TACO',
    source_code: 'TAC-004',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-005',
    name: 'Pão de Forma Integral',
    category: 'Panificados',
    portion_size: 50,
    portion_unit: 'fatia (2x)',
    energy_kcal: 123,
    protein_g: 4.7,
    carbs_g: 22.0,
    fat_g: 1.8,
    fiber_g: 3.5,
    sodium_mg: 250,
    source: 'TACO',
    source_code: 'TAC-005',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-006',
    name: 'Macarrão Cozido',
    category: 'Massas',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 102,
    protein_g: 3.3,
    carbs_g: 21.0,
    fat_g: 0.4,
    fiber_g: 1.3,
    sodium_mg: 1,
    source: 'TACO',
    source_code: 'TAC-006',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-007',
    name: 'Milho Verde Cozido',
    category: 'Cereais e Leguminosas',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 98,
    protein_g: 3.2,
    carbs_g: 17.1,
    fat_g: 1.9,
    fiber_g: 2.4,
    sodium_mg: 2,
    source: 'TACO',
    source_code: 'TAC-007',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-tbca-001',
    name: 'Quinoa Cozida',
    category: 'Cereais e Leguminosas',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 120,
    protein_g: 4.4,
    carbs_g: 21.3,
    fat_g: 1.9,
    fiber_g: 2.8,
    sodium_mg: 7,
    source: 'TBCA',
    source_code: 'TBC-001',
    source_version: 'v7.2',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - FCF/USP'
  },

  // ==========================================
  // LEGUMINOSAS
  // ==========================================
  {
    id: 'food-taco-008',
    name: 'Feijão Carioca Cozido',
    category: 'Cereais e Leguminosas',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 76,
    protein_g: 4.8,
    carbs_g: 13.6,
    fat_g: 0.5,
    fiber_g: 8.5,
    sodium_mg: 2,
    source: 'TACO',
    source_code: 'TAC-008',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-009',
    name: 'Feijão Preto Cozido',
    category: 'Cereais e Leguminosas',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 77,
    protein_g: 4.5,
    carbs_g: 14.0,
    fat_g: 0.5,
    fiber_g: 8.4,
    sodium_mg: 2,
    source: 'TACO',
    source_code: 'TAC-009',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-010',
    name: 'Feijão Fradinho Cozido',
    category: 'Cereais e Leguminosas',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 78,
    protein_g: 5.1,
    carbs_g: 13.0,
    fat_g: 0.6,
    fiber_g: 6.9,
    sodium_mg: 3,
    source: 'TACO',
    source_code: 'TAC-010',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-011',
    name: 'Grão-de-Bico Cozido',
    category: 'Cereais e Leguminosas',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 164,
    protein_g: 8.9,
    carbs_g: 27.4,
    fat_g: 2.6,
    fiber_g: 7.6,
    sodium_mg: 6,
    source: 'TACO',
    source_code: 'TAC-011',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-012',
    name: 'Lentilha Cozida',
    category: 'Cereais e Leguminosas',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 116,
    protein_g: 9.0,
    carbs_g: 20.1,
    fat_g: 0.4,
    fiber_g: 7.9,
    sodium_mg: 2,
    source: 'TACO',
    source_code: 'TAC-012',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-tbca-002',
    name: 'Tofu Fresco',
    category: 'Cereais e Leguminosas',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 76,
    protein_g: 8.1,
    carbs_g: 1.9,
    fat_g: 4.8,
    fiber_g: 0.3,
    sodium_mg: 7,
    source: 'TBCA',
    source_code: 'TBC-002',
    source_version: 'v7.2',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - FCF/USP'
  },

  // ==========================================
  // CARNES E OVOS
  // ==========================================
  {
    id: 'food-taco-013',
    name: 'Peito de Frango Grelhado',
    category: 'Carnes e Ovos',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 159,
    protein_g: 32.0,
    carbs_g: 0.0,
    fat_g: 2.5,
    fiber_g: 0.0,
    sodium_mg: 50,
    source: 'TACO',
    source_code: 'TAC-013',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-014',
    name: 'Peito de Frango Cozido Desfiado',
    category: 'Carnes e Ovos',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 163,
    protein_g: 31.5,
    carbs_g: 0.0,
    fat_g: 3.2,
    fiber_g: 0.0,
    sodium_mg: 52,
    source: 'TACO',
    source_code: 'TAC-014',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-015',
    name: 'Coxa de Frango sem Pele Assada',
    category: 'Carnes e Ovos',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 167,
    protein_g: 26.9,
    carbs_g: 0.0,
    fat_g: 5.8,
    fiber_g: 0.0,
    sodium_mg: 85,
    source: 'TACO',
    source_code: 'TAC-015',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-016',
    name: 'Ovo de Galinha Cozido',
    category: 'Carnes e Ovos',
    portion_size: 50,
    portion_unit: 'unid',
    energy_kcal: 74,
    protein_g: 6.3,
    carbs_g: 0.5,
    fat_g: 5.0,
    fiber_g: 0.0,
    sodium_mg: 70,
    source: 'TACO',
    source_code: 'TAC-016',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-017',
    name: 'Clara de Ovo Cozida',
    category: 'Carnes e Ovos',
    portion_size: 30,
    portion_unit: 'unid',
    energy_kcal: 17,
    protein_g: 3.6,
    carbs_g: 0.2,
    fat_g: 0.1,
    fiber_g: 0.0,
    sodium_mg: 55,
    source: 'TACO',
    source_code: 'TAC-017',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-018',
    name: 'Patinho Bovino Moído Grelhado',
    category: 'Carnes e Ovos',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 219,
    protein_g: 35.9,
    carbs_g: 0.0,
    fat_g: 7.3,
    fiber_g: 0.0,
    sodium_mg: 62,
    source: 'TACO',
    source_code: 'TAC-018',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-019',
    name: 'Alcatra Bovina Grelhada',
    category: 'Carnes e Ovos',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 241,
    protein_g: 31.9,
    carbs_g: 0.0,
    fat_g: 11.6,
    fiber_g: 0.0,
    sodium_mg: 54,
    source: 'TACO',
    source_code: 'TAC-019',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-020',
    name: 'Filé Mignon Bovino Grelhado',
    category: 'Carnes e Ovos',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 220,
    protein_g: 32.8,
    carbs_g: 0.0,
    fat_g: 8.8,
    fiber_g: 0.0,
    sodium_mg: 58,
    source: 'TACO',
    source_code: 'TAC-020',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-021',
    name: 'Lombo Suíno Assado',
    category: 'Carnes e Ovos',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 210,
    protein_g: 35.7,
    carbs_g: 0.0,
    fat_g: 6.4,
    fiber_g: 0.0,
    sodium_mg: 55,
    source: 'TACO',
    source_code: 'TAC-021',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },

  // ==========================================
  // PESCADOS E FRUTOS DO MAR
  // ==========================================
  {
    id: 'food-taco-022',
    name: 'Filé de Tilápia Grelhado',
    category: 'Pescados e Frutos do Mar',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 128,
    protein_g: 26.0,
    carbs_g: 0.0,
    fat_g: 2.7,
    fiber_g: 0.0,
    sodium_mg: 52,
    source: 'TACO',
    source_code: 'TAC-022',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-023',
    name: 'Salmão Grelhado',
    category: 'Pescados e Frutos do Mar',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 229,
    protein_g: 24.0,
    carbs_g: 0.0,
    fat_g: 14.0,
    fiber_g: 0.0,
    sodium_mg: 60,
    source: 'TACO',
    source_code: 'TAC-023',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-024',
    name: 'Atum em Lata Conservado em Água',
    category: 'Pescados e Frutos do Mar',
    portion_size: 60,
    portion_unit: 'g',
    energy_kcal: 72,
    protein_g: 16.0,
    carbs_g: 0.0,
    fat_g: 0.6,
    fiber_g: 0.0,
    sodium_mg: 200,
    source: 'TACO',
    source_code: 'TAC-024',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-tbca-003',
    name: 'Sardinha Cozida / Grelhada',
    category: 'Pescados e Frutos do Mar',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 164,
    protein_g: 21.0,
    carbs_g: 0.0,
    fat_g: 8.5,
    fiber_g: 0.0,
    sodium_mg: 95,
    source: 'TBCA',
    source_code: 'TBC-003',
    source_version: 'v7.2',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - FCF/USP'
  },

  // ==========================================
  // TUBÉRCULOS E RAÍZES
  // ==========================================
  {
    id: 'food-taco-025',
    name: 'Batata Doce Cozida',
    category: 'Tubérculos e Raízes',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 77,
    protein_g: 0.6,
    carbs_g: 18.4,
    fat_g: 0.1,
    fiber_g: 2.2,
    sodium_mg: 3,
    source: 'TACO',
    source_code: 'TAC-025',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-026',
    name: 'Batata Inglesa Cozida',
    category: 'Tubérculos e Raízes',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 52,
    protein_g: 1.2,
    carbs_g: 11.9,
    fat_g: 0.1,
    fiber_g: 1.3,
    sodium_mg: 1,
    source: 'TACO',
    source_code: 'TAC-026',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-027',
    name: 'Mandioca / Aipim Cozido',
    category: 'Tubérculos e Raízes',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 125,
    protein_g: 0.6,
    carbs_g: 30.1,
    fat_g: 0.3,
    fiber_g: 1.6,
    sodium_mg: 2,
    source: 'TACO',
    source_code: 'TAC-027',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-028',
    name: 'Mandioquinha / Batata-Baroa Cozida',
    category: 'Tubérculos e Raízes',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 80,
    protein_g: 0.9,
    carbs_g: 18.9,
    fat_g: 0.2,
    fiber_g: 1.8,
    sodium_mg: 2,
    source: 'TACO',
    source_code: 'TAC-028',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-tbca-004',
    name: 'Tapioca Goma Hidratada',
    category: 'Tubérculos e Raízes',
    portion_size: 50,
    portion_unit: 'g',
    energy_kcal: 118,
    protein_g: 0.2,
    carbs_g: 29.0,
    fat_g: 0.1,
    fiber_g: 0.5,
    sodium_mg: 1,
    source: 'TBCA',
    source_code: 'TBC-004',
    source_version: 'v7.2',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - FCF/USP'
  },

  // ==========================================
  // FRUTAS
  // ==========================================
  {
    id: 'food-taco-029',
    name: 'Banana Prata',
    category: 'Frutas',
    portion_size: 100,
    portion_unit: 'unid',
    energy_kcal: 98,
    protein_g: 1.3,
    carbs_g: 26.0,
    fat_g: 0.1,
    fiber_g: 2.0,
    sodium_mg: 1,
    source: 'TACO',
    source_code: 'TAC-029',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-030',
    name: 'Banana Nanica',
    category: 'Frutas',
    portion_size: 100,
    portion_unit: 'unid',
    energy_kcal: 92,
    protein_g: 1.4,
    carbs_g: 23.8,
    fat_g: 0.1,
    fiber_g: 1.9,
    sodium_mg: 1,
    source: 'TACO',
    source_code: 'TAC-030',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-031',
    name: 'Maçã Fuji com Casca',
    category: 'Frutas',
    portion_size: 100,
    portion_unit: 'unid',
    energy_kcal: 56,
    protein_g: 0.3,
    carbs_g: 15.2,
    fat_g: 0.2,
    fiber_g: 1.3,
    sodium_mg: 1,
    source: 'TACO',
    source_code: 'TAC-031',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-032',
    name: 'Mamão Papaia',
    category: 'Frutas',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 40,
    protein_g: 0.5,
    carbs_g: 10.4,
    fat_g: 0.1,
    fiber_g: 1.0,
    sodium_mg: 2,
    source: 'TACO',
    source_code: 'TAC-032',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-033',
    name: 'Laranja Pera',
    category: 'Frutas',
    portion_size: 100,
    portion_unit: 'unid',
    energy_kcal: 37,
    protein_g: 1.0,
    carbs_g: 8.9,
    fat_g: 0.1,
    fiber_g: 0.8,
    sodium_mg: 1,
    source: 'TACO',
    source_code: 'TAC-033',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-034',
    name: 'Melancia',
    category: 'Frutas',
    portion_size: 100,
    portion_unit: 'fatia',
    energy_kcal: 33,
    protein_g: 0.9,
    carbs_g: 8.1,
    fat_g: 0.0,
    fiber_g: 0.1,
    sodium_mg: 1,
    source: 'TACO',
    source_code: 'TAC-034',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-035',
    name: 'Abacaxi Pérola',
    category: 'Frutas',
    portion_size: 100,
    portion_unit: 'fatia',
    energy_kcal: 48,
    protein_g: 0.9,
    carbs_g: 12.3,
    fat_g: 0.1,
    fiber_g: 1.0,
    sodium_mg: 1,
    source: 'TACO',
    source_code: 'TAC-035',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-036',
    name: 'Morango Fresco',
    category: 'Frutas',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 30,
    protein_g: 0.9,
    carbs_g: 6.8,
    fat_g: 0.3,
    fiber_g: 1.7,
    sodium_mg: 1,
    source: 'TACO',
    source_code: 'TAC-036',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-037',
    name: 'Abacate',
    category: 'Frutas',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 96,
    protein_g: 1.2,
    carbs_g: 6.0,
    fat_g: 8.4,
    fiber_g: 6.3,
    sodium_mg: 1,
    source: 'TACO',
    source_code: 'TAC-037',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-tbca-005',
    name: 'Manga Palmer',
    category: 'Frutas',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 60,
    protein_g: 0.8,
    carbs_g: 15.0,
    fat_g: 0.2,
    fiber_g: 1.6,
    sodium_mg: 2,
    source: 'TBCA',
    source_code: 'TBC-005',
    source_version: 'v7.2',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - FCF/USP'
  },

  // ==========================================
  // HORTALIÇAS E LEGUMES
  // ==========================================
  {
    id: 'food-taco-038',
    name: 'Brócolis Cozido',
    category: 'Hortaliças e Legumes',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 25,
    protein_g: 2.1,
    carbs_g: 4.4,
    fat_g: 0.5,
    fiber_g: 3.4,
    sodium_mg: 3,
    source: 'TACO',
    source_code: 'TAC-038',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-039',
    name: 'Alface Crespa',
    category: 'Hortaliças e Legumes',
    portion_size: 50,
    portion_unit: 'g',
    energy_kcal: 6,
    protein_g: 0.6,
    carbs_g: 1.0,
    fat_g: 0.1,
    fiber_g: 0.9,
    sodium_mg: 2,
    source: 'TACO',
    source_code: 'TAC-039',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-040',
    name: 'Cenoura Crua Ralada',
    category: 'Hortaliças e Legumes',
    portion_size: 50,
    portion_unit: 'g',
    energy_kcal: 17,
    protein_g: 0.7,
    carbs_g: 3.9,
    fat_g: 0.1,
    fiber_g: 1.6,
    sodium_mg: 29,
    source: 'TACO',
    source_code: 'TAC-040',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-041',
    name: 'Tomate com Semente',
    category: 'Hortaliças e Legumes',
    portion_size: 100,
    portion_unit: 'unid',
    energy_kcal: 15,
    protein_g: 1.1,
    carbs_g: 3.1,
    fat_g: 0.2,
    fiber_g: 1.2,
    sodium_mg: 1,
    source: 'TACO',
    source_code: 'TAC-041',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-042',
    name: 'Couve Manteiga Refogada',
    category: 'Hortaliças e Legumes',
    portion_size: 50,
    portion_unit: 'g',
    energy_kcal: 45,
    protein_g: 1.5,
    carbs_g: 4.3,
    fat_g: 2.8,
    fiber_g: 2.2,
    sodium_mg: 2,
    source: 'TACO',
    source_code: 'TAC-042',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-043',
    name: 'Abobrinha Italiana Cozida',
    category: 'Hortaliças e Legumes',
    portion_size: 100,
    portion_unit: 'g',
    energy_kcal: 15,
    protein_g: 1.1,
    carbs_g: 3.0,
    fat_g: 0.2,
    fiber_g: 1.6,
    sodium_mg: 1,
    source: 'TACO',
    source_code: 'TAC-043',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },

  // ==========================================
  // LATICÍNIOS E DERIVADOS
  // ==========================================
  {
    id: 'food-taco-044',
    name: 'Leite de Vaca Desnatado',
    category: 'Leites e Derivados',
    portion_size: 200,
    portion_unit: 'ml',
    energy_kcal: 70,
    protein_g: 6.0,
    carbs_g: 10.0,
    fat_g: 0.0,
    fiber_g: 0.0,
    sodium_mg: 108,
    source: 'TACO',
    source_code: 'TAC-044',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-045',
    name: 'Leite de Vaca Integral',
    category: 'Leites e Derivados',
    portion_size: 200,
    portion_unit: 'ml',
    energy_kcal: 120,
    protein_g: 6.0,
    carbs_g: 9.0,
    fat_g: 6.4,
    fiber_g: 0.0,
    sodium_mg: 128,
    source: 'TACO',
    source_code: 'TAC-045',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-046',
    name: 'Iogurte Natural Desnatado',
    category: 'Leites e Derivados',
    portion_size: 170,
    portion_unit: 'pote',
    energy_kcal: 85,
    protein_g: 7.0,
    carbs_g: 10.0,
    fat_g: 0.5,
    fiber_g: 0.0,
    sodium_mg: 100,
    source: 'TACO',
    source_code: 'TAC-046',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-047',
    name: 'Queijo Minas Frescal',
    category: 'Leites e Derivados',
    portion_size: 50,
    portion_unit: 'fatia',
    energy_kcal: 132,
    protein_g: 8.7,
    carbs_g: 1.6,
    fat_g: 10.1,
    fiber_g: 0.0,
    sodium_mg: 160,
    source: 'TACO',
    source_code: 'TAC-047',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-tbca-006',
    name: 'Queijo Cottage',
    category: 'Leites e Derivados',
    portion_size: 50,
    portion_unit: 'g',
    energy_kcal: 49,
    protein_g: 6.2,
    carbs_g: 1.7,
    fat_g: 2.0,
    fiber_g: 0.0,
    sodium_mg: 180,
    source: 'TBCA',
    source_code: 'TBC-006',
    source_version: 'v7.2',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - FCF/USP'
  },
  {
    id: 'food-tbca-007',
    name: 'Queijo Ricota',
    category: 'Leites e Derivados',
    portion_size: 50,
    portion_unit: 'fatia',
    energy_kcal: 70,
    protein_g: 5.5,
    carbs_g: 1.9,
    fat_g: 4.5,
    fiber_g: 0.0,
    sodium_mg: 84,
    source: 'TBCA',
    source_code: 'TBC-007',
    source_version: 'v7.2',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - FCF/USP'
  },

  // ==========================================
  // ÓLEOS, GORDURAS E OLEAGINOSAS
  // ==========================================
  {
    id: 'food-taco-048',
    name: 'Azeite de Oliva Extra Virgem',
    category: 'Óleos e Gorduras',
    portion_size: 10,
    portion_unit: 'ml (1 c. sopa)',
    energy_kcal: 88,
    protein_g: 0.0,
    carbs_g: 0.0,
    fat_g: 10.0,
    fiber_g: 0.0,
    sodium_mg: 0,
    source: 'TACO',
    source_code: 'TAC-048',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-049',
    name: 'Castanha-do-Pará (Castanha-do-Brasil)',
    category: 'Oleaginosas e Sementes',
    portion_size: 15,
    portion_unit: 'g (3 unid)',
    energy_kcal: 98,
    protein_g: 2.2,
    carbs_g: 1.8,
    fat_g: 9.5,
    fiber_g: 1.1,
    sodium_mg: 0,
    source: 'TACO',
    source_code: 'TAC-049',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-taco-050',
    name: 'Castanha de Caju Torrada',
    category: 'Oleaginosas e Sementes',
    portion_size: 20,
    portion_unit: 'g',
    energy_kcal: 114,
    protein_g: 3.7,
    carbs_g: 6.0,
    fat_g: 9.2,
    fiber_g: 0.8,
    sodium_mg: 3,
    source: 'TACO',
    source_code: 'TAC-050',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-tbca-008',
    name: 'Pasta de Amendoim Integral',
    category: 'Oleaginosas e Sementes',
    portion_size: 15,
    portion_unit: 'g (1 c. sopa)',
    energy_kcal: 90,
    protein_g: 4.1,
    carbs_g: 3.0,
    fat_g: 7.5,
    fiber_g: 1.0,
    sodium_mg: 2,
    source: 'TBCA',
    source_code: 'TBC-008',
    source_version: 'v7.2',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - FCF/USP'
  },
  {
    id: 'food-tbca-009',
    name: 'Semente de Chia',
    category: 'Oleaginosas e Sementes',
    portion_size: 15,
    portion_unit: 'g (1 c. sopa)',
    energy_kcal: 73,
    protein_g: 2.5,
    carbs_g: 6.3,
    fat_g: 4.6,
    fiber_g: 5.1,
    sodium_mg: 2,
    source: 'TBCA',
    source_code: 'TBC-009',
    source_version: 'v7.2',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - FCF/USP'
  },

  // ==========================================
  // SUPLEMENTOS
  // ==========================================
  {
    id: 'food-taco-051',
    name: 'Whey Protein Concentrado 80%',
    category: 'Suplementos',
    portion_size: 30,
    portion_unit: 'dose (1 scoop)',
    energy_kcal: 120,
    protein_g: 24.0,
    carbs_g: 2.0,
    fat_g: 1.5,
    fiber_g: 0.0,
    sodium_mg: 55,
    source: 'TACO',
    source_code: 'TAC-051',
    source_version: '4ª Edição',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - NEPA/UNICAMP'
  },
  {
    id: 'food-tbca-010',
    name: 'Whey Protein Isolado 90%',
    category: 'Suplementos',
    portion_size: 30,
    portion_unit: 'dose (1 scoop)',
    energy_kcal: 110,
    protein_g: 27.0,
    carbs_g: 0.5,
    fat_g: 0.3,
    fiber_g: 0.0,
    sodium_mg: 45,
    source: 'TBCA',
    source_code: 'TBC-010',
    source_version: 'v7.2',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - FCF/USP'
  },
  {
    id: 'food-tbca-011',
    name: 'Creatina Monohidratada 100%',
    category: 'Suplementos',
    portion_size: 5,
    portion_unit: 'g (1 dosador)',
    energy_kcal: 0,
    protein_g: 0.0,
    carbs_g: 0.0,
    fat_g: 0.0,
    fiber_g: 0.0,
    sodium_mg: 0,
    source: 'TBCA',
    source_code: 'TBC-011',
    source_version: 'v7.2',
    source_reference: 'Tabela Brasileira de Composição de Alimentos - FCF/USP'
  }
];

export function seedNutritionFoodDatabase(db: any): void {
  try {
    // 1. Garante que as colunas de metadados existam na tabela nutrition_food_database
    const cols = (db.prepare('PRAGMA table_info(nutrition_food_database)').all() as any[]).map(c => c.name);
    if (!cols.includes('source')) {
      db.exec("ALTER TABLE nutrition_food_database ADD COLUMN source TEXT DEFAULT 'TACO'");
    }
    if (!cols.includes('source_code')) {
      db.exec('ALTER TABLE nutrition_food_database ADD COLUMN source_code TEXT');
    }
    if (!cols.includes('source_version')) {
      db.exec('ALTER TABLE nutrition_food_database ADD COLUMN source_version TEXT');
    }
    if (!cols.includes('source_reference')) {
      db.exec('ALTER TABLE nutrition_food_database ADD COLUMN source_reference TEXT');
    }

    // 2. Verifica se a base pública (tenant_id IS NULL) já está devidamente semeada
    const countRow = db.prepare('SELECT COUNT(*) as c FROM nutrition_food_database WHERE tenant_id IS NULL AND is_clinic_custom = 0').get() as any;
    const currentCount = Number(countRow?.c || 0);

    // Se houver menos de 40 alimentos públicos, insere o catálogo completo TACO / TBCA de forma idempotente
    if (currentCount < 40) {
      const insertStmt = db.prepare(`
        INSERT INTO nutrition_food_database (
          id, tenant_id, name, category, portion_size, portion_unit,
          energy_kcal, protein_g, carbs_g, fat_g, fiber_g, sodium_mg,
          is_clinic_custom, source, source_code, source_version, source_reference
        ) VALUES (
          ?, NULL, ?, ?, ?, ?,
          ?, ?, ?, ?, ?, ?,
          0, ?, ?, ?, ?
        )
      `);

      for (const item of TACO_TBCA_FOOD_CATALOG) {
        // Verifica se já existe alimento público com o mesmo nome para evitar duplicata
        const exists = db.prepare('SELECT id FROM nutrition_food_database WHERE tenant_id IS NULL AND name = ?').get(item.name);
        if (!exists) {
          insertStmt.run(
            item.id,
            item.name,
            item.category,
            item.portion_size,
            item.portion_unit,
            item.energy_kcal,
            item.protein_g,
            item.carbs_g,
            item.fat_g,
            item.fiber_g,
            item.sodium_mg,
            item.source,
            item.source_code || null,
            item.source_version || null,
            item.source_reference || null
          );
        }
      }
      console.log('[NutritionFoodSeed] Catálogo oficial TACO / TBCA semeado com sucesso!');
    }
  } catch (err) {
    console.warn('[NutritionFoodSeed] Aviso ao semear catálogo TACO / TBCA:', err);
  }
}
