import { test, expect } from '../../helpers/audit-test';
import { password, apiLogin } from '../../helpers/session';

test('@critical Landing → cadastro pela interface → OTP → teste grátis → perfil → Agenda', async ({ page, request }) => {
  await page.addLocatorHandler(page.getByRole('button', { name: 'Rejeitar não necessários', exact: true }), button => button.click());
  await page.goto('/');
  await page.getByRole('button', { name: 'COMEÇAR AGORA', exact: true }).last().click();
  await page.getByPlaceholder('Nome completo', { exact: true }).fill('e2e-user-cadastro-browser');
  await page.getByPlaceholder('(54) 99999-9999', { exact: true }).fill('11999990000');
  await page.locator('#signup-email').fill('e2e-browser-registration@test.invalid');
  await page.getByRole('combobox', { name: 'Profissão', exact: true }).click();
  await page.getByRole('option', { name: /Fisioterapeuta|Fisioterapia/ }).first().click();
  await page.getByPlaceholder('Mínimo 6 caracteres', { exact: true }).fill(password);
  await page.getByPlaceholder('Repita a senha', { exact: true }).fill(password);
  await page.getByRole('checkbox', { name: /Li e aceito os/ }).check();
  await page.getByRole('checkbox', { name: /Li e aceito a/ }).check();
  const registered = page.waitForResponse(r => r.url().endsWith('/public/tenants/register') && r.request().method() === 'POST');
  await page.getByRole('button', { name: 'CRIAR MINHA CONTA', exact: true }).click();
  expect((await registered).status()).toBe(201);
  await expect(page.getByRole('heading', { name: 'Confirme seu E-mail', exact: true })).toBeVisible();
  const otp = page.locator('input[maxlength="1"]');
  for (let index=0; index<6; index++) await otp.nth(index).fill(String(index+1));
  await page.getByRole('button', { name: 'Começar teste grátis (7 dias)', exact: true }).first().click();
  await page.getByPlaceholder('Ex: 12345/SP', { exact: true }).fill('E2E-SYNTHETIC');
  const activated = page.waitForResponse(r => r.url().endsWith('/onboarding/complete-profile') && r.request().method() === 'POST');
  await page.getByRole('button', { name: 'Concluir e Acessar o Sistema', exact: true }).click();
  expect((await activated).ok()).toBe(true);
  await page.getByRole('button', { name: 'Não mostrar novamente', exact: true }).click();
  await page.getByRole('button', { name: 'Agenda Interativa', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Agendar', exact: true })).toBeVisible();
  const headers = await apiLogin(request, 'e2e-browser-registration');
  const professionals = await request.get('/api/v1/professionals', { headers });
  expect(professionals.ok()).toBe(true);
  const professional = (await professionals.json())[0];
  expect(professional).toBeTruthy();
  const schedules = await request.get(`/api/v1/professionals/${professional.id}`, { headers });
  expect(schedules.ok()).toBe(true);
  expect(JSON.stringify(await schedules.json())).toContain('08:00');
});
